Repository cakephp/cakephp, pull requests merged in 2018-11, with the labels that each got.

#12698 Add disable methods
  src/Controller/Controller.php
  src/Database/Connection.php
  src/Database/Driver.php
  src/Database/DriverInterface.php
  src/Database/Query.php
  src/Datasource/ConnectionInterface.php
  src/Http/Session/DatabaseSession.php
  src/ORM/Association/Loader/SelectLoader.php
  src/ORM/Behavior/TranslateBehavior.php
  src/ORM/Behavior/TreeBehavior.php
  src/ORM/EagerLoader.php
  src/ORM/Query.php
  src/ORM/Table.php
  src/TestSuite/Fixture/FixtureManager.php
  src/View/View.php
  src/View/ViewBuilder.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Database/DriverTest.php
  tests/TestCase/ORM/QueryTest.php
  tests/TestCase/View/ViewBuilderTest.php
  tests/TestCase/View/ViewTest.php
Labels: Enhancement

#12699 4x - Support default values in cache engine
  src/Cache/Engine/ApcuEngine.php
  src/Cache/Engine/FileEngine.php
  src/Cache/Engine/MemcachedEngine.php
  src/Cache/Engine/RedisEngine.php
  src/Cache/Engine/WincacheEngine.php
  tests/TestCase/Cache/Engine/ApcuEngineTest.php
  tests/TestCase/Cache/Engine/FileEngineTest.php
  tests/TestCase/Cache/Engine/MemcachedEngineTest.php
  tests/TestCase/Cache/Engine/RedisEngineTest.php
  tests/TestCase/Cache/Engine/WincacheEngineTest.php
Labels: cache

#12695 Fix router reload regression in integration testing.
  src/TestSuite/IntegrationTestCase.php
  src/TestSuite/MiddlewareDispatcher.php
  tests/TestCase/Routing/Filter/RoutingFilterTest.php
  tests/TestCase/Routing/RouteBuilderTest.php
  tests/TestCase/TestSuite/IntegrationTestCaseTest.php
  tests/test_app/TestApp/Application.php
  tests/test_app/TestApp/ApplicationWithDefaultRoutes.php
  tests/test_app/TestApp/ApplicationWithPluginRoutes.php
  tests/test_app/TestApp/Controller/PostsController.php
  tests/test_app/config/routes.php
Labels: Defect

#12704 3.next - Add TestCase method to drop plugins.
  config/bootstrap.php
  src/TestSuite/TestCase.php
  tests/TestCase/Auth/FormAuthenticateTest.php
  tests/TestCase/Auth/PasswordHasherFactoryTest.php
  tests/TestCase/Cache/CacheTest.php
  tests/TestCase/Command/HelpCommandTest.php
  tests/TestCase/Console/CommandCollectionTest.php
  tests/TestCase/Console/HelperRegistryTest.php
  tests/TestCase/Console/ShellDispatcherTest.php
  tests/TestCase/Console/ShellTest.php
  tests/TestCase/Console/TaskRegistryTest.php
  tests/TestCase/Controller/ComponentRegistryTest.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Core/AppTest.php
  tests/TestCase/Core/BasePluginTest.php
  tests/TestCase/Core/Configure/Engine/IniConfigTest.php
  tests/TestCase/Core/Configure/Engine/JsonConfigTest.php
  tests/TestCase/Core/Configure/Engine/PhpConfigTest.php
  tests/TestCase/Core/ConfigureTest.php
  tests/TestCase/Core/PluginTest.php
  tests/TestCase/Datasource/ConnectionManagerTest.php
  tests/TestCase/Error/ErrorHandlerTest.php
  tests/TestCase/Error/ExceptionRendererTest.php
  tests/TestCase/Http/BaseApplicationTest.php
  tests/TestCase/Http/SessionTest.php
  tests/TestCase/I18n/I18nTest.php
  tests/TestCase/Log/LogTest.php
  tests/TestCase/Mailer/EmailTest.php
  tests/TestCase/ORM/AssociationTest.php
  tests/TestCase/ORM/BehaviorRegistryTest.php
  tests/TestCase/ORM/Locator/TableLocatorTest.php
  tests/TestCase/ORM/QueryRegressionTest.php
  tests/TestCase/ORM/ResultSetTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/Routing/DispatcherTest.php
  tests/TestCase/Routing/Filter/AssetFilterTest.php
  tests/TestCase/Routing/Middleware/AssetMiddlewareTest.php
  tests/TestCase/Routing/RequestActionTraitTest.php
  tests/TestCase/Routing/RouteBuilderTest.php
  tests/TestCase/Routing/RouterTest.php
  tests/TestCase/Shell/CommandListShellTest.php
  tests/TestCase/Shell/CompletionShellTest.php
  tests/TestCase/Shell/Task/AssetsTaskTest.php
  tests/TestCase/Shell/Task/ExtractTaskTest.php
  tests/TestCase/Shell/Task/UnloadTaskTest.php
  tests/TestCase/TestSuite/FixtureManagerTest.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
  tests/TestCase/TestSuite/TestCaseTest.php
  tests/TestCase/View/CellTest.php
  tests/TestCase/View/Helper/FlashHelperTest.php
  tests/TestCase/View/Helper/HtmlHelperTest.php
  tests/TestCase/View/Helper/NumberHelperTest.php
  tests/TestCase/View/Helper/TextHelperTest.php
  tests/TestCase/View/Helper/UrlHelperTest.php
  tests/TestCase/View/HelperRegistryTest.php
  tests/TestCase/View/HelperTest.php
  tests/TestCase/View/StringTemplateTest.php
  tests/TestCase/View/ViewTest.php
  tests/TestCase/View/Widget/WidgetLocatorTest.php
Labels: plugins, testing

#12703 Remove deprecated code from 4.x
  src/Core/Plugin.php
  src/Http/Middleware/SecurityHeadersMiddleware.php
  src/Mailer/Email.php
  src/ORM/Table.php
  src/ORM/TableRegistry.php
  tests/TestCase/Collection/CollectionTest.php
  tests/TestCase/Core/PluginTest.php
  tests/TestCase/Error/Middleware/ErrorHandlerMiddlewareTest.php
  tests/TestCase/ORM/ResultSetTest.php
Labels: deprecations

#12711 4x - Implement TTL parameters for cache engines
  src/Cache/CacheEngine.php
  src/Cache/Engine/ApcuEngine.php
  src/Cache/Engine/FileEngine.php
  src/Cache/Engine/MemcachedEngine.php
  src/Cache/Engine/RedisEngine.php
  src/Cache/Engine/WincacheEngine.php
  tests/TestCase/Cache/Engine/ApcuEngineTest.php
  tests/TestCase/Cache/Engine/FileEngineTest.php
  tests/TestCase/Cache/Engine/MemcachedEngineTest.php
  tests/TestCase/Cache/Engine/RedisEngineTest.php
  tests/TestCase/Cache/Engine/WincacheEngineTest.php
Labels: Enhancement, cache

#12714 Fix paginator defaulting for multi-default-sort.
  src/Datasource/Paginator.php
  src/View/Helper/PaginatorHelper.php
  tests/TestCase/Datasource/PaginatorTest.php
Labels: Defect

#12719 Fix invalid value of htmlspecialchars argument
  src/Core/functions.php
Labels: Defect

#12718 Fix some PHP 7.3 errors
  .travis.yml
  lib/Cake/Console/Command/Task/ModelTask.php
  lib/Cake/Core/App.php
  lib/Cake/Model/Permission.php
  lib/Cake/Test/Case/Console/Command/Task/ExtractTaskTest.php
  lib/Cake/Test/Case/I18n/MultibyteTest.php
  lib/Cake/Utility/Debugger.php
Labels: Enhancement

#12724 Remove Mailer @methods annotation of removed functions in 4.0
  src/Mailer/Mailer.php
Labels: documentation

#12663 Use Locale::lookup to handle generic options as a fallback
  src/I18n/Middleware/LocaleSelectorMiddleware.php
  tests/TestCase/I18n/Middleware/LocaleSelectorMiddlewareTest.php
Labels: middleware

#12726 Resolves the first part of object variable naming cleanup.
  src/Auth/BasicAuthenticate.php
  src/Console/ShellDispatcher.php
  src/Console/TaskRegistry.php
  src/Event/Event.php
  src/Mailer/Email.php
  src/ORM/Behavior.php
  src/Shell/Task/CommandTask.php
  src/Utility/Hash.php
  src/View/Helper.php
  src/View/Helper/FormHelper.php
  src/View/Helper/HtmlHelper.php
  src/View/Helper/NumberHelper.php
  src/View/Helper/PaginatorHelper.php
  src/View/Helper/TextHelper.php
Labels: Enhancement

#12733 Fix return type in of `countBy` @method annotation in Query
  src/ORM/Query.php
Labels: documentation

#12739 Fix docblocks
  src/Routing/Middleware/RoutingMiddleware.php
Labels: documentation

#12748 add missing namespace
  src/Routing/Middleware/RoutingMiddleware.php
Labels: routing

#12735 Dasherize path elements by default instead of underscoring.
  src/Routing/RouteBuilder.php
  src/Routing/Router.php
  tests/TestCase/Routing/RouterTest.php
Labels: Enhancement

#12741 3.next - Add ArrayCache engine
  src/Cache/Engine/ArrayEngine.php
  tests/TestCase/Cache/Engine/ArrayEngineTest.php
Labels: Enhancement, cache

#12760 Fix NullEngine::write() return value to match abstract method's signature - issue #12758
  src/Cache/Engine/NullEngine.php
  tests/TestCase/Cache/CacheTest.php
Labels: Defect

#12761 Test with SQLite first to get first results faster
  .travis.yml
Labels: testing

#12754 Remove deprecated usage.
  src/Command/HelpCommand.php
  src/Console/ConsoleOptionParser.php
  tests/TestCase/Command/HelpCommandTest.php
Labels: deprecations

#12113 4.x TranslateBehavior strategies
  psalm.xml
  src/ORM/Behavior/Translate/EavStrategy.php
  src/ORM/Behavior/Translate/ShadowTableStrategy.php
  src/ORM/Behavior/Translate/TranslateStrategyInterface.php
  src/ORM/Behavior/Translate/TranslateStrategyTrait.php
  src/ORM/Behavior/TranslateBehavior.php
  tests/Fixture/ArticlesMoreTranslationsFixture.php
  tests/Fixture/ArticlesTranslationsFixture.php
  tests/Fixture/AuthorsTranslationsFixture.php
  tests/Fixture/CommentsTranslationsFixture.php
  tests/Fixture/GroupsTranslationsFixture.php
  tests/Fixture/SpecialTagsTranslationsFixture.php
  tests/Fixture/TagsShadowTranslationsFixture.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorShadowTableTest.php
Labels: Enhancement

#12769 Run cache tests when collecting coverage
  .travis.yml
Labels: testing

#12770 Fix Association::$finder type
  src/ORM/Association.php
Labels: documentation

#12765 Add deprecation warning for routing middleware
  src/Routing/Middleware/RoutingMiddleware.php
  tests/TestCase/Routing/Middleware/RoutingMiddlewareTest.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
  tests/test_app/TestApp/Application.php
Labels: routing

#12768 Fix incorrect alias name on joined associations
  src/ORM/ResultSet.php
  tests/TestCase/ORM/Association/BelongsToTest.php
  tests/TestCase/ORM/QueryTest.php
Labels: ORM
