Repository cakephp/cakephp, pull requests merged in 2018-12, with the labels that each got.

#12745 Fix paginator for falling back to default sort.
  src/Datasource/Paginator.php
  src/View/Helper/PaginatorHelper.php
  tests/TestCase/Datasource/PaginatorTest.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
Labels: Defect

#12779 Get just the header_size instead of all curl options
  src/Http/Client/Adapter/Curl.php
Labels: Enhancement

#12780 Fix doc blocks
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Http/Client/Auth/OauthTest.php
  tests/TestCase/Mailer/MailerTest.php
Labels: documentation

#12777 Form Helper maxlength attribute uses validation #12773
  src/View/Form/ArrayContext.php
  src/View/Form/ContextInterface.php
  src/View/Form/EntityContext.php
  src/View/Form/FormContext.php
  src/View/Form/NullContext.php
  src/View/Helper/FormHelper.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: Enhancement

#12783 3.7 cell - exception
  src/View/Cell.php
Labels: view

#12794 Fixed regression in assertCookieNotSet
  src/TestSuite/Constraint/Response/CookieSet.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
  tests/test_app/TestApp/Controller/CookieComponentTestController.php
Labels: Defect, testing

#12796 Ensure case sensitive method name matching when invoking action.
  src/Controller/Component/AuthComponent.php
  src/Controller/Controller.php
  tests/TestCase/Controller/ControllerTest.php
Labels: Enhancement

#12814 Add missing docblock for typehint.
  src/I18n/Number.php
Labels: documentation

#12803 Remove duplicate code from IntegerType
  src/Database/Type/IntegerType.php
Labels: database

#12819 allow incorrect decimal / float formatting
  src/Database/Type/DecimalType.php
  src/Database/Type/FloatType.php
  tests/TestCase/Database/Type/DecimalTypeTest.php
  tests/TestCase/Database/Type/FloatTypeTest.php
Labels: Defect

#12818 Fix typehints
  src/Database/Schema/TableSchemaInterface.php
Labels: documentation

#12816 Fix docblocks and better IDE and static analyzer discoverery.
  src/Collection/CollectionInterface.php
  src/Collection/CollectionTrait.php
  src/Collection/Iterator/FilterIterator.php
  src/Routing/Router.php
  tests/TestCase/Controller/Component/AuthComponentTest.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
  tests/TestCase/Routing/Middleware/RoutingMiddlewareTest.php
  tests/TestCase/Routing/RouteBuilderTest.php
  tests/TestCase/Routing/RouterTest.php
  tests/TestCase/Shell/Helper/ProgressHelperTest.php
Labels: documentation

#12808 Improve support of enum data type
  lib/Cake/Model/CakeSchema.php
  lib/Cake/Model/Datasource/Database/Mysql.php
  lib/Cake/Model/Datasource/DboSource.php
  lib/Cake/Test/Case/Model/CakeSchemaTest.php
  lib/Cake/Test/Case/Model/Datasource/Database/MysqlTest.php
  lib/Cake/Test/Case/Model/Datasource/DboSourceTest.php
Labels: models

#12822 Use annotitations for integration trait setup/teardown
  src/TestSuite/IntegrationTestTrait.php
Labels: testing

#12821 Update typehints.
  src/Collection/CollectionInterface.php
  src/Collection/CollectionTrait.php
  src/Database/Statement/BufferedStatement.php
  src/Http/Client/Response.php
  src/TestSuite/IntegrationTestTrait.php
  src/TestSuite/TestCase.php
  src/Validation/Validator.php
  src/View/Form/ArrayContext.php
  src/View/Form/ContextInterface.php
  src/View/Form/EntityContext.php
  src/View/Form/FormContext.php
  src/View/Form/NullContext.php
  src/View/View.php
Labels: documentation

#12825 Fix notice error on missing argument
  src/Console/Arguments.php
  tests/TestCase/Console/ArgumentsTest.php
Labels: console

#12826 createFile() should create directories.
  src/Console/ConsoleIo.php
  tests/TestCase/Console/ConsoleIoTest.php
Labels: console

#12828 shells => commands in docs block
  src/Command/HelpCommand.php
Labels: documentation

#12824 Enable subcommands to use spaces.
  src/Console/CommandCollection.php
  src/Console/CommandRunner.php
  tests/TestCase/Console/CommandCollectionTest.php
  tests/TestCase/Console/CommandRunnerTest.php
Labels: console

#12830 Fixing Typehints
  src/View/ViewBuilder.php
Labels: documentation

#12837 Fixes docblock for View::set()
  lib/Cake/View/View.php
Labels: documentation

#12842 Fix error code check.
  src/Http/Client/Adapter/Curl.php
Labels: Defect, http client

#12844 Remove redundant conditional checks.
  psalm.xml
  src/Console/Command.php
  src/Console/ConsoleOptionParser.php
  src/Controller/Component/SecurityComponent.php
  src/Core/ObjectRegistry.php
  src/Core/StaticConfigTrait.php
  src/Database/Dialect/SqlserverDialectTrait.php
  src/Database/Schema/MysqlSchema.php
  src/Database/SqlserverCompiler.php
  src/Datasource/EntityTrait.php
  src/Http/Server.php
  src/Http/ServerRequest.php
  src/ORM/BehaviorRegistry.php
  src/ORM/Marshaller.php
  src/ORM/Query.php
  src/ORM/Table.php
  src/Routing/Route/Route.php
  src/Shell/Helper/TableHelper.php
  src/Utility/Hash.php
  src/Validation/Validation.php
  src/View/AjaxView.php
  src/View/Form/EntityContext.php
  src/View/Helper/FormHelper.php
  src/View/Helper/PaginatorHelper.php
Labels: Enhancement

#12846 Fix nullable docblocks
  src/Controller/Component/AuthComponent.php
Labels: documentation
