Repository cakephp/cakephp, pull requests merged in 2018-06, with the labels that each got.

#12167 Try to get travis to pass again.
  src/Collection/CollectionInterface.php
  src/Collection/CollectionTrait.php
  src/Collection/Iterator/SortIterator.php
  src/Utility/Hash.php
  tests/TestCase/Collection/Iterator/SortIteratorTest.php
Labels: testing

#12169 Fix #12168 - Stream restores error handler on exception
  src/Http/Client/Adapter/Stream.php
  tests/TestCase/Http/Client/Adapter/StreamTest.php
Labels: errorhandler, http

#12172 4.x: Use EventInterface instead of Event for typehints.
  src/Auth/BaseAuthenticate.php
  src/Controller/Component.php
  src/Controller/Component/AuthComponent.php
  src/Controller/Component/RequestHandlerComponent.php
  src/Controller/Component/SecurityComponent.php
  src/Controller/Controller.php
  src/Controller/ErrorController.php
  src/Event/Decorator/ConditionDecorator.php
  src/Event/Decorator/SubjectFilterDecorator.php
  src/Event/EventDispatcherInterface.php
  src/Event/EventDispatcherTrait.php
  src/Event/EventList.php
  src/Event/EventManager.php
  src/Mailer/Mailer.php
  src/ORM/Behavior.php
  src/ORM/Behavior/CounterCacheBehavior.php
  src/ORM/Behavior/TimestampBehavior.php
  src/ORM/Behavior/TranslateBehavior.php
  src/ORM/Behavior/TreeBehavior.php
  src/ORM/Table.php
  src/TestSuite/Constraint/EventFiredWith.php
  src/TestSuite/IntegrationTestTrait.php
  src/View/Helper.php
  src/View/View.php
  tests/TestCase/Controller/Component/AuthComponentTest.php
  tests/TestCase/Controller/Component/RequestHandlerComponentTest.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Error/ExceptionRendererTest.php
  tests/TestCase/Event/Decorator/ConditionDecoratorTest.php
  tests/TestCase/Event/Decorator/SubjectFilterDecoratorTest.php
  tests/TestCase/Event/EventManagerTest.php
  tests/TestCase/Http/ActionDispatcherTest.php
  tests/TestCase/Http/ServerTest.php
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/ORM/Behavior/CounterCacheBehaviorTest.php
  tests/TestCase/ORM/MarshallerTest.php
  tests/TestCase/ORM/QueryRegressionTest.php
  tests/TestCase/ORM/QueryTest.php
  tests/TestCase/ORM/RulesCheckerIntegrationTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/View/ViewTest.php
  tests/test_app/Plugin/TestPlugin/src/Routing/Filter/Test2DispatcherFilter.php
  tests/test_app/Plugin/TestPlugin/src/Routing/Filter/TestDispatcherFilter.php
  tests/test_app/TestApp/Auth/TestAuthenticate.php
  tests/test_app/TestApp/Controller/Component/AppleComponent.php
  tests/test_app/TestApp/Controller/Component/OrangeComponent.php
  tests/test_app/TestApp/Controller/Component/TestAuthComponent.php
  tests/test_app/TestApp/Controller/PostsController.php
  tests/test_app/TestApp/Model/Behavior/SluggableBehavior.php
  tests/test_app/TestApp/Routing/Filter/AppendFilter.php
  tests/test_app/TestApp/View/Helper/EventListenerTestHelper.php
Labels: Enhancement

#12178 Use getter/setter instead of deprecated properties.
  src/View/Helper.php
  src/View/Helper/HtmlHelper.php
  src/View/HelperRegistry.php
  tests/TestCase/View/Helper/FlashHelperTest.php
  tests/TestCase/View/JsonViewTest.php
  tests/TestCase/View/ViewBuilderTest.php
  tests/TestCase/View/XmlViewTest.php
Labels: deprecations, view

#12182 4.x remove deprecation warnings
  src/Controller/Controller.php
  src/Filesystem/Folder.php
  src/Http/Session.php
  tests/TestCase/BasicsTest.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Core/InstanceConfigTraitTest.php
  tests/TestCase/Core/StaticConfigTraitTest.php
  tests/TestCase/Event/EventManagerTest.php
  tests/TestCase/Filesystem/FolderTest.php
  tests/TestCase/Http/ServerRequestTest.php
  tests/TestCase/Http/SessionTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/ViewBuilderTest.php
Labels: deprecations

#12183 Improve error message for missing shells
  src/Console/Exception/MissingShellException.php
Labels: console

#12185 Catching StopException in ConsoleIntegrationTestCase
  src/TestSuite/ConsoleIntegrationTestCase.php
  tests/TestCase/Shell/CommandListShellTest.php
  tests/TestCase/Shell/CompletionShellTest.php
  tests/TestCase/TestSuite/ConsoleIntegrationTestCaseTest.php
  tests/test_app/TestApp/Application.php
  tests/test_app/TestApp/Command/AbortCommand.php
  tests/test_app/TestApp/Shell/IntegrationShell.php
Labels: Defect

#12189 Change name and phpdoc of Email::deliver() $config argument
  src/Mailer/Email.php
Labels: documentation

#12190 add missing deprecation into Event::data()
  src/Event/Event.php
  tests/TestCase/Event/Decorator/ConditionDecoratorTest.php
  tests/test_app/TestApp/Auth/TestAuthenticate.php
Labels: events

#11837 [RFC] HTML5 validation error messages
  src/Validation/Validator.php
  src/View/Form/ArrayContext.php
  src/View/Form/ContextInterface.php
  src/View/Form/EntityContext.php
  src/View/Form/FormContext.php
  src/View/Form/NullContext.php
  src/View/Helper/FormHelper.php
  tests/TestCase/ORM/RulesCheckerIntegrationTest.php
  tests/TestCase/Validation/ValidatorTest.php
  tests/TestCase/View/Form/ArrayContextTest.php
  tests/TestCase/View/Form/EntityContextTest.php
  tests/TestCase/View/Form/FormContextTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: RFC, validation

#12195 Fix docblock to what its interface contracts says.
  src/ORM/Table.php
Labels: documentation

#12196 The $order param allows both a string and array
  lib/Cake/Model/Model.php
Labels: documentation

#12192 Remove more deprecated features from 3.x
  src/Controller/Controller.php
  src/Core/Plugin.php
  src/View/Cell.php
  src/View/View.php
  tests/TestCase/Core/PluginTest.php
Labels: deprecations

#12179 3.7 view props
  src/Mailer/Email.php
  src/View/AjaxView.php
  src/View/HelperRegistry.php
  src/View/JsonView.php
  src/View/View.php
  src/View/XmlView.php
  tests/TestCase/Controller/Component/RequestHandlerComponentTest.php
  tests/TestCase/Error/DebuggerTest.php
  tests/TestCase/View/CellTest.php
  tests/TestCase/View/Helper/FlashHelperTest.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
  tests/TestCase/View/HelperRegistryTest.php
  tests/TestCase/View/JsonViewTest.php
  tests/TestCase/View/ViewBuilderTest.php
  tests/TestCase/View/ViewTest.php
Labels: deprecations

#12184 Fix URL arrays not working with IntegrationTestCase and RoutingMiddleware
  src/TestSuite/IntegrationTestCase.php
  src/TestSuite/LegacyRequestDispatcher.php
  src/TestSuite/MiddlewareDispatcher.php
  tests/TestCase/TestSuite/IntegrationTestCaseTest.php
Labels: routing, testing

#12200 Move start/end calculation into datasource.
  src/Datasource/Paginator.php
  src/View/Helper/PaginatorHelper.php
  tests/TestCase/Datasource/PaginatorTest.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
Labels: Enhancement

#12173 4.x - Shell deprecations
  src/Console/Shell.php
  src/Console/ShellDispatcher.php
  src/Shell/CommandListShell.php
  src/Shell/OrmCacheShell.php
  tests/TestCase/Command/HelpCommandTest.php
  tests/TestCase/Console/CommandCollectionTest.php
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Console/ShellDispatcherTest.php
  tests/TestCase/Shell/CommandListShellTest.php
  tests/TestCase/Shell/CompletionShellTest.php
  tests/TestCase/TestSuite/ConsoleIntegrationTestTraitTest.php
Labels: deprecations

#12162 Fix # 11827: Replace use of each() in DboSource::order for PHP 7.2 compatibility
  lib/Cake/Model/Datasource/DboSource.php
Labels: Enhancement

#12197 3.6 - deprecationWarning - PaginatorHelper::generateUrl()
  src/View/Helper/PaginatorHelper.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
Labels: deprecations, helpers, view

#12164 Fix #12163
  src/ORM/Table.php
  tests/TestCase/ORM/TableTest.php
Labels: Defect

#12212 Improved property documentation
  lib/Cake/Model/Datasource/DboSource.php
Labels: documentation, models

#12217 Remove ORM annotations from Datasource package
  src/Datasource/QueryCacher.php
  src/Datasource/QueryTrait.php
  src/Datasource/RepositoryInterface.php
  src/ORM/Table.php
Labels: datasource

#12213 Casting all integration test data to string
  src/TestSuite/IntegrationTestCase.php
  tests/TestCase/TestSuite/IntegrationTestCaseTest.php
Labels: Defect, testing

#12201 3.7 cell deprecations
  src/View/Cell.php
  src/View/CellTrait.php
  tests/TestCase/View/CellTest.php
  tests/test_app/TestApp/View/Cell/ArticlesCell.php
Labels: deprecations, view

#12206 3.7 helper deprecations
  src/View/Helper.php
  src/View/Helper/FlashHelper.php
  src/View/Helper/FormHelper.php
  src/View/Helper/PaginatorHelper.php
  src/View/Helper/SessionHelper.php
  src/View/Helper/UrlHelper.php
  src/View/HelperRegistry.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/Helper/HtmlHelperTest.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
  tests/TestCase/View/Helper/UrlHelperTest.php
  tests/TestCase/View/HelperTest.php
Labels: deprecations

#12215 4.x Added getRequiredMessage to ContextInterface
  src/View/Form/ContextInterface.php
  src/View/Helper/FormHelper.php
Labels: deprecations

#12226 Deprecated View::uuid() as it's unused in core.
  src/View/View.php
  tests/TestCase/View/ViewTest.php
Labels: deprecations

#12229 3.next - Deprecate the read side of join() and from()
  src/Database/Query.php
  src/ORM/Association/BelongsToMany.php
  tests/TestCase/Database/QueryTest.php
Labels: ORM, deprecations

#12221 4.x remove deprecation code
  src/Core/Plugin.php
  src/View/Helper/PaginatorHelper.php
  tests/TestCase/Core/PluginTest.php
  tests/TestCase/Utility/Crypto/McryptTest.php
  tests/TestCase/Utility/SecurityTest.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
  tests/test_app/TestApp/Template/Scaffold/empty
Labels: deprecations

#12198 Deprecate the Response being able to create new Cookies
  src/Controller/Component/CookieComponent.php
  src/Controller/Component/CsrfComponent.php
  src/Http/Cookie/Cookie.php
  src/Http/Middleware/CsrfProtectionMiddleware.php
  src/Http/Response.php
  tests/TestCase/Controller/Component/CookieComponentTest.php
  tests/TestCase/Http/Cookie/CookieCollectionTest.php
  tests/TestCase/Http/Cookie/CookieTest.php
  tests/TestCase/Http/Middleware/EncryptedCookieMiddlewareTest.php
  tests/TestCase/Http/ResponseEmitterTest.php
  tests/TestCase/Http/ResponseTest.php
  tests/test_app/TestApp/Controller/PostsController.php
Labels: deprecations, http

#12236 Fix save many with exceptions
  src/ORM/Table.php
  tests/TestCase/ORM/TableTest.php
Labels: Defect, ORM

#12222 Fix EntityTrait examples and route parsing with brace style routes.
  src/Datasource/EntityTrait.php
  src/Routing/Route/Route.php
  tests/TestCase/Routing/Route/RouteTest.php
Labels: documentation, routing

#12247 4.x - Collection typing
  src/Collection/Collection.php
  src/Collection/CollectionInterface.php
  src/Collection/CollectionTrait.php
  src/Collection/ExtractTrait.php
  src/Collection/Iterator/BufferedIterator.php
  src/Collection/Iterator/ExtractIterator.php
  src/Collection/Iterator/FilterIterator.php
  src/Collection/Iterator/InsertIterator.php
  src/Collection/Iterator/MapReduce.php
  src/Collection/Iterator/NestIterator.php
  src/Collection/Iterator/NoChildrenIterator.php
  src/Collection/Iterator/ReplaceIterator.php
  src/Collection/Iterator/SortIterator.php
  src/Collection/Iterator/StoppableIterator.php
  src/Collection/Iterator/TreeIterator.php
  src/Collection/Iterator/TreePrinter.php
  src/Collection/Iterator/UnfoldIterator.php
  src/Collection/Iterator/ZipIterator.php
  src/Collection/functions.php
  src/Datasource/ResultSetDecorator.php
  src/ORM/ResultSet.php
  tests/TestCase/Collection/CollectionTest.php
  tests/TestCase/Collection/Iterator/BufferedIteratorTest.php
  tests/TestCase/Collection/Iterator/ExtractIteratorTest.php
  tests/TestCase/Collection/Iterator/FilterIteratorTest.php
  tests/TestCase/Collection/Iterator/InsertIteratorTest.php
  tests/TestCase/Collection/Iterator/MapReduceTest.php
  tests/TestCase/Collection/Iterator/ReplaceIteratorTest.php
  tests/TestCase/Collection/Iterator/SortIteratorTest.php
  tests/TestCase/Collection/Iterator/TreeIteratorTest.php
  tests/TestCase/ORM/QueryTest.php
Labels: collection

#12170 Create method for import html
  src/Utility/Xml.php
  tests/Fixture/sample.html
  tests/TestCase/Utility/XmlTest.php
Labels: Enhancement, utility

#12209 3.7 - Add curl based Http\Client Adapter.
  composer.json
  src/Http/Client.php
  src/Http/Client/Adapter/Curl.php
  src/Http/Client/Adapter/Stream.php
  src/Http/Client/AdapterInterface.php
  tests/TestCase/Http/Client/Adapter/CurlTest.php
  tests/TestCase/Http/ClientTest.php
Labels: Enhancement, http

#12256 Fix duplicate route errors when using loadPlugin()
  src/Routing/RouteBuilder.php
  tests/TestCase/Routing/RouteBuilderTest.php
  tests/TestCase/TestSuite/IntegrationTestCaseTest.php
  tests/test_app/Plugin/TestPlugin/config/routes.php
  tests/test_app/TestApp/ApplicationWithPluginRoutes.php
Labels: plugins, routing

#12263 Convert command objects to class name strings for HelpCommand output.
  src/Command/HelpCommand.php
  tests/TestCase/Command/HelpCommandTest.php
  tests/test_app/TestApp/Application.php
Labels: Defect

#12261 Use setDirty(field) as true by default as the name suggest.
  src/Datasource/EntityTrait.php
  tests/TestCase/ORM/EntityTest.php
Labels: Enhancement

#12270 Fix `BreadcrumbsHelper` property annotation.
  src/View/View.php
Labels: documentation

#12268 Fix nested validator error messages
  src/Datasource/EntityTrait.php
  tests/TestCase/ORM/EntityTest.php
Labels: ORM

#12248 4.x - Add typehints to console classes.
  src/Command/HelpCommand.php
  src/Command/VersionCommand.php
  src/Console/Arguments.php
  src/Console/Command.php
  src/Console/CommandCollection.php
  src/Console/CommandCollectionAwareInterface.php
  src/Console/CommandFactory.php
  src/Console/CommandFactoryInterface.php
  src/Console/CommandRunner.php
  src/Console/CommandScanner.php
  src/Console/ConsoleErrorHandler.php
  src/Console/ConsoleInput.php
  src/Console/ConsoleInputArgument.php
  src/Console/ConsoleInputOption.php
  src/Console/ConsoleInputSubcommand.php
  src/Console/ConsoleIo.php
  src/Console/ConsoleOptionParser.php
  src/Console/ConsoleOutput.php
  src/Console/Exception/ConsoleException.php
  src/Console/Exception/MissingHelperException.php
  src/Console/Exception/MissingShellException.php
  src/Console/Exception/MissingShellMethodException.php
  src/Console/Exception/MissingTaskException.php
  src/Console/Exception/StopException.php
  src/Console/HelpFormatter.php
  src/Console/Helper.php
  src/Console/HelperRegistry.php
  src/Console/Shell.php
  src/Console/ShellDispatcher.php
  src/Console/TaskRegistry.php
  src/TestSuite/Stub/ConsoleOutput.php
  tests/TestCase/Console/ArgumentsTest.php
  tests/TestCase/Console/CommandCollectionTest.php
  tests/TestCase/Console/CommandFactoryTest.php
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Console/CommandTest.php
  tests/TestCase/Console/ConsoleErrorHandlerTest.php
  tests/TestCase/Console/ConsoleIoTest.php
  tests/TestCase/Console/ConsoleOptionParserTest.php
  tests/TestCase/Console/ConsoleOutputTest.php
  tests/TestCase/Console/HelpFormatterTest.php
  tests/TestCase/Console/HelperRegistryTest.php
  tests/TestCase/Console/ShellDispatcherTest.php
  tests/TestCase/Console/ShellTest.php
  tests/TestCase/Console/TaskRegistryTest.php
  tests/test_app/TestApp/Shell/ShellTestShell.php
  tests/test_app/TestApp/Shell/TestingDispatchShell.php
Labels: console

#12276 Show deprecated warning only if session handler found in Network/Session namespace
  src/Http/Session.php
  tests/TestCase/Http/SessionTest.php
Labels: deprecations, network

#12274 Remove recent deprecations from 3.x
  src/Database/Query.php
  src/Routing/RouteBuilder.php
  tests/TestCase/Database/QueryTest.php
  tests/TestCase/Routing/RouteBuilderTest.php
Labels: deprecations

#12279 Replace deprecated 'fieldList' with 'fields' in phpdoc
  src/ORM/Table.php
Labels: documentation

#12273 Use Plugin::load() when creating classless plugins.
  src/Core/Plugin.php
  src/Core/PluginCollection.php
  src/Http/BaseApplication.php
  tests/TestCase/Core/PluginCollectionTest.php
  tests/TestCase/Http/BaseApplicationTest.php
Labels: plugins

#12283 4.x Event strict typing.
  appveyor.yml
  src/Console/CommandRunner.php
  src/Controller/Component.php
  src/Controller/Component/AuthComponent.php
  src/Controller/Component/PaginatorComponent.php
  src/Controller/Component/RequestHandlerComponent.php
  src/Controller/Component/SecurityComponent.php
  src/Controller/Controller.php
  src/Event/Decorator/AbstractDecorator.php
  src/Event/Decorator/ConditionDecorator.php
  src/Event/Decorator/SubjectFilterDecorator.php
  src/Event/Event.php
  src/Event/EventDispatcherInterface.php
  src/Event/EventDispatcherTrait.php
  src/Event/EventInterface.php
  src/Event/EventList.php
  src/Event/EventListenerInterface.php
  src/Event/EventManager.php
  src/Event/EventManagerInterface.php
  src/Form/Form.php
  src/Http/ActionDispatcher.php
  src/Http/Server.php
  src/Mailer/Mailer.php
  src/ORM/Behavior.php
  src/ORM/Behavior/TimestampBehavior.php
  src/ORM/Table.php
  src/View/Cell.php
  src/View/Helper.php
  src/View/Helper/FlashHelper.php
  src/View/Helper/FormHelper.php
  src/View/Helper/HtmlHelper.php
  src/View/Helper/NumberHelper.php
  src/View/Helper/PaginatorHelper.php
  src/View/Helper/TextHelper.php
  src/View/Helper/TimeHelper.php
  src/View/Helper/UrlHelper.php
  tests/TestCase/Event/Decorator/ConditionDecoratorTest.php
  tests/TestCase/Event/Decorator/SubjectFilterDecoratorTest.php
  tests/TestCase/Event/EventDispatcherTraitTest.php
  tests/TestCase/Event/EventListTest.php
  tests/TestCase/Event/EventManagerTest.php
  tests/TestCase/Event/EventTest.php
  tests/TestCase/ORM/BehaviorTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/View/ViewTest.php
  tests/test_app/TestApp/View/Helper/EventListenerTestHelper.php
Labels: events

#12289 Make config deprecation error message more helpful
  src/Core/Configure/Engine/PhpConfig.php
Labels: Enhancement, deprecations

#12287 Adjust App::className() to be clean nullable return.
  src/Auth/PasswordHasherFactory.php
  src/Cache/CacheRegistry.php
  src/Console/HelperRegistry.php
  src/Console/Shell.php
  src/Console/TaskRegistry.php
  src/Controller/Component/AuthComponent.php
  src/Controller/ComponentRegistry.php
  src/Core/App.php
  src/Core/ObjectRegistry.php
  src/Database/Connection.php
  src/Datasource/ConnectionRegistry.php
  src/Http/ControllerFactory.php
  src/Http/MiddlewareQueue.php
  src/Log/LogEngineRegistry.php
  src/Mailer/MailerAwareTrait.php
  src/ORM/BehaviorRegistry.php
  src/ORM/Locator/TableLocator.php
  src/Routing/RouteBuilder.php
  src/View/Helper/NumberHelper.php
  src/View/HelperRegistry.php
  src/View/Widget/WidgetLocator.php
  tests/TestCase/Core/AppTest.php
  tests/TestCase/I18n/TimeTest.php
Labels: Enhancement

#12292 Ignore invalid expires attributes in cookies.
  src/Http/Cookie/CookieCollection.php
  tests/TestCase/Http/Cookie/CookieCollectionTest.php
Labels: http

#12296 Fixed issue #12295 - https://github.com/cakephp/cakephp/issues/12295
  src/Routing/Route/RedirectRoute.php
Labels: Need Tests, routing

#12305 MultiCheckboxWidget should use checkboxWrapper, not radioWrapper.
  src/View/Widget/MultiCheckboxWidget.php
  tests/TestCase/View/Widget/MultiCheckboxWidgetTest.php
Labels: Defect
