Repository cakephp/cakephp, pull requests merged in 2018-02, with the labels that each got.

#11706 Add withAddedLink()
  src/Http/Response.php
  tests/TestCase/Http/ResponseTest.php
Labels: Enhancement, http

#11711 Fix incorrect annotations.
  phpstan.neon
  src/Database/Driver.php
  src/Datasource/ConnectionInterface.php
Labels: documentation

#11722 Initialize $prefix to suppress Notice Error
  src/Template/Error/missing_action.ctp
Labels: exception

#11691 feat: allow modifying the Form schema class
  src/Form/Form.php
  tests/TestCase/Form/FormTest.php
  tests/test_app/TestApp/Form/AppForm.php
  tests/test_app/TestApp/Form/FormSchema.php
Labels: Enhancement

#11725 Use relative path to allow using phpstan.phar locally.
  phpstan.neon
Labels: Enhancement

#11727 Do not allow updates to tables with no primary key
  src/ORM/Table.php
  tests/TestCase/ORM/TableRegressionTest.php
Labels: ORM

#11692 [RFC] Add application event hook.
  src/Console/CommandRunner.php
  src/Event/EventApplicationInterface.php
  src/Event/EventManager.php
  src/Event/EventManagerInterface.php
  src/Http/BaseApplication.php
  src/Http/Server.php
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Http/ServerTest.php
  tests/test_app/TestApp/Http/EventApplication.php
Labels: Enhancement, RFC, events

#11736 Make view block inst. a bit less internally coupled.
  src/Event/EventDispatcherTrait.php
  src/View/View.php
  tests/TestCase/Error/DebuggerTest.php
Labels: Enhancement

#11734 Add virtual fields into __debugInfo() output.
  src/Datasource/EntityTrait.php
  tests/TestCase/ORM/EntityTest.php
Labels: Enhancement

#10933 Deprecate TableRegistry static API.
  phpstan.neon
  src/Auth/BaseAuthenticate.php
  src/Console/Shell.php
  src/Http/Session/DatabaseSession.php
  src/ORM/README.md
  src/ORM/Table.php
  src/ORM/TableRegistry.php
  src/Template/Element/auto_table_warning.ctp
  src/TestSuite/Fixture/TestFixture.php
  src/TestSuite/TestCase.php
  src/View/Form/EntityContext.php
  tests/Fixture/FixturizedTestCase.php
  tests/TestCase/Auth/BasicAuthenticateTest.php
  tests/TestCase/Auth/DigestAuthenticateTest.php
  tests/TestCase/Auth/FormAuthenticateTest.php
  tests/TestCase/Console/ShellDispatcherTest.php
  tests/TestCase/Console/ShellTest.php
  tests/TestCase/Controller/Component/AuthComponentTest.php
  tests/TestCase/Controller/Component/PaginatorComponentTest.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Database/Schema/MysqlSchemaTest.php
  tests/TestCase/Database/Schema/PostgresSchemaTest.php
  tests/TestCase/Database/Schema/SqliteSchemaTest.php
  tests/TestCase/Database/Schema/SqlserverSchemaTest.php
  tests/TestCase/Database/Schema/TableSchemaTest.php
  tests/TestCase/Datasource/PaginatorTest.php
  tests/TestCase/Http/Session/DatabaseSessionTest.php
  tests/TestCase/Mailer/EmailTest.php
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/ORM/Association/BelongsToTest.php
  tests/TestCase/ORM/Association/HasManyTest.php
  tests/TestCase/ORM/Association/HasOneTest.php
  tests/TestCase/ORM/AssociationCollectionTest.php
  tests/TestCase/ORM/AssociationProxyTest.php
  tests/TestCase/ORM/AssociationTest.php
  tests/TestCase/ORM/Behavior/BehaviorRegressionTest.php
  tests/TestCase/ORM/Behavior/CounterCacheBehaviorTest.php
  tests/TestCase/ORM/Behavior/TimestampBehaviorTest.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
  tests/TestCase/ORM/Behavior/TreeBehaviorTest.php
  tests/TestCase/ORM/BindingKeyTest.php
  tests/TestCase/ORM/CompositeKeysTest.php
  tests/TestCase/ORM/EagerLoaderTest.php
  tests/TestCase/ORM/Locator/LocatorAwareTraitTest.php
  tests/TestCase/ORM/MarshallerTest.php
  tests/TestCase/ORM/QueryRegressionTest.php
  tests/TestCase/ORM/QueryTest.php
  tests/TestCase/ORM/ResultSetTest.php
  tests/TestCase/ORM/RulesCheckerIntegrationTest.php
  tests/TestCase/ORM/TableRegistryTest.php
  tests/TestCase/ORM/TableRegressionTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/ORM/TableUuidTest.php
  tests/TestCase/TestSuite/FixtureManagerTest.php
  tests/TestCase/TestSuite/TestCaseTest.php
  tests/TestCase/TestSuite/TestFixtureTest.php
  tests/TestCase/View/Form/EntityContextTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: ORM, deprecations

#11741 Fix Paginator unnecessarily modifying "sort" option.
  src/Datasource/Paginator.php
  tests/TestCase/Controller/Component/PaginatorComponentTest.php
  tests/TestCase/Datasource/PaginatorTest.php
Labels: Defect, pagination

#11737 3.6: Always use consistent class usage and inclusion.
  src/Database/Type.php
  src/ORM/Association/BelongsToMany.php
  src/ORM/Locator/LocatorInterface.php
  src/ORM/Table.php
  src/Template/Error/missing_action.ctp
  src/Template/Error/missing_controller.ctp
  src/TestSuite/TestCase.php
  src/Validation/RulesProvider.php
  src/Validation/ValidatorAwareTrait.php
  tests/TestCase/Event/EventDispatcherTraitTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/TestSuite/TestCaseTest.php
Labels: Enhancement

#11746 Changed docblock
  src/Database/Expression/QueryExpression.php
Labels: documentation

#11748 Change to class constant
  src/Datasource/QueryTrait.php
Labels: Enhancement

#11704 Rename WidgetRegistry to WidgetLocator
  src/View/Helper/FormHelper.php
  src/View/Widget/WidgetLocator.php
  src/View/Widget/WidgetRegistry.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/Widget/WidgetLocatorTest.php
Labels: Enhancement

#11643 [2.x] Make mcrypt optional
  composer.json
  lib/Cake/Test/Case/Utility/SecurityTest.php
  lib/Cake/Utility/Security.php
Labels: Enhancement

#11758 Fix Session handling in IntegrationTestCase usage.
  src/Network/Session.php
Labels: Defect

#11757 Ensure paging params are properly set based on "order" in settings.
  src/Datasource/Paginator.php
  tests/TestCase/Controller/Component/PaginatorComponentTest.php
  tests/TestCase/Datasource/PaginatorTest.php
Labels: Defect

#11752 Add consumeOrFail().
  src/Core/Configure.php
  tests/TestCase/Core/ConfigureTest.php
Labels: Enhancement

#11764 Improving exception msgs for database types
  src/Database/Type/BoolType.php
  src/Database/Type/DecimalType.php
  src/Database/Type/IntegerType.php
  src/Database/Type/StringType.php
Labels: Enhancement

#11770 Use variadic isset
  src/ORM/EagerLoader.php
  src/Validation/Validation.php
Labels: Enhancement
