Repository cakephp/cakephp, pull requests merged in 2018-08, with the labels that each got.

#12415 Fix regression in session handling
  src/Http/Session.php
Labels: Defect

#12419 4.0 - clean up deprecations and add strict_types (http\response)
  src/Http/Response.php
  tests/TestCase/Http/BaseApplicationTest.php
Labels: deprecations

#12421 Remove unneeded View::$hasRendered flag.
  src/View/View.php
  tests/TestCase/Error/DebuggerTest.php
  tests/TestCase/View/ViewTest.php
Labels: Enhancement

#12429 4.x - Add type hints to database package
  src/Database/Connection.php
  src/Database/Dialect/MysqlDialectTrait.php
  src/Database/Dialect/PostgresDialectTrait.php
  src/Database/Dialect/SqliteDialectTrait.php
  src/Database/Dialect/SqlserverDialectTrait.php
  src/Database/Driver.php
  src/Database/DriverInterface.php
  src/Database/Exception.php
  src/Database/Exception/NestedTransactionRollbackException.php
  src/Database/Expression/BetweenExpression.php
  src/Database/Expression/CaseExpression.php
  src/Database/Expression/Comparison.php
  src/Database/Expression/OrderClauseExpression.php
  src/Database/Expression/UnaryExpression.php
  src/Database/ExpressionInterface.php
  src/Database/FieldTypeConverter.php
  src/Database/FunctionsBuilder.php
  src/Database/IdentifierQuoter.php
  src/Database/Log/LoggedQuery.php
  src/Database/Log/LoggingStatement.php
  src/Database/Log/QueryLogger.php
  src/Database/Query.php
  src/Database/QueryCompiler.php
  src/Database/Retry/ReconnectStrategy.php
  src/Database/SchemaCache.php
  src/Database/SqlDialectTrait.php
  src/Database/SqliteCompiler.php
  src/Database/SqlserverCompiler.php
  src/Database/Statement/StatementDecorator.php
  src/Database/StatementInterface.php
  src/Database/Type.php
  src/Database/Type/BaseType.php
  src/Database/Type/DateTimeType.php
  src/Database/TypeConverterTrait.php
  src/Database/TypeFactory.php
  src/Database/TypeInterface.php
  src/Database/TypeMap.php
  src/Database/TypeMapTrait.php
  src/Database/TypedResultInterface.php
  src/Database/TypedResultTrait.php
  src/Database/ValueBinder.php
  src/Datasource/ConnectionInterface.php
  src/Datasource/QueryInterface.php
  src/ORM/Query.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Database/Driver/SqlserverTest.php
  tests/TestCase/Database/DriverTest.php
  tests/TestCase/Database/ExpressionTypeCastingIntegrationTest.php
  tests/TestCase/Database/ExpressionTypeCastingTest.php
  tests/TestCase/Database/FunctionsBuilderTest.php
  tests/TestCase/Database/QueryTest.php
  tests/TestCase/Database/Schema/TableSchemaTest.php
  tests/TestCase/Database/SchemaCacheTest.php
  tests/TestCase/Database/TypeFactoryTest.php
  tests/TestCase/Database/ValueBinderTest.php
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/TestSuite/TestFixtureTest.php
  tests/test_app/TestApp/Database/Type/BarType.php
  tests/test_app/TestApp/Database/Type/FooType.php
Labels: database

#12433 Avoid undefined index: null (update action)
  lib/Cake/Model/Datasource/DboSource.php
Labels: Defect

#12443 3.7 remove hasRendered methods from view
  src/Mailer/Email.php
  src/View/View.php
  tests/TestCase/Error/DebuggerTest.php
  tests/TestCase/View/ViewTest.php
Labels: view

#12454 Quote column identifier for column names containing utf-8 chars (ä)
  src/Database/SqlDialectTrait.php
  tests/TestCase/Database/ConnectionTest.php
Labels: Enhancement, database

#12462 Deprecate ViewVarsTrait::viewOptions() and related property.
  src/Controller/Controller.php
  src/View/Cell.php
  src/View/ViewVarsTrait.php
  tests/TestCase/View/ViewVarsTraitTest.php
Labels: deprecations

#12464 Add assertRedirectNotContains & assertHeaderNotContains
  src/TestSuite/Constraint/Response/HeaderNotContains.php
  src/TestSuite/IntegrationTestTrait.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
Labels: Enhancement, testing

#12480 Add an option on extractTask to avoid the display of marker errors
  src/Shell/Task/ExtractTask.php
  tests/TestCase/Shell/Task/ExtractTaskTest.php
  tests/test_app/TestApp/Template/Pages/extract.ctp
Labels: Enhancement

#12468 3.next email transport
  src/Mailer/Email.php
  src/Mailer/TransportFactory.php
  src/Mailer/TransportRegistry.php
  src/TestSuite/TestEmailTransport.php
  tests/TestCase/Mailer/EmailTest.php
  tests/TestCase/TestSuite/EmailAssertTraitTest.php
  tests/TestCase/TestSuite/EmailTraitTest.php
  tests/TestCase/TestSuite/TestEmailTransportTest.php
Labels: Enhancement

#12504 Improved the ORM Readme
  src/ORM/README.md
Labels: ORM, documentation

#12460 3.next email viewbuilder methods
  src/Mailer/Email.php
  src/Mailer/Mailer.php
  tests/TestCase/Mailer/EmailTest.php
  tests/TestCase/Mailer/MailerTest.php
Labels: mailer
