Repository cakephp/cakephp, pull requests merged in 2019-03, with the labels that each got.

#13026 Offload phpcs and static analysis checks to Scrutinizer
  .scrutinizer.yml
  .travis.yml
Labels: testing

#13031 Fix Comparison expression cloning.
  src/Database/Expression/Comparison.php
Labels: Defect

#13017 Add Message class for email.
  src/Mailer/AbstractTransport.php
  src/Mailer/Email.php
  src/Mailer/Mailer.php
  src/Mailer/Message.php
  src/Mailer/Renderer.php
  src/Mailer/Transport/DebugTransport.php
  src/Mailer/Transport/MailTransport.php
  src/Mailer/Transport/SmtpTransport.php
  src/TestSuite/Constraint/Email/MailConstraintBase.php
  src/TestSuite/Constraint/Email/MailContains.php
  src/TestSuite/Constraint/Email/MailCount.php
  src/TestSuite/Constraint/Email/MailSentWith.php
  src/TestSuite/Constraint/Email/NoMailSent.php
  src/TestSuite/EmailTrait.php
  src/TestSuite/TestEmailTransport.php
  tests/TestCase/Mailer/EmailTest.php
  tests/TestCase/Mailer/MessageTest.php
  tests/TestCase/Mailer/Transport/DebugTransportTest.php
  tests/TestCase/Mailer/Transport/MailTransportTest.php
  tests/TestCase/Mailer/Transport/SmtpTransportTest.php
  tests/TestCase/TestSuite/TestEmailTransportTest.php
  tests/test_app/TestApp/Mailer/Email/TestEmail.php
  tests/test_app/TestApp/Mailer/TestEmail.php
  tests/test_app/TestApp/Mailer/TestMessage.php
  tests/test_app/TestApp/Renderer/TestRenderer.php
  tests/test_app/templates/email/html/html.php
Labels: Enhancement

#13033 Fix session data not saved on fastcgi servers on slower session backends
  src/Http/ResponseEmitter.php
Labels: Defect

#13028 Try to avoid installing PHP each time on appveyor.
  appveyor.yml
  tests/TestCase/Console/ConsoleInputTest.php
  tests/TestCase/Database/Driver/SqlserverTest.php
Labels: testing

#13047 Speed up ExtractTask by skipping files without translation functions
  src/Shell/Task/ExtractTask.php
Labels: Enhancement

#13050 Fix up extract() doc.
  src/Shell/Task/ExtractTask.php
  src/Utility/Text.php
  tests/TestCase/Filesystem/FolderTest.php
Labels: documentation

#13052 Improve generated .pot references compatibility with PO editors
  src/Shell/Task/ExtractTask.php
  tests/TestCase/Shell/Task/ExtractTaskTest.php
Labels: Enhancement, i18n

#13044 Allow custom label attributes array for each radio button
  src/View/Widget/RadioWidget.php
Labels: Enhancement

#12990 3.next - Add notEmpty* validator methods
  src/Validation/Validator.php
  tests/TestCase/Validation/ValidatorTest.php
Labels: Enhancement, validation

#13055 4.x static analysis
  phpstan.neon
  psalm.xml
  src/Auth/DefaultPasswordHasher.php
  src/Cache/Engine/MemcachedEngine.php
  src/Core/Configure.php
  src/Core/ObjectRegistry.php
  src/Database/Expression/Comparison.php
  src/Database/Statement/StatementDecorator.php
  src/Http/Client/Auth/Oauth.php
  src/Mailer/Email.php
  src/Routing/Route/Route.php
  src/View/JsonView.php
  src/View/SerializedView.php
  src/View/View.php
  tests/TestCase/View/JsonViewTest.php
Labels: documentation

#13061 Improve number formatter pattern example in doc blocks
  src/I18n/Number.php
  src/View/Helper/NumberHelper.php
  tests/TestCase/I18n/NumberTest.php
Labels: Enhancement, documentation

#13066 Add test case for patching.
  tests/TestCase/ORM/TableTest.php
Labels: testing

#13064 Fix PHPDoc of Table::findOrCreate() and reuse unused Table::_getFindOrCreateQuery()
  src/ORM/Table.php
Labels: ORM

#13074 Allow setting multiple headers of the same name.
  src/Mailer/AbstractTransport.php
  src/Mailer/Email.php
  tests/TestCase/Mailer/EmailTest.php
  tests/TestCase/Mailer/Transport/DebugTransportTest.php
Labels: Enhancement

#13058 Add extra unit tests
  .travis.yml
  composer.json
  lib/Cake/Test/Case/AllControllerTest.php
  lib/Cake/Test/Case/Controller/ApplicationControllerTest.php
Labels: testing

#13054 FormHelper does not respect passed 'escape' option for errors
  lib/Cake/Test/Case/View/Helper/FormHelperTest.php
Labels: Defect
