Repository cakephp/cakephp, pull requests merged in 2019-08, with the labels that each got.

#13453 Set default value for argument.
  src/Datasource/EntityInterface.php
Labels: cleanup

#13455 Split combined getter/setter EntityInterface::isNew().
  src/Datasource/EntityInterface.php
  src/Datasource/EntityTrait.php
  src/ORM/Association/BelongsToMany.php
  src/ORM/Behavior/Translate/EavStrategy.php
  src/ORM/Entity.php
  src/ORM/Table.php
  tests/TestCase/ORM/Behavior/TimestampBehaviorTest.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/ORM/MarshallerTest.php
  tests/TestCase/ORM/ResultSetTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/View/Form/EntityContextTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: deprecations, enhancement

#13472 Allow specifying custom cache key prefix for Schema\CachedCollection.
  src/Database/Connection.php
  tests/TestCase/Database/ConnectionTest.php
Labels: enhancement

#13475 Use less inflection on aliasing.
  src/ORM/Locator/TableLocator.php
Labels: enhancement

#13485 Add more concrete array doc.
  src/Database/Expression/TupleComparison.php
  src/Datasource/EntityInterface.php
  src/Datasource/EntityTrait.php
  src/ORM/Rule/IsUnique.php
  src/ORM/RulesChecker.php
  src/View/Helper/SecureFieldTokenTrait.php
Labels: cleanup, documentation

#13484 Use less inflection on aliasing. Add tests.
  src/ORM/Locator/TableLocator.php
  tests/TestCase/ORM/Locator/TableLocatorTest.php
Labels: testing

#13487 Add default value for enable* methods.
  src/Database/Connection.php
  src/Datasource/ConnectionInterface.php
Labels: enhancement

#13491 Fix return type handling
  src/View/Helper/FormHelper.php
Labels: cleanup

#13490 Fix array typehints to be more precise, string array check strictness
  src/Auth/BaseAuthenticate.php
  src/Cache/Engine/FileEngine.php
  src/Controller/Component/AuthComponent.php
  src/Database/Driver/Mysql.php
  src/Database/Driver/Postgres.php
  src/Database/Driver/Sqlite.php
  src/Database/Driver/Sqlserver.php
  src/Http/Middleware/BodyParserMiddleware.php
  src/Http/Middleware/CsrfProtectionMiddleware.php
  src/Http/Middleware/SecurityHeadersMiddleware.php
  src/Http/Response.php
  src/ORM/Association/HasMany.php
  src/ORM/Association/Loader/SelectLoader.php
  src/ORM/Behavior.php
  src/ORM/Marshaller.php
  src/TestSuite/EmailAssertTrait.php
  src/TestSuite/Fixture/FixtureInjector.php
  src/Utility/Inflector.php
  src/Utility/Text.php
  src/View/Helper/FormHelper.php
  src/View/View.php
Labels: enhancement

#13494 Backport saveManyOrFail(), deleteMany(), deleteManyOrFail()
  src/ORM/Table.php
  tests/TestCase/ORM/TableTest.php
Labels: enhancement

#13486 3.x: Backport of "Make metadata cache key configurable"
  src/Database/Connection.php
  src/Database/Schema/CachedCollection.php
  tests/TestCase/Database/ConnectionTest.php
Labels: enhancement

#13500 Remove unused vars and assigments.
  psalm-baseline.xml
  psalm.xml
  src/Cache/CacheRegistry.php
  src/Command/HelpCommand.php
  src/Datasource/ModelAwareTrait.php
  src/Error/ExceptionRenderer.php
  src/Http/Client/Auth/Oauth.php
  src/I18n/DateFormatTrait.php
  src/Log/Engine/FileLog.php
  src/Mailer/TransportRegistry.php
  src/ORM/Association/Loader/SelectLoader.php
  src/ORM/Marshaller.php
  src/Routing/Router.php
  src/TestSuite/IntegrationTestTrait.php
  src/Validation/Validator.php
  src/View/Form/EntityContext.php
  src/View/View.php
Labels: cleanup

#13497 Backport: Split combined getter/setter EntityInterface::isNew().
  src/Datasource/EntityInterface.php
  src/Datasource/EntityTrait.php
  src/ORM/Association/BelongsToMany.php
  src/ORM/Entity.php
  src/ORM/Table.php
  tests/TestCase/ORM/Behavior/TimestampBehaviorTest.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/ORM/MarshallerTest.php
  tests/TestCase/ORM/ResultSetTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/View/Form/EntityContextTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: datasource

#13214 4.x: IS NULL exception fix
  src/Database/Expression/QueryExpression.php
  src/ORM/Association/BelongsToMany.php
  src/ORM/Behavior/Translate/EavStrategy.php
  src/ORM/Rule/ExistsIn.php
  src/ORM/Rule/IsUnique.php
  src/ORM/RulesChecker.php
  tests/TestCase/Database/QueryTest.php
  tests/TestCase/ORM/RulesCheckerIntegrationTest.php
  tests/test_app/TestApp/Model/Behavior/SluggableBehavior.php
Labels: ORM

#13478 Allow HtmlHelper::tableHeaders to accept cell attributes in HtmlHelper::tableCells format
  src/View/Helper/HtmlHelper.php
  tests/TestCase/View/Helper/HtmlHelperTest.php
Labels: enhancement

#13512 Fix typo
  src/Database/Type/BinaryType.php
  src/Database/Type/BinaryUuidType.php
  src/Database/Type/BoolType.php
  src/Database/Type/DecimalType.php
  src/Database/Type/FloatType.php
  src/Database/Type/IntegerType.php
  src/Database/Type/JsonType.php
  src/Database/Type/StringType.php
  src/Database/TypeInterface.php
  tests/TestCase/Database/Type/DecimalTypeTest.php
Labels: documentation

#13514 Remove invalid throws. Restore typehint for IDE.
  src/Database/Type/DecimalType.php
Labels: documentation

#13511 Fix return type for TestEmailTransport::send().
  src/TestSuite/TestEmailTransport.php
Labels: defect

#13513 Document param types.
  src/Database/Type/BatchCastingInterface.php
  src/Database/Type/DecimalType.php
  src/Database/Type/FloatType.php
  src/Database/Type/IntegerType.php
Labels: documentation

#13502 Use data attribute to hold confirm message.
  src/View/Helper.php
  src/View/Helper/FormHelper.php
  src/View/Helper/HtmlHelper.php
  src/View/Widget/ButtonWidget.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/Helper/HtmlHelperTest.php
  tests/TestCase/View/Widget/ButtonWidgetTest.php
Labels: enhancement

#13520 Fix double escaping of URLs in PaginatorHelper::meta().
  src/View/Helper/PaginatorHelper.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
Labels: defect

#13521 Fix JsonType to not express null as string.
  src/Database/Type/JsonType.php
  tests/TestCase/Database/Type/JsonTypeTest.php
Labels: enhancement

#13524 Split Paginator::paginate() into smaller methods.
  src/Datasource/Paginator.php
Labels: enhancement

#13506 Throw exception if context cannot be generated for given entity.
  src/View/Form/ContextFactory.php
  src/View/Helper/FormHelper.php
  tests/TestCase/View/Form/ContextFactoryTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/test_app/templates/Posts/cache_form.php
Labels: enhancement

#13525 4.x cache cleanup
  src/Cache/CacheEngine.php
  tests/TestCase/Cache/Engine/FileEngineTest.php
Labels: cleanup

#13541 Add deprecation warning for Form::_buildValidator
  src/Form/Form.php
Labels: deprecations

#13540 Fix errors reported by static analyzers.
  psalm-baseline.xml
  psalm.xml
  src/Controller/Component/RequestHandlerComponent.php
  src/Controller/ErrorController.php
  src/Event/Decorator/SubjectFilterDecorator.php
  src/Event/EventInterface.php
  src/Http/Middleware/CsrfProtectionMiddleware.php
  src/Http/MiddlewareQueue.php
  src/Http/ResponseEmitter.php
  src/Http/Session.php
  src/Http/Session/DatabaseSession.php
  src/View/View.php
  src/View/Widget/RadioWidget.php
  tests/TestCase/Http/MiddlewareQueueTest.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
Labels: cleanup

#13546 Removed deprecated tag.
  src/View/ViewVarsTrait.php
Labels: deprecations, documentation, view

#13538 Add ascii validation methods
  src/Validation/Validation.php
  src/Validation/Validator.php
  tests/TestCase/Validation/ValidationTest.php
  tests/TestCase/Validation/ValidatorTest.php
Labels: validation

#13545 Remove unneeded ViewVarsTrait from View.
  src/View/View.php
  tests/TestCase/Error/DebuggerTest.php
Labels: cleanup

#13549 More concrete array doc for string value arrays.
  src/Console/CommandCollection.php
  src/Http/Response.php
  src/Http/Session/CacheSession.php
  src/I18n/Date.php
  src/I18n/FrozenDate.php
  src/I18n/FrozenTime.php
  src/I18n/Time.php
  src/View/Helper/HtmlHelper.php
  src/View/Helper/IdGeneratorTrait.php
  src/View/StringTemplate.php
  src/View/View.php
  src/View/ViewBlock.php
  src/View/Widget/DateTimeWidget.php
Labels: documentation

#13553 allow socket to connect to unix file based sockets
  src/Network/Socket.php
Labels: defect

#13552 Socket connect works with unix file sockets using port null
  src/Network/Socket.php
  tests/TestCase/Network/SocketTest.php
Labels: defect

#13560 Fix up doc blocks and issues around mixed return type.
  psalm-baseline.xml
  src/Auth/BaseAuthenticate.php
  src/Auth/BasicAuthenticate.php
  src/Auth/DigestAuthenticate.php
  src/Auth/FormAuthenticate.php
  src/Auth/Storage/MemoryStorage.php
  src/Auth/Storage/StorageInterface.php
  src/Cache/Cache.php
  src/Console/ConsoleIo.php
  src/Console/ConsoleOutput.php
  src/Console/Shell.php
  src/Controller/Component.php
  src/Database/DriverInterface.php
  src/Database/Statement/StatementDecorator.php
  src/Database/StatementInterface.php
  src/Database/Type/BinaryUuidType.php
  src/Datasource/EntityTrait.php
  src/Datasource/InvalidPropertyInterface.php
  src/Datasource/QueryCacher.php
  src/Error/BaseErrorHandler.php
  src/Error/Debugger.php
  src/Http/Client.php
  src/Http/Response.php
  src/Shell/Helper/TableHelper.php
  src/basics.php
  tests/test_app/TestApp/Shell/TestingDispatchShell.php
Labels: enhancement

#13563 More concrete array doc for string value arrays.
  src/Collection/ExtractTrait.php
  src/Command/RoutesGenerateCommand.php
  src/Console/CommandRunner.php
  src/Console/CommandScanner.php
  src/Console/ConsoleInputOption.php
  src/Console/Exception/MissingOptionException.php
  src/Core/Configure.php
  src/Http/CorsBuilder.php
  src/Http/ServerRequest.php
  src/Mailer/Renderer.php
  src/Mailer/Transport/SmtpTransport.php
  src/ORM/Association/BelongsToMany.php
  src/ORM/Association/HasMany.php
  src/ORM/Association/Loader/SelectLoader.php
  src/ORM/LazyEagerLoader.php
  src/ORM/Query.php
  src/Routing/Route/Route.php
  src/Routing/RouteBuilder.php
  src/Routing/RouteCollection.php
  src/Shell/Task/CommandTask.php
  src/TestSuite/Constraint/Console/ContentsBase.php
  src/TestSuite/Fixture/FixtureManager.php
  src/TestSuite/TestCase.php
  src/Utility/MergeVariablesTrait.php
  src/Utility/Text.php
  src/Utility/Xml.php
  src/Validation/Validation.php
  src/View/Exception/MissingCellTemplateException.php
  src/View/Exception/MissingTemplateException.php
  src/View/Helper/TextHelper.php
  src/View/StringTemplate.php
  src/View/StringTemplateTrait.php
Labels: documentation

#13565 Clear uncleared property in TableLocator::clear method
  src/ORM/Locator/TableLocator.php
Labels: ORM

#13566 Fix memory leak in unit tests - improve clean up in tearDown method
  src/ORM/Locator/LocatorAwareTrait.php
  src/TestSuite/TestCase.php
Labels: testing

#13568 Throw exception from Event::getSubject() when subject is null.
  src/Event/Decorator/SubjectFilterDecorator.php
  src/Event/Event.php
  src/Event/EventInterface.php
  src/Event/EventManager.php
  tests/TestCase/Event/EventTest.php
Labels: enhancement

#13580 Add abort() wrapper similar to Shell::abort().
  src/Console/ConsoleIo.php
  src/Console/Shell.php
  tests/TestCase/Console/ConsoleIoTest.php
Labels: enhancement

#13579 Fix exception to be valid error default code 1 instead of 244 - Alternative
  src/Console/Exception/ConsoleException.php
  src/Console/Exception/MissingHelperException.php
  src/Console/Exception/MissingShellException.php
  src/Console/Exception/MissingShellMethodException.php
  src/Console/Exception/MissingTaskException.php
  src/Console/Exception/StopException.php
  tests/TestCase/ExceptionsTest.php
Labels: defect

#13567 WIP - PHP 7.4
  src/Console/ConsoleOutput.php
  src/Shell/CompletionShell.php
  src/View/Helper/SecureFieldTokenTrait.php
  tests/TestCase/View/ViewTest.php
Labels: compatibility

#13575 Docblock fixes: Backport from 4.x
  src/Auth/AbstractPasswordHasher.php
  src/Auth/BasicAuthenticate.php
  src/Auth/DefaultPasswordHasher.php
  src/Auth/DigestAuthenticate.php
  src/Auth/FallbackPasswordHasher.php
  src/Cache/CacheEngine.php
  src/Cache/Engine/ApcuEngine.php
  src/Cache/Engine/ArrayEngine.php
  src/Cache/Engine/MemcachedEngine.php
  src/Cache/Engine/RedisEngine.php
  src/Cache/Engine/WincacheEngine.php
  src/Cache/Engine/XcacheEngine.php
  src/Collection/ExtractTrait.php
  src/Collection/Iterator/ExtractIterator.php
  src/Collection/Iterator/MapReduce.php
  src/Collection/Iterator/NestIterator.php
  src/Collection/Iterator/ZipIterator.php
  src/Console/ConsoleInputArgument.php
  src/Console/ConsoleInputOption.php
  src/Console/ConsoleOutput.php
  src/Controller/Controller.php
  src/Routing/RouteCollection.php
  src/Shell/Helper/ProgressHelper.php
  src/Shell/Helper/TableHelper.php
  src/Utility/Security.php
Labels: documentation
