Repository cakephp/cakephp, pull requests merged in 2019-01, with the labels that each got.

#12835 Better grouping in CLI for commands.
  src/Command/HelpCommand.php
  tests/TestCase/Command/HelpCommandTest.php
Labels: Enhancement, RFC

#12865 Trait annotations
  src/TestSuite/ConsoleIntegrationTestTrait.php
  src/TestSuite/EmailTrait.php
  tests/TestCase/TestSuite/EmailTraitTest.php
Labels: testing

#12869 Add callable typehint to QueryExpression methods and_ & or_
  src/Database/Expression/QueryExpression.php
Labels: documentation

#12870 Add string|array|null typehint for data
  src/TestSuite/IntegrationTestTrait.php
Labels: documentation

#12871 Remove bad chaining typehints and fix up RepositoryInterface methods.
  src/Core/PluginApplicationInterface.php
  src/Database/Driver.php
  src/Database/DriverInterface.php
  src/Database/Query.php
  src/Database/Schema/TableSchema.php
  src/Database/Schema/TableSchemaInterface.php
  src/Datasource/RepositoryInterface.php
  src/Event/EventManager.php
  src/Event/EventManagerInterface.php
  src/Http/BaseApplication.php
  src/ORM/Query.php
  tests/TestCase/Controller/Component/PaginatorComponentTest.php
  tests/TestCase/Datasource/PaginatorTest.php
Labels: documentation

#12746 Include prefer lowest and simplify checks
  .travis.yml
  composer.json
  phpstan.neon
Labels: testing

#12877 Explain unusual parent call
  src/ORM/Query.php
Labels: documentation

#12876 Use validator for prefer-lowest.
  .travis.yml
Labels: testing

#12788 Support multiple table locations.
  src/ORM/Locator/TableLocator.php
  tests/TestCase/ORM/Locator/TableLocatorTest.php
  tests/test_app/Plugin/TestPlugin/src/Infrastructure/Table/AddressesTable.php
  tests/test_app/TestApp/Infrastructure/Table/AddressesTable.php
Labels: Enhancement, ORM

#12884 Fix variable name to prevent type warning in IDE
  src/Validation/Validator.php
Labels: optimization

#12886 Fix missing deprecation docs
  src/Core/Plugin.php
Labels: deprecations, documentation

#12904 Cake\I18n\Time toQuarter() return Int
  src/I18n/Time.php
  tests/TestCase/View/Helper/TimeHelperTest.php
Labels: Defect

#12905 Fix docblock on ORM/Table.php
  src/ORM/Table.php
Labels: documentation

#12923 Remove unused code.
  src/Http/ActionDispatcher.php
Labels: cleanup

#12907 PSR 15
  composer.json
  src/Core/HttpApplicationInterface.php
  src/Error/Middleware/ErrorHandlerMiddleware.php
  src/Http/ActionDispatcher.php
  src/Http/BaseApplication.php
  src/Http/Middleware/BodyParserMiddleware.php
  src/Http/Middleware/CallableDecoratorMiddleware.php
  src/Http/Middleware/CsrfProtectionMiddleware.php
  src/Http/Middleware/DoublePassDecoratorMiddleware.php
  src/Http/Middleware/EncryptedCookieMiddleware.php
  src/Http/Middleware/SecurityHeadersMiddleware.php
  src/Http/MiddlewareQueue.php
  src/Http/Runner.php
  src/Http/Server.php
  src/I18n/Middleware/LocaleSelectorMiddleware.php
  src/Routing/Middleware/RoutingMiddleware.php
  tests/TestCase/Error/Middleware/ErrorHandlerMiddlewareTest.php
  tests/TestCase/Http/ActionDispatcherTest.php
  tests/TestCase/Http/BaseApplicationTest.php
  tests/TestCase/Http/Middleware/BodyParserMiddlewareTest.php
  tests/TestCase/Http/Middleware/CsrfProtectionMiddlewareTest.php
  tests/TestCase/Http/Middleware/EncryptedCookieMiddlewareTest.php
  tests/TestCase/Http/Middleware/SecurityHeadersMiddlewareTest.php
  tests/TestCase/Http/MiddlewareQueueTest.php
  tests/TestCase/Http/RunnerTest.php
  tests/TestCase/Http/ServerTest.php
  tests/TestCase/I18n/Middleware/LocaleSelectorMiddlewareTest.php
  tests/TestCase/Routing/Middleware/RoutingMiddlewareTest.php
  tests/test_app/TestApp/Application.php
  tests/test_app/TestApp/Http/MiddlewareApplication.php
  tests/test_app/TestApp/Http/TestRequestHandler.php
Labels: http

#12936 Improve error messages when persistence fails
  src/ORM/Exception/PersistenceFailedException.php
  tests/TestCase/ORM/TableTest.php
Labels: Defect

#12939 Change Cookie::getExpiresTimestamp() return type
  src/Http/Cookie/Cookie.php
  src/Http/Cookie/CookieInterface.php
  tests/TestCase/Http/Cookie/CookieTest.php
  tests/TestCase/Http/ResponseTest.php
Labels: Enhancement

#12914 Patching search data in findOrCreate to ensure valid entity
  src/ORM/Table.php
  tests/TestCase/ORM/TableTest.php
Labels: Defect, ORM
