Repository cakephp/cakephp, pull requests merged in 2019-06, with the labels that each got.

#13309 Remove incorrect example
  src/Database/Query.php
Labels: database, documentation

#13310 Fix up string[] doc blocks and annotations.
  psalm-baseline.xml
  src/Database/Query.php
  src/Database/TypeMap.php
Labels: documentation

#13311 [2.x]Fix When PHPUnit 5.2.0+, test ends before calling FixtureManager::shutdown()
  lib/Cake/TestSuite/CakeTestRunner.php
  lib/Cake/TestSuite/CakeTestSuiteCommand.php
Labels: testing

#13320 Backport 4.x model aware fix for inflected assignment.
  src/Datasource/ModelAwareTrait.php
Labels: defect

#13287 4.x connection cache
  psalm-baseline.xml
  src/Database/Connection.php
  src/Database/Expression/QueryExpression.php
  src/Database/Schema/CachedCollection.php
  src/Database/SchemaCache.php
  src/Database/composer.json
  src/Datasource/ConnectionInterface.php
  src/Datasource/RepositoryInterface.php
  src/Datasource/composer.json
  src/Event/EventDispatcherTrait.php
  tests/TestCase/Command/SchemacacheCommandsTest.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Database/Schema/CollectionTest.php
  tests/TestCase/Database/Schema/TableSchemaTest.php
  tests/TestCase/Database/SchemaCacheTest.php
  tests/TestCase/TestSuite/FixtureManagerTest.php
Labels: enhancement

#13326 Backport 4.x validation
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: validation

#13318 3.next - Improve nested validator support in EntityContext
  src/Datasource/EntityTrait.php
  src/View/Form/EntityContext.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/View/Form/EntityContextTest.php
Labels: helpers, validation

#13328 4.x serverShell => ServerCommand
  src/Command/ServerCommand.php
  tests/TestCase/Command/ServerCommandTest.php
Labels: console

#13335 Fix return type of SqlserverDialectTrait::version()
  src/Database/Dialect/SqlserverDialectTrait.php
  tests/TestCase/Database/Driver/SqlserverTest.php
Labels: defect

#13338 Use constants instead of strings.
  src/Validation/ValidationRule.php
  src/Validation/Validator.php
Labels: cleanup

#13324 Backport 4.x deprecations for easier upgrading.
  src/Datasource/EntityTrait.php
Labels: deprecations

#13330 Convert I18nShell to commands.
  src/Command/I18nCommand.php
  src/Command/I18nExtractCommand.php
  src/Command/I18nInitCommand.php
  src/Console/ConsoleInput.php
  src/Shell/I18nShell.php
  tests/TestCase/Command/I18nCommandTest.php
  tests/TestCase/Command/I18nExtractCommandTest.php
  tests/TestCase/Console/CommandCollectionTest.php
  tests/TestCase/Console/ConsoleInputTest.php
  tests/TestCase/Console/ShellTest.php
Labels: console, enhancement

#13346 Remove unneeded class_exists() check.
  src/Core/ObjectRegistry.php
Labels: cleanup

#13355 4.x error handler
  src/Console/ConsoleErrorHandler.php
  src/Error/BaseErrorHandler.php
  src/Error/ErrorHandler.php
  src/Error/ErrorLogger.php
  src/Error/Middleware/ErrorHandlerMiddleware.php
  tests/TestCase/Error/ErrorHandlerTest.php
  tests/TestCase/Error/Middleware/ErrorHandlerMiddlewareTest.php
Labels: enhancement

#13348 3.next - Improve console testing with interactive input
  src/TestSuite/ConsoleIntegrationTestTrait.php
  src/TestSuite/Stub/ConsoleInput.php
  tests/TestCase/TestSuite/ConsoleIntegrationTestTraitTest.php
Labels: console, enhancement, testing

#13325 Remove deprecated method of 3.x.
  src/Datasource/EntityTrait.php
  tests/TestCase/ORM/EntityTest.php
Labels: cleanup, deprecations

#13360 Added missing parenthesis to TupleComparisonTranslatorTrait example
  src/Database/Dialect/TupleComparisonTranslatorTrait.php
Labels: documentation

#13359 Fix Type::buildAll() not returning type instance set using Type::set()
  src/Database/Type.php
  src/ORM/ResultSet.php
  tests/TestCase/Database/QueryTest.php
  tests/TestCase/Database/TypeTest.php
  tests/test_app/TestApp/Database/Type/BarType.php
Labels: defect

#13364 Correct parameter name for inspecting extensions
  src/Http/ServerRequest.php
Labels: documentation, http

#13349 4.x fixtures
  psalm-baseline.xml
  src/Database/ConstraintsInterface.php
  src/Datasource/FixtureInterface.php
  src/TestSuite/Fixture/FixtureInjector.php
  src/TestSuite/Fixture/FixtureManager.php
  src/TestSuite/Fixture/TestFixture.php
  src/TestSuite/TestCase.php
Labels: enhancement

#13357 Fix for issue 13342 - RadioWidget and MultiCheckboxWidget now use passed "id"
  src/View/Helper/IdGeneratorTrait.php
  src/View/Widget/MultiCheckboxWidget.php
  src/View/Widget/RadioWidget.php
  tests/TestCase/View/Widget/MultiCheckboxWidgetTest.php
  tests/TestCase/View/Widget/RadioWidgetTest.php
Labels: enhancement

#13368 Clarify and update docs for ServerRequest::is()
  src/Http/ServerRequest.php
Labels: documentation

#13339 4.0 support underscored name in command
  src/Command/CacheClearCommand.php
  src/Command/CacheClearallCommand.php
  src/Command/CacheListCommand.php
  src/Command/I18nExtractCommand.php
  src/Command/I18nInitCommand.php
  src/Command/RoutesCheckCommand.php
  src/Command/RoutesGenerateCommand.php
  src/Command/SchemacacheBuildCommand.php
  src/Command/SchemacacheClearCommand.php
  src/Console/Command.php
  src/Console/CommandScanner.php
  tests/TestCase/Command/CacheCommandsTest.php
  tests/TestCase/Command/CompletionCommandTest.php
Labels: enhancement

#13375 Fix backward incompatibility for allowEmpty* methods
  src/Validation/Validator.php
  tests/TestCase/Validation/ValidatorTest.php
Labels: validation

#13131 #13088 - Validation::datetime
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: validation

#13379 Remove duplicate tests.
  tests/TestCase/Validation/ValidationTest.php
Labels: cleanup, testing

#13383 Fix error reported by psalm.
  psalm-baseline.xml
  psalm.xml
  src/Command/CompletionCommand.php
  src/Console/CommandCollection.php
  src/Console/CommandFactory.php
  src/Console/CommandScanner.php
  src/Console/ShellDispatcher.php
Labels: cleanup

#13382 4.x - Update tests to not use deprecated PHPUnit features
  src/Http/Middleware/BodyParserMiddleware.php
  src/Routing/RouteBuilder.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Database/QueryTest.php
  tests/TestCase/Datasource/ModelAwareTraitTest.php
  tests/TestCase/Event/EventDispatcherTraitTest.php
  tests/TestCase/Http/ActionDispatcherTest.php
  tests/TestCase/Http/Middleware/BodyParserMiddlewareTest.php
  tests/TestCase/Mailer/Transport/SmtpTransportTest.php
  tests/TestCase/ORM/QueryTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/Routing/RouteBuilderTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/ViewTest.php
  tests/test_app/TestApp/Stub/Stub.php
Labels: deprecations, testing
