Repository cakephp/cakephp, pull requests merged in 2019-09, with the labels that each got.

#13584 Add support for stripping aliases from identifier expressions.
  src/Database/SqlDialectTrait.php
  tests/TestCase/Database/QueryTest.php
Labels: defect

#13587 Fix abort() method.
  src/Console/ConsoleIo.php
  tests/TestCase/Console/ConsoleIoTest.php
Labels: compatibility

#13593 Deprecate setting fixtures as string.
  src/TestSuite/Fixture/FixtureManager.php
Labels: deprecations

#13591 Remove untested and unneeded feature.
  src/TestSuite/Fixture/FixtureManager.php
Labels: cleanup

#13594 Fix errors reported by psalm under Routing.
  psalm-baseline.xml
  src/Routing/Route/Route.php
  src/Routing/RouteBuilder.php
  src/Routing/RouteCollection.php
  src/Routing/Router.php
Labels: cleanup

#13597 Removed unused constructor argument.
  src/TestSuite/IntegrationTestTrait.php
  src/TestSuite/MiddlewareDispatcher.php
Labels: cleanup

#13432 Set expiration atomically in RedisEngine::add()
  src/Cache/Engine/RedisEngine.php
Labels: cache

#13606 Fix loading ShellHelpers from plugins
  lib/Cake/Console/Shell.php
Labels: defect

#13616 Fix some docblocks.
  tests/TestCase/DatabaseSuite.php
Labels: documentation

#13619 Fix some docblocks.
  src/ORM/Query.php
Labels: documentation

#13615 Add SQLite decimal length/precision
  src/Database/Schema/SqliteSchema.php
  tests/TestCase/Database/Schema/SqliteSchemaTest.php
Labels: enhancement

#13632 Fix CS - empty values last in docblocks
  src/Cache/Engine/MemcachedEngine.php
  src/Cache/SimpleCacheEngine.php
  src/Console/Command.php
  src/Console/ConsoleIo.php
  src/Controller/Component/CookieComponent.php
  src/Controller/Component/RequestHandlerComponent.php
  src/Core/App.php
  src/Database/Driver/PDODriverTrait.php
  src/Database/Query.php
  src/Database/Type/BinaryType.php
  src/Database/Type/BinaryUuidType.php
  src/Database/Type/FloatType.php
  src/Database/Type/JsonType.php
  src/Datasource/EntityInterface.php
  src/Datasource/EntityTrait.php
  src/Datasource/QueryTrait.php
  src/Filesystem/File.php
  src/Form/Schema.php
  src/Http/Client/FormDataPart.php
  src/Http/Client/Response.php
  src/Http/Response.php
  src/Http/ResponseEmitter.php
  src/Http/ServerRequest.php
  src/Mailer/Email.php
  src/Network/Socket.php
  src/ORM/Association/BelongsToMany.php
  src/Routing/Route/Route.php
  src/Routing/RouteBuilder.php
  src/Routing/RouteCollection.php
  src/TestSuite/IntegrationTestTrait.php
  src/Validation/Validator.php
  src/View/Form/ArrayContext.php
  src/View/Form/ContextInterface.php
  src/View/Form/EntityContext.php
  src/View/Helper/TimeHelper.php
  src/View/StringTemplateTrait.php
  src/View/ViewBuilder.php
  src/View/Widget/RadioWidget.php
Labels: code-style

#13633 Fix CS - PSR12 issues
  src/Database/Type/DateTimeType.php
  src/Filesystem/File.php
  src/Form/Form.php
  src/Http/MiddlewareQueue.php
  src/I18n/I18n.php
  src/I18n/MessagesFileLoader.php
  src/ORM/Table.php
  src/Routing/RequestActionTrait.php
  src/Validation/ValidatorAwareTrait.php
Labels: code-style

#13637 Fix CS - PSR12
  tests/TestCase/Auth/Storage/MemoryStorageTest.php
  tests/TestCase/Console/CommandTest.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Controller/Exception/AuthSecurityExceptionTest.php
  tests/TestCase/Controller/Exception/SecurityExceptionTest.php
  tests/TestCase/Core/FunctionsTest.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Database/DriverTest.php
  tests/TestCase/Database/Expression/FunctionExpressionTest.php
  tests/TestCase/Database/Expression/IdentifierExpressionTest.php
  tests/TestCase/Database/Expression/TupleComparisonTest.php
  tests/TestCase/Database/ExpressionTypeCastingTest.php
  tests/TestCase/Database/FunctionsBuilderTest.php
  tests/TestCase/Database/Log/LoggedQueryTest.php
  tests/TestCase/Database/Log/QueryLoggerTest.php
  tests/TestCase/Database/QueryTest.php
  tests/TestCase/Datasource/ConnectionManagerTest.php
  tests/TestCase/Error/ExceptionRendererTest.php
  tests/TestCase/Error/Middleware/ErrorHandlerMiddlewareTest.php
  tests/TestCase/Event/EventManagerTest.php
  tests/TestCase/ExceptionsTest.php
  tests/TestCase/Http/ActionDispatcherTest.php
  tests/TestCase/Http/Client/Adapter/StreamTest.php
  tests/TestCase/Http/ServerRequestTest.php
  tests/TestCase/Http/SessionTest.php
  tests/TestCase/I18n/Parser/MoFileParserTest.php
  tests/TestCase/I18n/Parser/PoFileParserTest.php
  tests/TestCase/Log/Engine/FileLogTest.php
  tests/TestCase/Log/LogTest.php
  tests/TestCase/Mailer/EmailTest.php
  tests/TestCase/ORM/AssociationTest.php
  tests/TestCase/ORM/Behavior/Translate/TranslateTraitTest.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
  tests/TestCase/ORM/Locator/TableLocatorTest.php
  tests/TestCase/ORM/MarshallerTest.php
  tests/TestCase/ORM/QueryTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/Routing/DispatcherTest.php
  tests/TestCase/Validation/RulesProviderTest.php
  tests/TestCase/Validation/ValidationSetTest.php
  tests/TestCase/Validation/ValidationTest.php
  tests/TestCase/Validation/ValidatorTest.php
  tests/TestCase/View/Form/EntityContextTest.php
  tests/TestCase/View/Helper/TimeHelperTest.php
  tests/TestCase/View/StringTemplateTraitTest.php
  tests/TestCase/View/ViewVarsTraitTest.php
Labels: code-style

#13630 4.x url helper
  src/View/Helper/HtmlHelper.php
  src/View/Helper/UrlHelper.php
  tests/TestCase/View/Helper/HtmlHelperTest.php
  tests/TestCase/View/Helper/UrlHelperTest.php
Labels: cleanup

#13640 `CURLOPT_POSTFIELDS` only set when the request body content is not empty
  src/Http/Client/Adapter/Curl.php
Labels: defect, http

#13634 Add class to statically get asset URLs similar to Router::url() for routes.
  src/Routing/Asset.php
  src/View/Helper/UrlHelper.php
  tests/TestCase/Routing/AssetTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/Helper/HtmlHelperTest.php
  tests/TestCase/View/Helper/UrlHelperTest.php
Labels: enhancement

#13650 Fix existence check in MailSentWith.
  src/TestSuite/Constraint/Email/MailSentWith.php
  tests/TestCase/TestSuite/EmailTraitTest.php
Labels: defect

#13648 4.x mysql charset
  src/Database/Driver/Mysql.php
  tests/TestCase/Database/Driver/MysqlTest.php
Labels: enhancement

#13656 Remove unneeded ServerRequest properties.
  src/Http/ServerRequest.php
Labels: cleanup

#13657 Remove redundant config.
  phpunit.xml.dist
Labels: cleanup

#13655 Remove unnecessary 30 days memcached duration check.
  src/Cache/Engine/MemcachedEngine.php
Labels: cache

#13626 Refactor $fixtures property to a getter method
  src/TestSuite/Fixture/FixtureManager.php
  src/TestSuite/TestCase.php
  tests/Fixture/FixturizedTestCase.php
  tests/TestCase/Auth/BasicAuthenticateTest.php
  tests/TestCase/Auth/DigestAuthenticateTest.php
  tests/TestCase/Auth/FormAuthenticateTest.php
  tests/TestCase/Command/SchemacacheCommandsTest.php
  tests/TestCase/Console/ShellTest.php
  tests/TestCase/Controller/Component/AuthComponentTest.php
  tests/TestCase/Controller/Component/PaginatorComponentTest.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Database/ExpressionTypeCastingIntegrationTest.php
  tests/TestCase/Database/QueryTest.php
  tests/TestCase/Database/Schema/CollectionTest.php
  tests/TestCase/Database/Schema/TableSchemaTest.php
  tests/TestCase/Database/SchemaCacheTest.php
  tests/TestCase/Datasource/PaginatorTest.php
  tests/TestCase/Datasource/SimplePaginatorTest.php
  tests/TestCase/Http/Session/DatabaseSessionTest.php
  tests/TestCase/Http/SessionTest.php
  tests/TestCase/Mailer/EmailTest.php
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/ORM/Association/BelongsToTest.php
  tests/TestCase/ORM/Association/HasManyTest.php
  tests/TestCase/ORM/Association/HasOneTest.php
  tests/TestCase/ORM/AssociationProxyTest.php
  tests/TestCase/ORM/Behavior/BehaviorRegressionTest.php
  tests/TestCase/ORM/Behavior/CounterCacheBehaviorTest.php
  tests/TestCase/ORM/Behavior/TimestampBehaviorTest.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorShadowTableTest.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
  tests/TestCase/ORM/Behavior/TreeBehaviorTest.php
  tests/TestCase/ORM/BindingKeyTest.php
  tests/TestCase/ORM/CompositeKeysTest.php
  tests/TestCase/ORM/MarshallerTest.php
  tests/TestCase/ORM/QueryRegressionTest.php
  tests/TestCase/ORM/QueryTest.php
  tests/TestCase/ORM/ResultSetTest.php
  tests/TestCase/ORM/RulesCheckerIntegrationTest.php
  tests/TestCase/ORM/SaveOptionsBuilderTest.php
  tests/TestCase/ORM/TableComplexIdTest.php
  tests/TestCase/ORM/TableRegressionTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/ORM/TableUuidTest.php
  tests/TestCase/TestSuite/FixtureManagerTest.php
  tests/TestCase/TestSuite/TestFixtureTest.php
  tests/TestCase/Utility/XmlTest.php
  tests/TestCase/View/Form/EntityContextTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/ViewTest.php
Labels: enhancement

#13662 Cleanup
  src/Command/I18nExtractCommand.php
  src/Command/PluginAssetsTrait.php
  src/Utility/Inflector.php
Labels: cleanup

#13677 Fix header comparison debug output
  src/TestSuite/Constraint/Response/HeaderEquals.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
Labels: defect

#13678 4.x: Remove remaining pieces after requestAction removal
  src/Controller/Component/SecurityComponent.php
  src/Http/ServerRequest.php
  tests/TestCase/Http/ActionDispatcherTest.php
  tests/TestCase/Http/ServerRequestTest.php
  tests/TestCase/Routing/RouterTest.php
Labels: cleanup

#13672 Avoid potentially parsing URL multiple times.
  src/Routing/Router.php
  tests/TestCase/Controller/Component/AuthComponentTest.php
  tests/TestCase/Routing/RouterTest.php
Labels: routing

#13631 Add deprecations for 4.x API changes.
  src/Console/ConsoleIo.php
  src/View/Helper/HtmlHelper.php
  src/View/Helper/UrlHelper.php
  tests/TestCase/View/Helper/HtmlHelperTest.php
Labels: deprecations

#13533 4.x completion
  src/Command/CompletionCommand.php
  tests/TestCase/Command/CompletionCommandTest.php
Labels: console

#13684 Fix generation of datetime control.
  src/View/Helper/FormHelper.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: defect

#13687 Fix missing "for" attribute for datetime input labels.
  src/View/Helper/FormHelper.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: defect

#13691 Fix Number::toPercentage() format
  src/I18n/Number.php
  tests/TestCase/I18n/NumberTest.php
Labels: i18n

#13690 Remove unnecessary quotes and \r\n in FormData format
  src/Http/Client/FormData.php
  tests/TestCase/Http/Client/FormDataTest.php
Labels: http client
