Repository cakephp/cakephp, pull requests merged in 2019-10, with the labels that each got.

#13686 #11249: custom selected class
  src/View/Helper/FormHelper.php
  src/View/Widget/MultiCheckboxWidget.php
  src/View/Widget/RadioWidget.php
  tests/TestCase/View/Widget/MultiCheckboxWidgetTest.php
  tests/TestCase/View/Widget/RadioWidgetTest.php
Labels: enhancement

#13702 Improve docblocks and code readability.
  src/Controller/Component/RequestHandlerComponent.php
Labels: cleanup

#13701 Cleanup SecurityComponent.
  src/Controller/Component/SecurityComponent.php
Labels: cleanup

#13710 More dead code cleanup.
  src/Controller/Component/SecurityComponent.php
Labels: cleanup

#13717 Include file and line information in error handler middleware
  src/Error/Middleware/ErrorHandlerMiddleware.php
Labels: enhancement

#13720 Replace remaining integer debug levels references
  src/Core/Configure/Engine/PhpConfig.php
  src/Core/Exception/Exception.php
  src/Error/BaseErrorHandler.php
  src/Error/ErrorHandler.php
  src/Error/ExceptionRenderer.php
Labels: documentation

#13726 return value for __invoke was wrong
  tests/test_app/TestApp/Http/BadResponseApplication.php
Labels: testing

#13724 Fixed microseconds being dropped when creating Time and FrozenTime
  src/I18n/DateFormatTrait.php
  src/I18n/FrozenTime.php
  src/I18n/Time.php
  tests/TestCase/I18n/TimeTest.php
Labels: defect

#13735 Update param type in docblock.
  src/View/Helper/PaginatorHelper.php
Labels: documentation

#13737 Add missing Email `@deprecated` tags
  src/Mailer/Email.php
Labels: documentation, email

#13716 First draft of http package
  src/Controller/Controller.php
  src/Http/ActionDispatcher.php
  src/Http/ControllerFactory.php
  src/Http/ControllerInterface.php
  src/Http/Cookie/Cookie.php
  src/Http/Exception/MissingControllerException.php
  src/Http/Middleware/CsrfProtectionMiddleware.php
  src/Http/ResponseEmitter.php
  src/Http/composer.json
  src/Routing/Exception/MissingControllerException.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Error/ErrorHandlerTest.php
  tests/TestCase/Error/ExceptionRendererTest.php
  tests/TestCase/Error/Middleware/ErrorHandlerMiddlewareTest.php
  tests/TestCase/ExceptionsTest.php
  tests/TestCase/Http/ActionDispatcherTest.php
  tests/TestCase/Http/ControllerFactoryTest.php
  tests/TestCase/Http/Middleware/CsrfProtectionMiddlewareTest.php
  tests/test_app/TestApp/Controller/CakesController.php
Labels: http

#13747 Fix invalid argument types in SqlserverSchema
  src/Database/Schema/Collection.php
  src/Database/Schema/SqlserverSchema.php
Labels: database

#13754 Fix paginator limit if query string exists
  src/View/Helper/PaginatorHelper.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
Labels: defect

#13753 Remove unneeded inline annotations. Fix self to static.
  phpstan.neon
  psalm-baseline.xml
  src/Collection/Iterator/ExtractIterator.php
  src/Controller/Component/RequestHandlerComponent.php
  src/Controller/Component/SecurityComponent.php
  src/Database/Expression/QueryExpression.php
  src/Database/Query.php
  src/Database/Schema/Collection.php
  src/Mailer/Email.php
  src/ORM/LazyEagerLoader.php
  src/View/Form/EntityContext.php
Labels: documentation

#13749 Fix incorrect cookies being used on redirects
  src/Http/Client.php
  tests/TestCase/Http/ClientTest.php
Labels: http client

#13742 Improve command option parser errors.
  src/Console/ConsoleOptionParser.php
  tests/TestCase/Console/CommandTest.php
  tests/TestCase/Console/ShellTest.php
  tests/TestCase/TestSuite/ConsoleIntegrationTestTraitTest.php
Labels: console

#13755 4.x routing
  src/Routing/RouteBuilder.php
  src/Routing/RouteCollection.php
  src/Routing/Router.php
  tests/TestCase/Routing/RouteBuilderTest.php
Labels: cleanup

#13750 Allow dates before 1600 to be valid
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: validation

#13774 Fix docblock
  src/Core/functions.php
Labels: documentation

#13775 Fix inteliphense docblock error
  src/View/Helper/FormHelper.php
Labels: documentation

#13784 Fix array docblocks.
  src/Auth/AbstractPasswordHasher.php
  src/Console/ConsoleIo.php
  src/Console/Shell.php
  src/Http/CorsBuilder.php
  src/Http/Response.php
  src/ORM/AssociationCollection.php
  src/ORM/RulesChecker.php
  src/TestSuite/Stub/ConsoleOutput.php
Labels: documentation

#13783 Add and/or methods on QueryExpression directly
  src/Database/Expression/QueryExpression.php
  src/ORM/Marshaller.php
  tests/TestCase/Database/Expression/QueryExpressionTest.php
Labels: database

#13787 Fix docblock/phpstan error. Improve phpstan run.
  .travis.yml
  composer.json
  src/Database/Type/FloatType.php
  src/Mailer/Transport/SmtpTransport.php
  src/View/SerializedView.php
  src/View/View.php
Labels: documentation

#13762 Enable Console lib split
  psalm-baseline.xml
  src/Console/BaseCommand.php
  src/Console/Command.php
  src/Console/CommandCollection.php
  src/Console/CommandFactory.php
  src/Console/CommandFactoryInterface.php
  src/Console/CommandInterface.php
  src/Console/CommandRunner.php
  src/Console/CommandScanner.php
  src/Console/ConsoleErrorHandler.php
  src/Console/composer.json
  src/Error/ConsoleErrorHandler.php
  src/Routing/Exception/MissingControllerException.php
  tests/TestCase/Console/CommandFactoryTest.php
  tests/TestCase/Error/ConsoleErrorHandlerTest.php
Labels: console

#13792 Use ::class magic constant instead of string.
  phpstan-baseline.neon
  src/Cache/Engine/ApcuEngine.php
  src/basics.php
Labels: cleanup

#13782 Fix partial empty option for dateTime
  src/View/Helper/FormHelper.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: defect

#13766 Add support for cookies with "SameSite" option.
  src/Http/Client/Response.php
  src/Http/Cookie/Cookie.php
  src/Http/Cookie/CookieCollection.php
  src/Http/Cookie/CookieInterface.php
  src/Http/Response.php
  src/Http/ResponseEmitter.php
  tests/TestCase/Http/Client/ResponseTest.php
  tests/TestCase/Http/Cookie/CookieTest.php
  tests/TestCase/Http/Middleware/CsrfProtectionMiddlewareTest.php
  tests/TestCase/Http/ResponseEmitterTest.php
  tests/TestCase/Http/ResponseTest.php
  tests/TestCase/Http/server_mocks.php
Labels: enhancement

#13789 Add config orFail() wrapper.
  src/Core/Configure.php
  src/Core/InstanceConfigTrait.php
  src/Core/StaticConfigTrait.php
  tests/TestCase/Core/InstanceConfigTraitTest.php
  tests/TestCase/Core/StaticConfigTraitTest.php
  tests/TestCase/View/StringTemplateTest.php
  tests/test_app/TestApp/Config/ReadOnlyTestInstanceConfig.php
Labels: enhancement

#13796 Cleanup exceptions to at least use RuntimeException and include previous
  src/Error/ErrorHandler.php
  src/TestSuite/TestCase.php
  src/View/Cell.php
  tests/TestCase/Core/InstanceConfigTraitTest.php
  tests/TestCase/Error/ErrorHandlerTest.php
Labels: cleanup

#13795 Backport 4.x orFail() for config.
  src/Core/Configure.php
  src/Core/InstanceConfigTrait.php
  src/Core/StaticConfigTrait.php
  tests/TestCase/Core/InstanceConfigTraitTest.php
  tests/TestCase/Core/StaticConfigTraitTest.php
Labels: enhancement

#13811 Remove unneeded PHP version checks
  src/Network/Socket.php
  tests/TestCase/Database/Type/IntegerTypeTest.php
  tests/TestCase/I18n/Formatter/IcuFormatterTest.php
Labels: cleanup

#13819 Add @method annotation to ConnectionInterface.
  src/Datasource/ConnectionInterface.php
Labels: documentation
