Repository cakephp/cakephp, pull requests merged in 2019-12, with the labels that each got.

#13958 Deprecation of mt_rand in uuid generation
  composer.json
  src/Utility/Text.php
  tests/TestCase/Error/ErrorHandlerTest.php
Labels: enhancement, utility

#13969 2.x - PHP 7.4
  .travis.yml
  lib/Cake/Console/ShellDispatcher.php
  lib/Cake/Model/Datasource/Database/Sqlite.php
  lib/Cake/Model/Model.php
  lib/Cake/Test/Case/Cache/CacheTest.php
  lib/Cake/Test/Case/Model/Datasource/Database/MysqlTest.php
  lib/Cake/Test/Case/View/Helper/FormHelperTest.php
  lib/Cake/Test/Case/View/Helper/RssHelperTest.php
  lib/Cake/Test/Case/View/ViewTest.php
Labels: compatibility

#13943 4.x - Added DateTimeTimezoneType
  src/Database/Schema/MysqlSchema.php
  src/Database/Schema/PostgresSchema.php
  src/Database/Schema/SqliteSchema.php
  src/Database/Schema/SqlserverSchema.php
  src/Database/Schema/TableSchemaInterface.php
  src/Database/Type/DateTimeTimezoneType.php
  src/Database/Type/DateTimeType.php
  src/Database/TypeFactory.php
  tests/TestCase/Database/Schema/PostgresSchemaTest.php
  tests/TestCase/Database/Type/DateTimeTimezoneTypeTest.php
Labels: database, enhancement, postgres

#13984 2.x - Updated CakeTestSuiteCommand::run() exit logic to match phpunit's
  lib/Cake/TestSuite/CakeTestSuiteCommand.php
Labels: testing

#13989 Add getter/setter methods for currency
  src/I18n/Number.php
  tests/TestCase/I18n/NumberTest.php
Labels: helpers

#14003 Add link to explain mentioned problem
  src/Database/SchemaCache.php
Labels: documentation

#14005 Remove duplicate calling TableLocator::clear()
  tests/TestCase/Controller/Component/PaginatorComponentTest.php
  tests/TestCase/Database/Schema/TableSchemaTest.php
  tests/TestCase/Datasource/PaginatorTest.php
  tests/TestCase/Http/Session/DatabaseSessionTest.php
  tests/TestCase/ORM/Association/BelongsToTest.php
  tests/TestCase/ORM/Association/HasManyTest.php
  tests/TestCase/ORM/Association/HasOneTest.php
  tests/TestCase/ORM/AssociationProxyTest.php
  tests/TestCase/ORM/AssociationTest.php
  tests/TestCase/ORM/Behavior/CounterCacheBehaviorTest.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
  tests/TestCase/ORM/Behavior/TreeBehaviorTest.php
  tests/TestCase/ORM/EagerLoaderTest.php
  tests/TestCase/ORM/MarshallerTest.php
  tests/TestCase/ORM/QueryRegressionTest.php
  tests/TestCase/ORM/QueryTest.php
  tests/TestCase/ORM/RulesCheckerIntegrationTest.php
  tests/TestCase/ORM/TableRegressionTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/ORM/TableUuidTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: cleanup

#13893 Add support for accounting currency formatting provided by the ICU library
  phpstan.neon
  src/I18n/Number.php
  tests/TestCase/I18n/NumberTest.php
Labels: enhancement, i18n

#14012 4.x - Fixed markdown lists in docblocks
  src/Console/Shell.php
  src/Console/ShellDispatcher.php
  src/Database/Connection.php
  src/Database/Query.php
  src/Http/Client/Exception/RequestException.php
  src/Http/Response.php
  src/I18n/FrozenDate.php
  src/I18n/FrozenTime.php
  src/I18n/Time.php
  src/ORM/Behavior/TranslateBehavior.php
  src/ORM/EagerLoader.php
  src/View/Form/ArrayContext.php
  src/View/Form/EntityContext.php
  src/View/Helper/BreadcrumbsHelper.php
  src/View/Helper/FormHelper.php
  src/View/View.php
  tests/TestCase/Filesystem/FolderTest.php
  tests/TestCase/Http/ServerRequestTest.php
Labels: documentation

#14010 Fixed preserving spaces in Text::slug
  src/Utility/Text.php
  tests/TestCase/Utility/TextTest.php
Labels: utility

#14033 Remove typehint for event data.
  src/TestSuite/Constraint/EventFiredWith.php
  src/TestSuite/TestCase.php
  tests/TestCase/TestSuite/Constraint/EventFiredWithTest.php
Labels: defect

#14041 Shim add for usability with numeric array
  src/Validation/Validator.php
  tests/TestCase/Validation/ValidatorTest.php
Labels: enhancement

#14050 4.1 - Added hard deprecation warning for primaryKey()
  src/Database/Schema/TableSchema.php
  src/View/Form/ArrayContext.php
  src/View/Form/EntityContext.php
  src/View/Form/FormContext.php
  src/View/Form/NullContext.php
Labels: deprecations

#14046 prevent TypeError on preg_match when param is an integer
  src/Routing/Route/Route.php
  tests/TestCase/Routing/Route/RouteTest.php
Labels: defect

#14056 Add support for placeholder in log messages.
  src/Log/Engine/BaseLog.php
  tests/TestCase/Log/Engine/BaseLogTest.php
  tests/test_app/TestApp/Log/Engine/TestBaseLog.php
Labels: enhancement, log

#14061 Supress PHPUnit ReflectionType deprecation warnings on PHP 7.4
  .travis.yml
  src/Cache/CacheRegistry.php
  src/Database/Expression/TupleComparison.php
  src/TestSuite/MockBuilder.php
  src/TestSuite/TestCase.php
  tests/phpunit_aliases.php
Labels: php7.4, testing

#14069 3.x form empty
  src/View/Helper/FormHelper.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: defect

#14067 Add helper method to load routes in tests
  src/TestSuite/MiddlewareDispatcher.php
  src/TestSuite/TestCase.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
  tests/TestCase/TestSuite/TestCaseTest.php
Labels: testing

#14072 4.1 - Deprecate QueryExpression or_() and and_()
  src/Database/Expression/QueryExpression.php
Labels: ORM

#14073 Fix file creation success check.
  src/Console/ConsoleIo.php
  tests/TestCase/Console/ConsoleIoTest.php
Labels: defect

#14092 allow IdentifierExpression as argument in Function
  src/Database/FunctionsBuilder.php
  tests/TestCase/Database/FunctionsBuilderTest.php
Labels: defect

#14098 Autoload PHPUnit aliases in MockBuilder
  src/TestSuite/MockBuilder.php
Labels: testing

#14091 Fixed missing types in api docs
  src/Collection/CollectionInterface.php
  src/Console/CommandCollection.php
  src/Console/Exception/StopException.php
  src/Database/Query.php
  src/View/Form/ArrayContext.php
  src/View/Form/ContextInterface.php
  src/View/Form/EntityContext.php
  tests/TestCase/Console/CommandCollectionTest.php
Labels: documentation

#14104 Fixed indent of nested lists in docblocks
  src/I18n/Date.php
  src/I18n/FrozenDate.php
  src/I18n/FrozenTime.php
  src/I18n/Time.php
Labels: documentation
