Repository cakephp/cakephp, pull requests merged in 2020-12, with the labels that each got.

#15200 Rename $callback to $path for methods that take a column/path
  src/Collection/CollectionInterface.php
  src/Collection/CollectionTrait.php
  src/Collection/ExtractTrait.php
Labels: cleanup

#15209 Add cronjob for master
  .github/workflows/ci.yml
Labels: testing

#14864 4.next - Add support for receiving the query object in result formatter callables
  src/Datasource/QueryTrait.php
  src/ORM/Association.php
  tests/TestCase/ORM/QueryTest.php
Labels: enhancement

#15215 Add 'valueSeparator' option for find('list').
  src/ORM/Table.php
  tests/TestCase/ORM/TableTest.php
Labels: ORM, enhancement

#15222 Clean up spelling of nonexistent
  src/View/Form/EntityContext.php
  tests/TestCase/Auth/PasswordHasherFactoryTest.php
  tests/TestCase/Cache/CacheTest.php
  tests/TestCase/Command/CompletionCommandTest.php
  tests/TestCase/Command/RoutesCommandTest.php
  tests/TestCase/Command/SchemaCacheCommandsTest.php
  tests/TestCase/Controller/Component/PaginatorComponentTest.php
  tests/TestCase/Core/ConfigureTest.php
  tests/TestCase/Database/Schema/CollectionTest.php
  tests/TestCase/Datasource/FactoryLocatorTest.php
  tests/TestCase/Datasource/PaginatorTestTrait.php
  tests/TestCase/Error/DebuggerTest.php
  tests/TestCase/Filesystem/FolderTest.php
  tests/TestCase/Form/FormTest.php
  tests/TestCase/Http/BaseApplicationTest.php
  tests/TestCase/ORM/MarshallerTest.php
  tests/TestCase/ORM/QueryTest.php
  tests/TestCase/ORM/Rule/LinkConstraintTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/Routing/AssetTest.php
  tests/TestCase/Utility/HashTest.php
  tests/TestCase/Validation/ValidationRuleTest.php
  tests/TestCase/Validation/ValidationTest.php
  tests/TestCase/View/CellTest.php
  tests/TestCase/View/Form/EntityContextTest.php
  tests/TestCase/View/Helper/FlashHelperTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/Helper/HtmlHelperTest.php
  tests/TestCase/View/Helper/UrlHelperTest.php
  tests/TestCase/View/StringTemplateTest.php
  tests/TestCase/View/ViewBuilderTest.php
  tests/TestCase/View/ViewTest.php
Labels: cleanup

#15230 4.2 fix fixtures
  tests/Fixture/BinaryUuidItemsBinaryUuidTagsFixture.php
  tests/Fixture/BinaryUuidTagsFixture.php
  tests/TestCase/ORM/Association/BelongsToManyTest.php
Labels: testing

#15233 Fix type error.
  src/I18n/Package.php
  src/I18n/Translator.php
  tests/TestCase/I18n/PackageTest.php
Labels: defect, i18n

#15247 Dont operate on bool
  src/View/Helper/PaginatorHelper.php
Labels: defect

#15248 Make Router::routes() return a sorted routes list.
  src/Routing/RouteCollection.php
  tests/TestCase/Routing/Middleware/RoutingMiddlewareTest.php
  tests/TestCase/Routing/RouteBuilderTest.php
Labels: enhancement, routing

#15256 Fix API docs
  src/Database/Driver/Sqlite.php
  src/Database/Driver/Sqlserver.php
  src/Database/Expression/ComparisonExpression.php
  src/I18n/PackageLocator.php
  src/I18n/TranslatorRegistry.php
  src/Validation/Validation.php
  src/View/Form/ContextInterface.php
Labels: documentation

#15259 Fix up accessible docblock
  src/Datasource/EntityInterface.php
Labels: documentation
