Repository cakephp/cakephp, pull requests merged in 2020-06, with the labels that each got.

#14660 Fix up a few more deprecation links.
  src/Database/Type/DateTimeType.php
  src/Form/Form.php
Labels: documentation

#14682 Backport ascii validation to 3.next
  src/Validation/Validation.php
  src/Validation/Validator.php
  tests/TestCase/Validation/ValidationTest.php
  tests/TestCase/Validation/ValidatorTest.php
Labels: backport

#14691 Backport Allow disabling lenient IntlDateFormatter parsing to 3.next
  src/I18n/DateFormatTrait.php
  tests/TestCase/I18n/DateTest.php
  tests/TestCase/I18n/TimeTest.php
Labels: backport

#14708 Backport 4.next changes to 3.next
  src/Database/Expression/TupleComparison.php
  src/I18n/Time.php
  src/Mailer/TransportRegistry.php
  src/ORM/AssociationsNormalizerTrait.php
  src/ORM/Behavior/TimestampBehavior.php
  src/ORM/Behavior/TreeBehavior.php
  src/Utility/Xml.php
  src/Validation/ValidationRule.php
  src/Validation/ValidationSet.php
  src/Validation/ValidatorAwareTrait.php
  src/View/Helper/TextHelper.php
  src/View/ViewBlock.php
  src/View/Widget/WidgetInterface.php
  tests/TestCase/View/Helper/TextHelperTest.php
Labels: backport

#14714 Backport 4.next changes to 3.next
  src/Cache/CacheRegistry.php
  src/Console/HelperRegistry.php
  src/Console/TaskRegistry.php
  src/Controller/ComponentRegistry.php
  src/Core/ObjectRegistry.php
  src/Datasource/ConnectionRegistry.php
  src/Datasource/EntityInterface.php
  src/Datasource/EntityTrait.php
  src/Log/LogEngineRegistry.php
  src/ORM/BehaviorRegistry.php
  src/View/HelperRegistry.php
  tests/TestCase/ORM/EntityTest.php
Labels: backport

#14718 [2.x] Fix deprecated argument order in calls to implode()
  lib/Cake/Console/Command/CompletionShell.php
  lib/Cake/View/Helper/FormHelper.php
Labels: php7.4

#14731 Avoid use of call_user_func() and call_user_func_array().
  src/Cache/Cache.php
  src/Controller/Component/PaginatorComponent.php
  src/Controller/Component/SecurityComponent.php
  src/Error/Debugger.php
  src/Error/ExceptionRenderer.php
  src/Http/ServerRequest.php
  src/Mailer/Email.php
  src/ORM/Behavior/TranslateBehavior.php
  src/ORM/BehaviorRegistry.php
  src/Utility/Hash.php
  src/Utility/Xml.php
  src/View/Helper/NumberHelper.php
  src/View/Helper/TextHelper.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
Labels: optimization

#14735 Micro optimization.
  src/Database/Connection.php
Labels: optimization

#14734 Backport 4.x changes to 3.x
  src/I18n/functions.php
Labels: documentation

#14737 Fix path docs
  src/Controller/Component/FlashComponent.php
  src/View/View.php
  src/View/ViewBuilder.php
Labels: documentation

#14740 Abort atomic save if deletion of junction record fails.
  src/ORM/Association/BelongsToMany.php
  tests/TestCase/ORM/Rule/LinkConstraintTest.php
Labels: enhancement

#14751 Don't modify strings from binary MO files
  src/I18n/Parser/MoFileParser.php
  tests/TestCase/I18n/Parser/MoFileParserTest.php
  tests/TestCase/I18n/Parser/PoFileParserTest.php
  tests/test_app/resources/locales/en/default.po
  tests/test_app/resources/locales/rule_0_mo/core.mo
  tests/test_app/resources/locales/rule_0_po/core.po
Labels: i18n

#14748 Use phpunit appropriate methods in getMockForModel
  src/TestSuite/TestCase.php
  tests/TestCase/TestSuite/TestCaseTest.php
  tests/test_app/TestApp/Model/Table/SluggedPostsTable.php
Labels: enhancement

#14758 [3.x] Update Xcache URL
  .travis.yml
  composer.json
Labels: testing

#14754 3.x - Don't modify strings from binary MO files
  src/I18n/Parser/MoFileParser.php
  tests/TestCase/I18n/Parser/MoFileParserTest.php
  tests/TestCase/I18n/Parser/PoFileParserTest.php
  tests/test_app/TestApp/Locale/en/default.po
  tests/test_app/TestApp/Locale/rule_0_mo/core.mo
  tests/test_app/TestApp/Locale/rule_0_po/core.po
Labels: backport
