Repository cakephp/cakephp, pull requests merged in 2020-10, with the labels that each got.

#15003 Move warning about CollectionInterface::count() to top of docblock
  src/Collection/CollectionInterface.php
Labels: documentation

#14945 Add a dependency injection container
  composer.json
  src/Console/BaseCommand.php
  src/Console/CommandFactory.php
  src/Console/CommandRunner.php
  src/Controller/ControllerFactory.php
  src/Core/BasePlugin.php
  src/Core/Container.php
  src/Core/ContainerApplicationInterface.php
  src/Core/ContainerInterface.php
  src/Core/PluginInterface.php
  src/Core/ServiceConfig.php
  src/Error/ExceptionRenderer.php
  src/Http/BaseApplication.php
  tests/TestCase/Console/CommandFactoryTest.php
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Controller/ControllerFactoryTest.php
  tests/TestCase/Core/BasePluginTest.php
  tests/TestCase/Core/ServiceConfigTest.php
  tests/TestCase/Http/BaseApplicationTest.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
  tests/test_app/TestApp/Application.php
  tests/test_app/TestApp/Command/DependencyCommand.php
  tests/test_app/TestApp/Controller/DependenciesController.php
Labels: enhancement

#14998 Use exception code as http code for HttpException only
  src/Core/Exception/Exception.php
  src/Datasource/Exception/InvalidPrimaryKeyException.php
  src/Error/ExceptionRenderer.php
  src/Mailer/Exception/MissingActionException.php
  tests/TestCase/Error/ExceptionRendererTest.php
  tests/TestCase/ExceptionsTest.php
Labels: enhancement

#15005 Update Collection parameter names
  src/Collection/CollectionInterface.php
  src/Collection/CollectionTrait.php
Labels: cleanup

#15013 Update Connection parameter names
  src/Database/Connection.php
  src/Datasource/ConnectionInterface.php
Labels: cleanup

#15015 Allow Cake\ORM\Query type in the arguments of epilog()
  src/Database/Query.php
Labels: documentation

#15017 3.x: Port #15015
  src/Database/Query.php
Labels: backport

#15016 Update Driver parameter names
  src/Database/Connection.php
  src/Database/Driver.php
  src/Database/Driver/Sqlserver.php
  src/Database/DriverInterface.php
Labels: cleanup

#15022 Clarify version map
  README.md
Labels: documentation

#15019 Update ExpressionInterface parameter names
  src/Database/Expression/AggregateExpression.php
  src/Database/Expression/BetweenExpression.php
  src/Database/Expression/CaseExpression.php
  src/Database/Expression/CommonTableExpression.php
  src/Database/Expression/ComparisonExpression.php
  src/Database/Expression/FunctionExpression.php
  src/Database/Expression/IdentifierExpression.php
  src/Database/Expression/OrderByExpression.php
  src/Database/Expression/OrderClauseExpression.php
  src/Database/Expression/QueryExpression.php
  src/Database/Expression/TupleComparison.php
  src/Database/Expression/UnaryExpression.php
  src/Database/Expression/ValuesExpression.php
  src/Database/Expression/WindowExpression.php
  src/Database/ExpressionInterface.php
Labels: cleanup

#15010 Made a more accurate comment on Email sender methods
  src/Mailer/Message.php
Labels: hacktoberfest-accepted

#15011 Set default error code to 500 for HttpException only
  src/Controller/Exception/MissingActionException.php
  src/Core/Exception/Exception.php
  src/Datasource/Exception/PageOutOfBoundsException.php
  src/Datasource/Exception/RecordNotFoundException.php
  src/Error/ConsoleErrorHandler.php
  src/Http/Exception/HttpException.php
  src/Network/Exception/SocketException.php
  src/Utility/Exception/XmlException.php
  tests/TestCase/Error/ConsoleErrorHandlerTest.php
  tests/TestCase/ExceptionsTest.php
Labels: cleanup, enhancement

#15034 Deprecate Exception::responseHeader() in favor of HttpException
  src/Auth/BasicAuthenticate.php
  src/Core/Exception/Exception.php
  src/Error/ExceptionRenderer.php
  src/Http/Exception/HttpException.php
  src/Http/Middleware/CsrfProtectionMiddleware.php
  src/Http/ServerRequest.php
  tests/TestCase/Auth/BasicAuthenticateTest.php
  tests/TestCase/Auth/DigestAuthenticateTest.php
  tests/TestCase/Error/ExceptionRendererTest.php
  tests/TestCase/Http/Middleware/CsrfProtectionMiddlewareTest.php
  tests/TestCase/Http/ServerRequestTest.php
Labels: cleanup

#15041 Remove lies from docblock.
  src/Console/CommandRunner.php
  src/Http/Server.php
Labels: documentation

#14943 Validation last=true regressions
  src/Validation/Validator.php
  tests/TestCase/Validation/ValidatorTest.php
Labels: defect

#15040 Add StringExpression with collation support
  src/Database/Driver/Postgres.php
  src/Database/Expression/StringExpression.php
  tests/TestCase/Database/Expression/StringExpressionTest.php
  tests/TestCase/Database/QueryTest.php
Labels: enhancement

#15051 Made a more accurate comment on Email sender methods
  src/Mailer/Email.php
Labels: documentation

#15064 Query cleanup
  src/Database/Query.php
  src/Datasource/QueryTrait.php
  src/ORM/Query.php
Labels: cleanup

#15052 Samesite default value
  src/Http/Middleware/CsrfProtectionMiddleware.php
  tests/TestCase/Http/Middleware/CsrfProtectionMiddlewareTest.php
Labels: defect

#15074 Make sure debug as string doesn't throw error.
  src/Error/BaseErrorHandler.php
  src/View/Helper/FormHelper.php
Labels: defect

#15078 Improve wording, grammar, punctuation etc.
  .github/CONTRIBUTING.md
  src/Cache/README.md
  src/Console/README.md
  src/Core/README.md
  src/Datasource/README.md
  src/Filesystem/README.md
  src/Http/README.md
  src/Log/README.md
  src/ORM/README.md
Labels: documentation

#15077 children, not childs
  src/Utility/Xml.php
Labels: documentation

#15069 Name acronyms correctly
  phpunit.xml.dist
  src/Cache/Cache.php
  src/Cache/Engine/MemcachedEngine.php
  src/Cache/Engine/RedisEngine.php
  src/Console/ConsoleInputOption.php
  src/Console/ConsoleOptionParser.php
  src/Console/HelpFormatter.php
  src/Console/Shell.php
  src/Console/ShellDispatcher.php
  src/Controller/Component/RequestHandlerComponent.php
  src/Core/functions.php
  src/Database/Driver/Mysql.php
  src/Database/Statement/MysqlStatement.php
  src/Database/Type/JsonType.php
  src/Datasource/EntityTrait.php
  src/Error/Debugger.php
  src/Http/Client/Response.php
  src/Http/Cookie/Cookie.php
  src/Http/Middleware/BodyParserMiddleware.php
  src/Http/Session.php
  src/I18n/DateFormatTrait.php
  src/I18n/I18nDateTimeInterface.php
  src/Mailer/Message.php
  src/TestSuite/ConsoleIntegrationTestTrait.php
  src/Utility/CookieCryptTrait.php
  src/Validation/Validation.php
  src/View/Helper/FormHelper.php
  src/View/JsonView.php
  src/View/XmlView.php
  tests/TestCase/Collection/CollectionTest.php
  tests/TestCase/Console/HelpFormatterTest.php
  tests/TestCase/Controller/Component/AuthComponentTest.php
  tests/TestCase/Controller/Component/RequestHandlerComponentTest.php
  tests/TestCase/Core/Configure/Engine/JsonConfigTest.php
  tests/TestCase/Database/Driver/MysqlTest.php
  tests/TestCase/Database/QueryTest.php
  tests/TestCase/Database/Schema/MysqlSchemaTest.php
  tests/TestCase/Database/Schema/PostgresSchemaTest.php
  tests/TestCase/Database/Type/JsonTypeTest.php
  tests/TestCase/Datasource/ResultSetDecoratorTest.php
  tests/TestCase/Error/ExceptionRendererTest.php
  tests/TestCase/Http/Client/ResponseTest.php
  tests/TestCase/Http/ServerRequestTest.php
  tests/TestCase/I18n/DateTest.php
  tests/TestCase/I18n/TimeTest.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/ORM/ResultSetTest.php
  tests/TestCase/Utility/XmlTest.php
  tests/TestCase/Validation/ValidatorTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/test_app/Plugin/TestTheme/webroot/js/one/theme_one.js
  tests/test_app/Plugin/TestTheme/webroot/js/theme.js
  tests/test_app/TestApp/Controller/RequestHandlerTestController.php
Labels: documentation

#15079 Update db and generator parameter names
  psalm-baseline.xml
  src/Database/Connection.php
  src/Database/ConstraintsInterface.php
  src/Database/Query.php
  src/Database/QueryCompiler.php
  src/Datasource/FixtureInterface.php
  src/ORM/Query.php
  src/TestSuite/Fixture/FixtureManager.php
  src/TestSuite/Fixture/TestFixture.php
  tests/Fixture/OtherArticlesFixture.php
Labels: cleanup

#15081 Change _runOperation to runPerFixture
  src/TestSuite/Fixture/FixtureManager.php
  tests/TestCase/TestSuite/FixtureManagerTest.php
Labels: cleanup

#15089 Forward port support of UTF-8 encoding for pj()
  src/Core/functions.php
Labels: enhancement

#15093 Move DDL statements out of transactions
  src/TestSuite/Fixture/FixtureManager.php
Labels: cleanup

#15100 Fix regression in object value comparison when marshalling entity.
  src/ORM/Marshaller.php
  tests/TestCase/ORM/MarshallerTest.php
Labels: ORM, defect
