Repository cakephp/cakephp, pull requests merged in 2020-05, with the labels that each got.

#14523 Improve error message for EmailTrait::MailContains
  src/TestSuite/Constraint/Email/MailContains.php
  src/TestSuite/Constraint/Email/MailContainsText.php
  tests/TestCase/TestSuite/EmailTraitTest.php
Labels: enhancement

#14515 Improve ErrorLogger for PHP errors
  src/Error/BaseErrorHandler.php
  src/Error/ErrorLogger.php
  src/Error/ErrorLoggerInterface.php
  tests/TestCase/Error/ErrorHandlerTest.php
Labels: enhancement, errorhandler

#14524 Adjust interface contracts as per implementation.
  src/Database/Query.php
  src/Datasource/QueryInterface.php
Labels: documentation

#14526 Backport PHP74 fixes
  src/I18n/Parser/PoFileParser.php
Labels: compatibility

#14529 Use FQCN imports.
  src/Database/Driver/Postgres.php
  src/Database/Driver/SqlDialectTrait.php
  src/Database/Driver/Sqlite.php
  src/Database/Driver/Sqlserver.php
Labels: cleanup

#14535 Fix test failure on MySQL 8
  tests/TestCase/Database/QueryTest.php
Labels: testing

#14533 Simplify Debugger::getType()
  src/Error/Debugger.php
  tests/TestCase/Error/DebuggerTest.php
Labels: cleanup

#14541 Cleanup MiddlewareDispatcher.
  src/TestSuite/MiddlewareDispatcher.php
Labels: cleanup

#14543 Update Filesystem internal description
  src/Filesystem/Filesystem.php
Labels: documentation

#14559 Fix false being set in form inputs
  src/View/Widget/BasicWidget.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: defect

#14551 4.1 - Added connection name to QueryLogger log entries
  src/Database/Connection.php
  src/Database/Log/QueryLogger.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Database/Log/LoggingStatementTest.php
  tests/TestCase/Database/Log/QueryLoggerTest.php
Labels: enhancement

#14562 Improve error message for EmailTrait::MailContains
  src/TestSuite/Constraint/Email/MailContains.php
  src/TestSuite/Constraint/Email/MailContainsHtml.php
  src/TestSuite/Constraint/Email/MailContainsText.php
  tests/TestCase/TestSuite/EmailTraitTest.php
Labels: enhancement

#14539 4.1 - Added exception for FunctionsBuilder::cast() when parameter is missing
  src/Database/FunctionsBuilder.php
  tests/TestCase/Database/FunctionsBuilderTest.php
Labels: defect

#14536 4.1 - Added named window expression support
  src/Database/Expression/AggregateExpression.php
  src/Database/Expression/WindowExpression.php
  src/Database/Query.php
  src/Database/QueryCompiler.php
  src/Database/SqlserverCompiler.php
  tests/TestCase/Database/Expression/AggregateExpressionTest.php
  tests/TestCase/Database/Expression/WindowExpressionTest.php
  tests/TestCase/Database/WindowQueryTests.php
Labels: enhancement

#14555 Throw exception when contain() in query builder for matching
  src/ORM/Association.php
  tests/TestCase/ORM/QueryTest.php
Labels: defect

#14563 Add iterable type into generator doc.
  src/Core/PluginCollection.php
Labels: documentation

#14575 Fix form-urlencoded PUT bodies not working in tests
  src/Http/ServerRequestFactory.php
  src/TestSuite/IntegrationTestTrait.php
  src/TestSuite/MiddlewareDispatcher.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
Labels: testing

#14576 Add Shells interactive false back for Commands
  src/Console/BaseCommand.php
  src/Console/ConsoleIo.php
  tests/TestCase/Console/CommandTest.php
  tests/test_app/TestApp/Command/NonInteractiveCommand.php
Labels: enhancement

#14570 4.next - Explicit list of supported valueSources
  src/View/Helper/FormHelper.php
Labels: enhancement

#14574 Consolidate logging formatting for query logging
  src/Database/Log/LoggedQuery.php
  src/Database/Log/QueryLogger.php
  tests/TestCase/Database/Log/LoggedQueryTest.php
  tests/TestCase/Database/Log/LoggingStatementTest.php
  tests/TestCase/Database/Log/QueryLoggerTest.php
Labels: database, log

#14578 Clean up tests using PHPStan level 1.
  src/Mailer/Email.php
  tests/TestCase/BasicsTest.php
  tests/TestCase/Collection/CollectionTest.php
  tests/TestCase/Command/PluginAssetsCommandsTest.php
  tests/TestCase/Command/SchemaCacheCommandsTest.php
  tests/TestCase/Command/ServerCommandTest.php
  tests/TestCase/Console/CommandCollectionTest.php
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Console/ConsoleInputTest.php
  tests/TestCase/Console/HelperRegistryTest.php
  tests/TestCase/Console/TaskRegistryTest.php
  tests/TestCase/Controller/Component/AuthComponentTest.php
  tests/TestCase/Core/FunctionsTest.php
  tests/TestCase/Database/Driver/SqlserverTest.php
  tests/TestCase/Database/Expression/QueryExpressionTest.php
  tests/TestCase/Http/BaseApplicationTest.php
  tests/TestCase/Http/ServerRequestTest.php
  tests/TestCase/Http/ServerTest.php
  tests/TestCase/I18n/Parser/PoFileParserTest.php
  tests/TestCase/Mailer/Transport/MailTransportTest.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/ORM/QueryTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/TestSuite/FixtureManagerTest.php
  tests/TestCase/TestSuite/TestEmailTransportTest.php
  tests/TestCase/Utility/TextTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/ViewVarsTraitTest.php
Labels: testing

#14590 Allow specifying "SameSite" attribute for CSRF protection cookie.
  src/Http/Middleware/CsrfProtectionMiddleware.php
  tests/TestCase/Http/Middleware/CsrfProtectionMiddlewareTest.php
Labels: enhancement

#14272 4.next Allows to set single element inside form data
  src/Form/Form.php
  tests/TestCase/Form/FormTest.php
Labels: enhancement

#14593 current evaluates to false on empty array
  src/Database/FunctionsBuilder.php
  tests/TestCase/Database/FunctionsBuilderTest.php
Labels: defect

#14596 Allow passing "locale" as find option.
  src/ORM/Behavior/Translate/EavStrategy.php
  src/ORM/Behavior/Translate/ShadowTableStrategy.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
Labels: ORM, enhancement

#14600 Backport return empty strings by translation functions from 4.x to 3.x
  src/I18n/functions.php
Labels: backport

#14601 Fixed invalid tags
  src/Validation/Validation.php
  src/View/SerializedView.php
Labels: documentation

#14602 Refactor deprecations to clickable links in IDE.
  src/Cache/Cache.php
  src/Console/Command.php
  src/Controller/Component/SecurityComponent.php
  src/Database/Expression/QueryExpression.php
  src/Database/Schema/TableSchema.php
  src/Datasource/EntityTrait.php
  src/Http/Cookie/Cookie.php
  src/Http/Middleware/CsrfProtectionMiddleware.php
  src/I18n/Number.php
  src/Mailer/Email.php
  src/Mailer/Mailer.php
  src/ORM/Locator/TableLocator.php
  src/ORM/TableRegistry.php
  src/TestSuite/ConsoleIntegrationTestCase.php
  src/TestSuite/IntegrationTestCase.php
  src/Validation/Validation.php
  src/Validation/Validator.php
  src/View/Form/ArrayContext.php
  src/View/Form/EntityContext.php
  src/View/Form/FormContext.php
  src/View/Form/NullContext.php
Labels: documentation

#14607 Fix CS: Use single quotes where applicable.
  src/Collection/CollectionTrait.php
  src/Command/CompletionCommand.php
  src/Command/I18nExtractCommand.php
  src/Console/CommandRunner.php
  src/Controller/ControllerFactory.php
  src/Database/Dialect/SqliteDialectTrait.php
  src/Database/Type/BinaryUuidType.php
  src/Filesystem/File.php
  src/Http/Cookie/CookieCollection.php
  src/I18n/Date.php
  src/I18n/FrozenDate.php
  src/ORM/Table.php
  src/View/Helper/FormHelper.php
  templates/Error/missing_action.php
  templates/Error/missing_behavior.php
  templates/Error/missing_component.php
  templates/Error/missing_controller.php
  templates/Error/missing_datasource_config.php
  templates/Error/missing_helper.php
  templates/Error/missing_route.php
  templates/Error/missing_view.php
  templates/element/auto_table_warning.php
  templates/element/exception_stack_trace.php
  templates/element/exception_stack_trace_nav.php
  templates/element/plugin_class_error.php
  tests/TestCase/Command/CompletionCommandTest.php
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Console/ConsoleOptionParserTest.php
  tests/TestCase/ExceptionsTest.php
  tests/TestCase/Filesystem/FolderTest.php
  tests/TestCase/Http/Client/Adapter/StreamTest.php
  tests/TestCase/Http/Cookie/CookieTest.php
  tests/TestCase/Http/ServerTest.php
  tests/TestCase/I18n/Parser/PoFileParserTest.php
  tests/TestCase/Mailer/Transport/SmtpTransportTest.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorShadowTableTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/Routing/Route/RouteTest.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
  tests/TestCase/Utility/XmlTest.php
  tests/TestCase/View/CellTest.php
  tests/TestCase/View/Helper/HtmlHelperTest.php
  tests/TestCase/View/StringTemplateTest.php
  tests/TestCase/View/ViewTest.php
  tests/test_app/TestApp/Middleware/ThrowsExceptionMiddleware.php
Labels: code-style

#14610 Add missing @var tags to constants
  src/Cache/CacheEngine.php
  src/Controller/Component/AuthComponent.php
  src/Controller/Component/FormProtectionComponent.php
  src/Controller/Component/SecurityComponent.php
  src/Core/PluginInterface.php
  src/Database/Expression/UnaryExpression.php
  src/Database/Schema/SqlserverSchema.php
  src/Http/Cookie/CookieInterface.php
  src/Http/Response.php
  src/I18n/Number.php
  src/I18n/Translator.php
  src/Routing/Middleware/RoutingMiddleware.php
  src/Utility/Crypto/OpenSsl.php
  src/Validation/Validator.php
Labels: documentation

#14609 4.1 - Grouped query tests under QueryTests/
  tests/TestCase/Database/QueryTests/CommonTableExpressionQueryTests.php
  tests/TestCase/Database/QueryTests/WindowQueryTests.php
Labels: cleanup

#14622 Generate truly random uuid() for Cake 2.x
  lib/Cake/Utility/CakeText.php
Labels: defect, security

#14625 Backport addFixture() for 3.9+
  src/TestSuite/TestCase.php
  tests/TestCase/TestSuite/FixtureManagerTest.php
Labels: enhancement

#14617 Allow chainable fixture adding in TestCase
  src/TestSuite/TestCase.php
  tests/TestCase/TestSuite/FixtureManagerTest.php
Labels: enhancement

#14635 Rename SchemaCacheCommandsTest
  tests/TestCase/Command/SchemaCacheCommandsTest.php
Labels: backport

#14641 3.8 - Backport #14639
  src/Mailer/Transport/SmtpTransport.php
  tests/TestCase/Mailer/Transport/SmtpTransportTest.php
Labels: backport

#14629 4.1 datasource locatorinterface
  src/Datasource/FactoryLocator.php
  src/Datasource/Locator/AbstractLocator.php
  src/Datasource/Locator/LocatorInterface.php
  src/Datasource/ModelAwareTrait.php
  src/ORM/Locator/LocatorAwareTrait.php
  src/ORM/Locator/LocatorInterface.php
  src/ORM/Locator/TableLocator.php
  src/ORM/TableRegistry.php
  tests/TestCase/Datasource/FactoryLocatorTest.php
  tests/TestCase/Datasource/ModelAwareTraitTest.php
Labels: ORM, enhancement

#14646 4.next - Add closure support to `Query::orderAsc()` and `Query::orderDesc()`.
  src/Database/Query.php
  tests/TestCase/Database/QueryTest.php
Labels: enhancement

#14647 Add defaulting and *orFail() to Session.
  src/Core/Configure.php
  src/Http/Session.php
  tests/TestCase/Http/SessionTest.php
Labels: RFC

#14649 3.next - Add callable support to `Query::orderAsc()` and `Query::orderDesc()`.
  src/Database/Query.php
  tests/TestCase/Database/QueryTest.php
Labels: backport
