Repository cakephp/cakephp, pull requests merged in 2020-07, with the labels that each got.

#14765 Replaced assertStringStartsWithSql with assertRegExpSql
  src/TestSuite/TestCase.php
  tests/TestCase/Database/QueryTests/CommonTableExpressionQueryTests.php
Labels: cleanup

#14767 3.x - Changed CollectionTrait::shuffle() to return all elements in collection.
  src/Collection/CollectionInterface.php
  src/Collection/CollectionTrait.php
  tests/TestCase/Collection/CollectionTest.php
Labels: backport

#14774 Cast property names in debug node tree
  src/Error/Debugger.php
  tests/TestCase/Error/DebuggerTest.php
Labels: defect

#14777 Deprecate method that throws deprecation warning along the way.
  src/View/Helper/NumberHelper.php
Labels: deprecations

#14778 Deprecate method that throws deprecation along the way
  src/View/Helper/NumberHelper.php
Labels: deprecations

#14782 Fix a bug of Validation::date()
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: defect

#14817 check datatype for localizedTime cakephp#14800
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: defect

#14818 fix Validation::custom function arguments cakephp#14816
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: defect

#14835 Fix form protection token generation with a "false" value.
  src/View/Helper/FormHelper.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: defect

#14832 Fix auto loading of model when ModelAwareTrait::modelClass is set to FQCN.
  src/Controller/Controller.php
  tests/TestCase/Controller/ControllerTest.php
  tests/test_app/TestApp/Controller/ArticlesController.php
Labels: defect

#14825 Add session based CSRF token middleware
  src/Http/Middleware/SessionCsrfProtectionMiddleware.php
  tests/TestCase/Http/Middleware/SessionCsrfProtectionMiddlewareTest.php
Labels: enhancement, http

#14842 Use client-side buffered cursor type
  psalm.xml
  src/Database/Driver/Sqlserver.php
  tests/TestCase/ORM/QueryTest.php
Labels: sqlserver

#14850 Make milliseconds loggable
  src/Log/Engine/BaseLog.php
Labels: log

#14860 Remove unneeded method call.
  src/Core/PluginCollection.php
Labels: cleanup
