Repository cakephp/cakephp, pull requests merged in 2020-02, with the labels that each got.

#14247 Bring docblock of dateAdd() in line with 4.x
  src/Database/FunctionsBuilder.php
Labels: documentation

#14251 Add getAccessible()
  src/Datasource/EntityInterface.php
  src/Datasource/EntityTrait.php
  tests/TestCase/ORM/EntityTest.php
Labels: enhancement

#14255 Update table docs.
  src/ORM/Table.php
Labels: documentation

#14261 Add methods to support editor links
  phpstan-baseline.neon
  src/Error/Debugger.php
  tests/TestCase/Error/DebuggerTest.php
Labels: enhancement

#14280 Fix occasional failure on Postgres due to different records order.
  tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
Labels: testing

#14279 Don't try to update counter cache when foreign key value is null.
  src/ORM/Behavior/CounterCacheBehavior.php
  tests/TestCase/ORM/Behavior/CounterCacheBehaviorTest.php
Labels: ORM

#14283 Fix EagerLoader loading optional association with leftJoinWith and contain
  src/ORM/EagerLoader.php
  tests/TestCase/ORM/QueryTest.php
Labels: ORM

#14288 Notice when using command i18n extract [4.0]
  src/Command/I18nExtractCommand.php
  tests/TestCase/Command/CacheCommandsTest.php
  tests/TestCase/Command/CompletionCommandTest.php
  tests/TestCase/Command/I18nCommandTest.php
  tests/TestCase/Command/I18nExtractCommandTest.php
  tests/TestCase/Command/PluginLoadCommandTest.php
  tests/TestCase/Command/RoutesCommandTest.php
  tests/TestCase/TestSuite/ConsoleIntegrationTestTraitTest.php
Labels: defect

#14289 4.1 - Clean up ServerRequest tests
  tests/TestCase/Http/ServerRequestFactoryTest.php
  tests/TestCase/Http/ServerRequestTest.php
Labels: cleanup

#14256 Issue #14254 - accounting for human input in decimal validation and w…
  src/Validation/Validation.php
Labels: enhancement, validation

#14299 Fix examples around prefix casing
  src/Routing/RouteBuilder.php
  src/Routing/Router.php
  tests/TestCase/Routing/RouteBuilderTest.php
Labels: documentation

#14301 Better typehinting for IDE discoverability in tests.
  tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
  tests/TestCase/Routing/RouterTest.php
Labels: documentation

#14308 Improve error message when driver cannot connect to database.
  src/Database/Connection.php
  src/Database/Driver.php
  src/Database/DriverInterface.php
  src/Database/Exception/MissingConnectionException.php
  templates/Error/missing_connection.php
  tests/TestCase/Database/ConnectionTest.php
Labels: database

#14310 Remove redundant instanceof check.
  src/ORM/Association/HasMany.php
Labels: cleanup

#14320 Add slug() to TextHelper
  src/View/Helper/TextHelper.php
  tests/TestCase/Utility/TextTest.php
  tests/TestCase/View/Helper/TextHelperTest.php
Labels: enhancement

#14332 Adding two examples of how to use the accessibleFields option
  src/ORM/Marshaller.php
  src/ORM/Table.php
Labels: documentation
