Repository cakephp/cakephp, pull requests merged in 2020-01, with the labels that each got.

#14079 4.1 - Added AggregateExpression for aggregate functions
  src/Database/Expression/AggregateExpression.php
  src/Database/FunctionsBuilder.php
  tests/TestCase/Database/Expression/AggregateExpressionTest.php
  tests/TestCase/Database/Expression/FunctionExpressionTest.php
  tests/TestCase/Database/FunctionsBuilderTest.php
Labels: database

#14110 Fix path output for CLI.
  src/Console/Command/HelpCommand.php
Labels: cleanup

#14081 4.1 - Renamed database schema dialect classes
  src/Database/Dialect/MysqlDialectTrait.php
  src/Database/Dialect/PostgresDialectTrait.php
  src/Database/Dialect/SqliteDialectTrait.php
  src/Database/Dialect/SqlserverDialectTrait.php
  src/Database/Driver.php
  src/Database/DriverInterface.php
  src/Database/Schema/BaseSchema.php
  src/Database/Schema/Collection.php
  src/Database/Schema/MysqlSchema.php
  src/Database/Schema/MysqlSchemaDialect.php
  src/Database/Schema/PostgresSchema.php
  src/Database/Schema/PostgresSchemaDialect.php
  src/Database/Schema/SchemaDialect.php
  src/Database/Schema/SqliteSchema.php
  src/Database/Schema/SqliteSchemaDialect.php
  src/Database/Schema/SqlserverSchema.php
  src/Database/Schema/SqlserverSchemaDialect.php
  tests/TestCase/Database/Schema/MysqlSchemaTest.php
  tests/TestCase/Database/Schema/PostgresSchemaTest.php
  tests/TestCase/Database/Schema/SqliteSchemaTest.php
  tests/TestCase/Database/Schema/SqlserverSchemaTest.php
Labels: database, enhancement

#14111 Moved schemaDialect() from driver dialect traits to drivers
  src/Database/Dialect/MysqlDialectTrait.php
  src/Database/Dialect/PostgresDialectTrait.php
  src/Database/Dialect/SqliteDialectTrait.php
  src/Database/Dialect/SqlserverDialectTrait.php
  src/Database/Driver/Mysql.php
  src/Database/Driver/Postgres.php
  src/Database/Driver/Sqlite.php
  src/Database/Driver/Sqlserver.php
Labels: database

#14112 Remove more un-necessary mocks.
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/ORM/Association/BelongsToTest.php
Labels: optimization

#14113 4.1 - Merged driver dialect traits with drivers
  src/Database/Dialect/MysqlDialectTrait.php
  src/Database/Dialect/PostgresDialectTrait.php
  src/Database/Dialect/SqliteDialectTrait.php
  src/Database/Dialect/SqlserverDialectTrait.php
  src/Database/Driver/Mysql.php
  src/Database/Driver/Postgres.php
  src/Database/Driver/SqlDialectTrait.php
  src/Database/Driver/Sqlite.php
  src/Database/Driver/Sqlserver.php
  src/Database/Driver/TupleComparisonTranslatorTrait.php
  src/Database/SqlDialectTrait.php
Labels: cleanup, database

#14119 Fix log write for numeric string key
  src/Log/Log.php
Labels: defect

#14121 Added 4.x backport for Client/Response->isSuccess() and tests.
  src/Http/Client/Response.php
  tests/TestCase/Http/Client/ResponseTest.php
Labels: enhancement

#14117 4.0: Fix config path to be normalized
  src/Http/BaseApplication.php
Labels: enhancement

#14120 4.0: Fix numeric string keys to work for log engines.
  src/Core/ObjectRegistry.php
  src/Core/StaticConfigTrait.php
  tests/TestCase/Log/LogTest.php
Labels: defect

#14122 Added 4.x backport for CspMiddleware and tests.
  composer.json
  src/Http/Middleware/CspMiddleware.php
  tests/TestCase/Http/Middleware/CspMiddlewareTest.php
Labels: enhancement

#14123 Fix numeric string keys to work for cache and configure.
  src/Cache/Cache.php
  src/Core/Configure.php
  tests/TestCase/Auth/ControllerAuthorizeTest.php
  tests/TestCase/Cache/CacheTest.php
  tests/TestCase/Collection/Iterator/FilterIteratorTest.php
  tests/TestCase/Collection/Iterator/ReplaceIteratorTest.php
  tests/TestCase/Core/ConfigureTest.php
Labels: defect

#14086 Validate table schema against max alias length
  src/Database/Driver.php
  src/Database/Driver/Mysql.php
  src/Database/Driver/Postgres.php
  src/Database/Driver/Sqlserver.php
  src/Database/DriverInterface.php
  src/ORM/Table.php
  tests/TestCase/ORM/TableTest.php
Labels: ORM, postgres

#14126 [4.x - cakephp/http] - add composer/ca-bundle
  composer.json
  src/Http/composer.json
Labels: dependencies, http

#14133 Only try to clean entities
  src/ORM/Association.php
Labels: defect

#14128 Improve how debug() handles cyclic references
  src/Error/Debugger.php
  src/Error/DumpContext.php
  tests/TestCase/Error/DebuggerTest.php
Labels: enhancement

#14145 4.0: Fix element cache key generation
  src/View/View.php
  tests/TestCase/View/ViewTest.php
  tests/test_app/templates/element/subfolder/test_element.php
Labels: defect

#14149 Fix docblocks around bool false.
  src/Controller/Component/AuthComponent.php
  src/Filesystem/File.php
  src/Mailer/Transport/SmtpTransport.php
  src/ORM/Table.php
  src/View/Helper/PaginatorHelper.php
Labels: documentation

#14156 Split Form::schema() into getter and setter
  src/Form/Form.php
  src/View/Form/FormContext.php
  tests/TestCase/Form/FormTest.php
  tests/TestCase/View/Form/FormContextTest.php
Labels: deprecations

#14170 Correct & clarify length parameter of File::read()
  src/Filesystem/File.php
Labels: documentation, enhancement

#14168 Fix type error in authenticator with null passwords
  src/Auth/BaseAuthenticate.php
  tests/TestCase/Auth/DigestAuthenticateTest.php
  tests/TestCase/Auth/FormAuthenticateTest.php
  tests/test_app/TestApp/Auth/CallCounterPasswordHasher.php
Labels: defect

#14180 Fix bug with bool values.
  src/Mailer/Message.php
Labels: defect

#14173 [3.x] Skip unchanged files when extracting translation strings
  src/Shell/Task/ExtractTask.php
Labels: console, enhancement, i18n

#14183 Add more coverage
  phpunit.xml.dist
  src/Core/ClassLoader.php
  src/Filesystem/File.php
  tests/TestCase/Command/CacheCommandsTest.php
  tests/TestCase/Command/I18nExtractCommandTest.php
  tests/TestCase/Error/Middleware/ErrorHandlerMiddlewareTest.php
  tests/TestCase/Filesystem/FileTest.php
Labels: testing

#14164 4.next - Begin decoupling variable dumping and formatting
  src/Error/Debug/ArrayItemNode.php
  src/Error/Debug/ArrayNode.php
  src/Error/Debug/ClassNode.php
  src/Error/Debug/DebugContext.php
  src/Error/Debug/NodeInterface.php
  src/Error/Debug/PropertyNode.php
  src/Error/Debug/ReferenceNode.php
  src/Error/Debug/ScalarNode.php
  src/Error/Debug/SpecialNode.php
  src/Error/Debug/TextFormatter.php
  src/Error/Debugger.php
  tests/TestCase/Error/DebuggerTest.php
Labels: enhancement

#14190 Add copy button
  templates/layout/dev_error.php
Labels: enhancement

#14195 Always use / in fallback layout title
  src/View/View.php
Labels: view

#14181 Fix Notice Error: Trying to access array offset on value of type null
  src/View/Helper/UrlHelper.php
Labels: compatibility, php7.4
