Repository cakephp/cakephp, pull requests merged in 2020-08, with the labels that each got.

#14866 Use env key matching interning array key.
  .appveyor.yml
  .github/workflows/ci.yml
  .travis.yml
  phpunit.xml.dist
  tests/bootstrap.php
Labels: testing

#14858 Clean up UUID fixture names
  src/Console/CommandCollection.php
  src/Console/ConsoleOptionParser.php
  src/Http/Client/Adapter/Curl.php
  src/Log/Engine/BaseLog.php
  src/ORM/Behavior/Translate/ShadowTableStrategy.php
  src/ORM/Table.php
  tests/Fixture/BinaryUuidItemsFixture.php
  tests/Fixture/UuidItemsFixture.php
  tests/Fixture/UuidportfoliosFixture.php
  tests/TestCase/Http/Client/Adapter/CurlTest.php
  tests/TestCase/ORM/TableUuidTest.php
Labels: testing

#14877 Fix SELECT queries with zero matching rows not being logged.
  src/Database/Log/LoggingStatement.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/ORM/ResultSetTest.php
Labels: defect

#14882 Make components projected on core level.
  src/Controller/Component.php
  src/Controller/Component/AuthComponent.php
  src/Core/ObjectRegistry.php
  tests/test_app/Plugin/TestPlugin/src/Controller/Component/PluginsComponent.php
  tests/test_app/Plugin/TestPlugin/src/Controller/Component/TestPluginComponent.php
  tests/test_app/TestApp/Controller/Component/AppleComponent.php
  tests/test_app/TestApp/Controller/Component/ConfiguredComponent.php
  tests/test_app/TestApp/Controller/Component/MutuallyReferencingOneComponent.php
  tests/test_app/TestApp/Controller/Component/MutuallyReferencingTwoComponent.php
  tests/test_app/TestApp/Controller/Component/OrangeComponent.php
  tests/test_app/TestApp/Controller/Component/ParamTestComponent.php
  tests/test_app/TestApp/Controller/Component/SomethingWithFlashComponent.php
  tests/test_app/TestApp/Controller/PaginatorTestController.php
Labels: cleanup

#14887 Fix null exception for special abstract table case
  src/ORM/Table.php
Labels: defect

#14895 Tests for url and pagination first/last
  tests/TestCase/View/Helper/PaginatorHelperTest.php
Labels: testing

#14906 3.x - Fix output buffers not being closed when the view triggers an exception.
  src/View/View.php
  tests/TestCase/View/ViewTest.php
  tests/test_app/TestApp/Template/Element/exception_with_open_buffers.ctp
Labels: backport

#14905 Make phpunit methods protected as per docs
  src/TestSuite/TestCase.php
Labels: cleanup

#14912 Rename getTable() to table() to remove naming collision.
  src/ORM/Behavior.php
  src/ORM/Behavior/TimestampBehavior.php
  tests/TestCase/ORM/Behavior/TreeBehaviorTest.php
  tests/TestCase/ORM/BehaviorTest.php
Labels: deprecations, enhancement

#14918 Keep all components annotated, even if deprecated.
  src/Controller/Controller.php
Labels: documentation

#14908 Make Route normalize HTTP method conditions
  src/Routing/Route/Route.php
  tests/TestCase/Routing/Route/RouteTest.php
  tests/TestCase/Routing/RouteBuilderTest.php
Labels: routing

#14936 Fix tmpdir path
  src/Log/Engine/FileLog.php
Labels: defect

#14940 Bugfix table cells
  src/View/Helper/HtmlHelper.php
  tests/TestCase/View/Helper/HtmlHelperTest.php
Labels: defect

#14947 Fix UUID warning for invalid ones.
  src/Database/Type/BinaryUuidType.php
  tests/TestCase/Database/Type/BinaryUuidTypeTest.php
Labels: defect
