Repository cakephp/cakephp, pull requests merged in 2020-09, with the labels that each got.

#14950 Fix generation of alias when using FQCN with TableLocator::get().
  .github/workflows/ci.yml
  src/ORM/Behavior/Translate/ShadowTableStrategy.php
  src/ORM/Locator/TableLocator.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
  tests/TestCase/ORM/Locator/TableLocatorTest.php
Labels: defect

#14934 Undeprecate class
  src/ORM/TableRegistry.php
Labels: deprecations

#14964 Fix HasMany not applying closure conditions during unlink
  src/ORM/Association/HasMany.php
  tests/TestCase/ORM/Association/HasManyTest.php
Labels: ORM

#14963 Allow TimeType to marshal H:i format
  src/Database/Type/TimeType.php
  tests/TestCase/Database/Type/TimeTypeTest.php
Labels: database, enhancement

#14969 Restrict Validation::time() so it requires minutes not just hours
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: enhancement, validation

#14914 Fix (some) response deprecations
  src/Controller/Component/RequestHandlerComponent.php
  src/Http/Client/Response.php
  src/Http/Response.php
  src/Utility/Xml.php
Labels: deprecations

#14967 Fixtures not truncated when both $import and $fields aren't set
  src/TestSuite/Fixture/TestFixture.php
  tests/TestCase/TestSuite/TestFixtureTest.php
Labels: defect

#14986 Throw an exception when wrong cache config detected
  src/Cache/Engine/MemcachedEngine.php
  tests/TestCase/Cache/Engine/MemcachedEngineTest.php
Labels: cache, defect

#14997 Return all possible form context attributes.
  src/View/Form/ArrayContext.php
  src/View/Form/ContextInterface.php
  src/View/Form/EntityContext.php
  src/View/Form/FormContext.php
  tests/TestCase/View/Form/EntityContextTest.php
  tests/TestCase/View/Form/FormContextTest.php
Labels: enhancement

#15000 Add gitattributes php diff
  .gitattributes
Labels: documentation
