Repository cakephp/cakephp, pull requests merged in 2021-11, with the labels that each got.

#16048 Add array type coercion for controller action params.
  src/Controller/ControllerFactory.php
  tests/TestCase/Controller/ControllerFactoryTest.php
  tests/test_app/TestApp/Controller/DependenciesController.php
Labels: enhancement

#16103 PHPDoc deprecated colon prefixed to braced paceholder
  src/Routing/Route/PluginShortRoute.php
  src/Routing/RouteBuilder.php
Labels: documentation

#16100 Deprecate public Connection::setDriver()
  src/Database/Connection.php
  src/Database/Exception/MissingDriverException.php
  src/Database/Exception/MissingExtensionException.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Database/Driver/PostgresTest.php
  tests/TestCase/Database/Driver/SqlserverTest.php
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/ORM/TableTest.php
Labels: database, deprecations

#16114 Clean up deprecation warning message
  src/Core/functions.php
  tests/TestCase/Core/FunctionsTest.php
Labels: deprecations

#16118 Fix up setting helpers as normalized.
  src/View/ViewBuilder.php
  tests/TestCase/Error/DebuggerTest.php
  tests/TestCase/Error/ExceptionRendererTest.php
  tests/TestCase/Mailer/MailerTest.php
  tests/TestCase/View/ViewBuilderTest.php
  tests/TestCase/View/ViewTest.php
Labels: defect

#16115 Add HSTS header to HttpsEnforcerMiddleware
  src/Http/Middleware/HttpsEnforcerMiddleware.php
  tests/TestCase/Http/Middleware/HttpsEnforcerMiddlewareTest.php
Labels: enhancement, http

#16125 Specify behavior of configRequest more precisely
  src/TestSuite/IntegrationTestTrait.php
Labels: documentation, testing

#16133 Fix CS.
  src/Database/Expression/CaseExpressionTrait.php
  src/Database/Expression/CaseStatementExpression.php
  src/Database/Expression/QueryExpression.php
  src/Database/Expression/WhenThenExpression.php
Labels: cleanup

#16124 Update Controller to directly use the Paginator class.
  src/Controller/Controller.php
  tests/TestCase/Controller/ControllerTest.php
Labels: pagination

#16117 Add prefer lowest version validation.
  .github/workflows/ci.yml
  composer.json
Labels: RFC

#16140 Add http status code 308 PERMANENT REDIRECT to Response::isRedirect
  src/Http/Client/Message.php
  src/Http/Client/Response.php
Labels: http

#16134 5.x merge view helpers squashed
  src/View/View.php
  src/View/ViewBuilder.php
  tests/TestCase/View/ViewBuilderTest.php
  tests/TestCase/View/ViewTest.php
  tests/test_app/TestApp/View/TestStringTemplate.php
  tests/test_app/TestApp/View/TestView.php
Labels: enhancement

#16150 Remove unneeded variable assignment.
  src/Core/functions.php
Labels: cleanup

#16152 Avoid unneeded variable assignment.
  src/ORM/Table.php
Labels: cleanup

#16156 Fix docblock
  src/Routing/Route/Route.php
Labels: documentation
