Repository cakephp/cakephp, pull requests merged in 2021-02, with the labels that each got.

#15322 Add `@see` tags to allow easy navigation to related marshaller methods.
  src/ORM/Table.php
Labels: documentation

#15324 Route cleanup
  src/Routing/Route/Route.php
Labels: cleanup

#15330 Improve $address parameter annotation for assertMailSentTo()
  src/TestSuite/EmailTrait.php
Labels: documentation, testing

#15340 Entity::isEmpty() behaves differently than method's comments
  src/Datasource/EntityTrait.php
  tests/TestCase/ORM/EntityTest.php
Labels: defect

#15338 Error handling is logging silenced (@) errors in PHP8. Issue #15336
  src/Error/BaseErrorHandler.php
Labels: php8.0

#15343 Simplify wrapping join tables expressions in parentheses
  src/Database/QueryCompiler.php
Labels: cleanup

#15344 Remove invalid options from attachTo
  src/ORM/Association.php
  tests/TestCase/ORM/QueryRegressionTest.php
Labels: cleanup

#15349 4.x - Fix file cache engine trying to clear root on realpath failure.
  src/Cache/Engine/FileEngine.php
Labels: cache
