Repository cakephp/cakephp, pull requests merged in 2021-07, with the labels that each got.

#15635 cake 5: Remove deprecated ? placeholders
  src/Utility/Text.php
  tests/TestCase/Utility/TextTest.php
Labels: cleanup

#15641 cake 5: Remove incomplete shell test
  tests/TestCase/Command/CompletionCommandTest.php
Labels: cleanup

#15638 cake 5: Remove _buildValidator deprecation warning
  src/Form/Form.php
Labels: cleanup

#15637 cake 5: Remove deprecated log formatter options
  src/Log/Engine/ConsoleLog.php
  src/Log/Engine/FileLog.php
  tests/TestCase/Log/Engine/ConsoleLogTest.php
  tests/TestCase/Log/Engine/FileLogTest.php
Labels: cleanup

#15636 cake 5: Remove deprecated sortWhiteList option
  src/Datasource/Paginator.php
  tests/TestCase/Datasource/PaginatorTestTrait.php
Labels: cleanup

#15643 cake 5: Remove deprecated File and Folder
  phpstan-baseline.neon
  src/Filesystem/File.php
  src/Filesystem/Folder.php
  tests/TestCase/Filesystem/FileTest.php
  tests/TestCase/Filesystem/FolderTest.php
Labels: cleanup

#15640 cake 5: Remove only E_USER_DEPRECATED flag when hiding deprecations
  src/TestSuite/TestCase.php
Labels: defect, testing

#15646 cake 5: Remove deprecated CakeException alias
  src/Core/Exception/Exception.php
Labels: cleanup

#15639 cake 5: Remove deprecated cast() parameters
  src/Database/FunctionsBuilder.php
  tests/TestCase/Database/FunctionsBuilderTest.php
Labels: cleanup

#15645 backport: Remove E_USER_DEPRECATED flag only when hiding deprecations
  src/TestSuite/TestCase.php
Labels: backport, defect

#15647 Fix parameter typehints in TestApp
  tests/TestCase/Auth/FormAuthenticateTest.php
  tests/TestCase/Controller/Component/PaginatorComponentTest.php
  tests/TestCase/DatabaseSuite.php
  tests/TestCase/Event/EventManagerTest.php
  tests/TestCase/Routing/RouterTest.php
  tests/test_app/TestApp/Application.php
  tests/test_app/TestApp/ApplicationWithDefaultRoutes.php
  tests/test_app/TestApp/ApplicationWithPluginRoutes.php
  tests/test_app/TestApp/Auth/TestAuthenticate.php
  tests/test_app/TestApp/Cache/Engine/TestAppCacheEngine.php
  tests/test_app/TestApp/Collection/CountableIterator.php
  tests/test_app/TestApp/Collection/TestIterator.php
  tests/test_app/TestApp/Controller/AuthTestController.php
  tests/test_app/TestApp/Controller/Component/AppleComponent.php
  tests/test_app/TestApp/Controller/Component/OrangeComponent.php
  tests/test_app/TestApp/Controller/Component/RequestHandlerExtComponent.php
  tests/test_app/TestApp/Controller/Component/TestAuthComponent.php
  tests/test_app/TestApp/Controller/Component/TestSecurityComponent.php
  tests/test_app/TestApp/Controller/DependenciesController.php
  tests/test_app/TestApp/Controller/PostsController.php
  tests/test_app/TestApp/Controller/SecurityTestController.php
  tests/test_app/TestApp/Controller/TestController.php
  tests/test_app/TestApp/Database/Type/ColumnSchemaAwareType.php
  tests/test_app/TestApp/Database/Type/OrderedUuidType.php
  tests/test_app/TestApp/Database/Type/TestType.php
  tests/test_app/TestApp/Database/Type/UuidValue.php
  tests/test_app/TestApp/Http/Client/Adapter/CakeStreamWrapper.php
  tests/test_app/TestApp/Http/Session/TestAppLibSession.php
  tests/test_app/TestApp/Log/Formatter/ValidFormatter.php
  tests/test_app/TestApp/Mailer/TestMessage.php
  tests/test_app/TestApp/Mailer/TestUserMailer.php
  tests/test_app/TestApp/Mailer/Transport/SmtpTestTransport.php
  tests/test_app/TestApp/Middleware/DumbMiddleware.php
  tests/test_app/TestApp/Middleware/SampleMiddleware.php
  tests/test_app/TestApp/Middleware/ThrowsExceptionMiddleware.php
  tests/test_app/TestApp/Model/Behavior/SluggableBehavior.php
  tests/test_app/TestApp/Model/Table/PaginatorPostsTable.php
  tests/test_app/TestApp/Model/Table/PublishedPostsTable.php
  tests/test_app/TestApp/Model/Table/TestTable.php
  tests/test_app/TestApp/Shell/ShellTestShell.php
  tests/test_app/TestApp/Shell/TestingDispatchShell.php
  tests/test_app/TestApp/Stub/Stub.php
  tests/test_app/TestApp/Utility/Base.php
  tests/test_app/TestApp/View/Cell/ArticlesCell.php
  tests/test_app/TestApp/View/Helper/EventListenerTestHelper.php
  tests/test_app/TestApp/View/Helper/HtmlAliasHelper.php
  tests/test_app/TestApp/View/Helper/TestBeforeAfterHelper.php
  tests/test_app/TestApp/View/TestView.php
  tests/test_app/TestApp/View/Widget/TestUsingViewWidget.php
Labels: cleanup

#15648 Minor optimization.
  src/Controller/Controller.php
Labels: cleanup

#15650 Fix tests param typehints
  tests/TestCase/Routing/RouteBuilderTest.php
  tests/TestCase/Routing/RouteCollectionTest.php
  tests/TestCase/Routing/RouterTest.php
  tests/TestCase/TestSuite/FixtureManagerTest.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
  tests/TestCase/Utility/HashTest.php
  tests/TestCase/Utility/InflectorTest.php
  tests/TestCase/Utility/TextTest.php
  tests/TestCase/Utility/XmlTest.php
  tests/TestCase/Validation/ValidationTest.php
  tests/TestCase/View/Form/EntityContextTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/Helper/NumberHelperTest.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
  tests/TestCase/View/Helper/TextHelperTest.php
  tests/TestCase/View/ViewBuilderTest.php
  tests/TestCase/View/ViewTest.php
  tests/TestCase/View/Widget/CheckboxWidgetTest.php
  tests/TestCase/View/Widget/DateTimeWidgetTest.php
  tests/test_app/Plugin/TestPlugin/src/Cache/Engine/TestPluginCacheEngine.php
  tests/test_app/Plugin/TestPlugin/src/Http/Session/TestPluginSession.php
  tests/test_app/Plugin/TestPlugin/src/Log/Engine/TestPluginLog.php
Labels: cleanup

#15651 Fix tests param typehints
  tests/TestCase/Collection/CollectionTest.php
  tests/TestCase/Error/ExceptionRendererTest.php
  tests/TestCase/Filesystem/FileTest.php
  tests/TestCase/Http/Client/ResponseTest.php
  tests/TestCase/Http/ClientTest.php
  tests/TestCase/Http/Cookie/CookieTest.php
  tests/TestCase/Http/CorsBuilderTest.php
  tests/TestCase/Http/Middleware/BodyParserMiddlewareTest.php
  tests/TestCase/Http/Middleware/CsrfProtectionMiddlewareTest.php
  tests/TestCase/Http/Middleware/SessionCsrfProtectionMiddlewareTest.php
  tests/TestCase/Http/ResponseTest.php
  tests/TestCase/Http/ServerRequestTest.php
  tests/TestCase/Http/server_mocks.php
  tests/TestCase/I18n/DateTest.php
  tests/TestCase/I18n/PluralRulesTest.php
  tests/TestCase/I18n/TimeTest.php
  tests/TestCase/Log/Engine/BaseLogTest.php
  tests/TestCase/Log/Engine/SyslogLogTest.php
  tests/TestCase/Log/LogTest.php
  tests/TestCase/Mailer/EmailTest.php
  tests/TestCase/Mailer/MailerTest.php
  tests/TestCase/Mailer/MessageTest.php
  tests/TestCase/Network/SocketTest.php
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/ORM/Behavior/CounterCacheBehaviorTest.php
  tests/TestCase/ORM/BindingKeyTest.php
  tests/TestCase/ORM/CompositeKeysTest.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/ORM/MarshallerTest.php
  tests/TestCase/ORM/QueryTest.php
  tests/TestCase/ORM/TableUuidTest.php
  tests/TestCase/Routing/Middleware/AssetMiddlewareTest.php
  tests/TestCase/Routing/Middleware/RoutingMiddlewareTest.php
Labels: cleanup

#15649 Clarify `Query::applyOptions()` behavior.
  src/Datasource/QueryTrait.php
  src/ORM/Query.php
Labels: documentation

#15652 Fix tests param typehints
  tests/TestCase/BasicsTest.php
  tests/TestCase/Cache/CacheTest.php
  tests/TestCase/Command/PluginUnloadCommandTest.php
  tests/TestCase/Console/CommandCollectionTest.php
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Console/ConsoleIoTest.php
  tests/TestCase/Console/ShellTest.php
  tests/TestCase/Controller/Component/PaginatorComponentTest.php
  tests/TestCase/Controller/Component/SecurityComponentTest.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Core/FunctionsTest.php
  tests/TestCase/Database/Driver/SqliteTest.php
  tests/TestCase/Database/DriverTest.php
  tests/TestCase/Database/Expression/QueryExpressionTest.php
  tests/TestCase/Database/Schema/MysqlSchemaTest.php
  tests/TestCase/Database/Schema/PostgresSchemaTest.php
  tests/TestCase/Database/Schema/SqliteSchemaTest.php
  tests/TestCase/Database/Schema/SqlserverSchemaTest.php
  tests/TestCase/Database/Schema/TableSchemaTest.php
  tests/TestCase/Database/Type/DateTimeFractionalTypeTest.php
  tests/TestCase/Database/Type/DateTimeTimezoneTypeTest.php
  tests/TestCase/Database/Type/DateTimeTypeTest.php
  tests/TestCase/Database/Type/DateTypeTest.php
  tests/TestCase/Database/Type/TimeTypeTest.php
  tests/TestCase/Database/TypeFactoryTest.php
  tests/TestCase/Datasource/ConnectionManagerTest.php
  tests/TestCase/Datasource/PaginatorTestTrait.php
  tests/TestCase/Error/DebuggerTest.php
  tests/TestCase/Error/ErrorHandlerTest.php
  tests/TestCase/Mailer/EmailTest.php
Labels: cleanup

#15654 Fix tests parameter typehints
  tests/TestCase/Error/ErrorHandlerTest.php
Labels: cleanup

#15653 Deprecate DoublePassDecoratorMiddleware.
  psalm-baseline.xml
  src/Http/Middleware/DoublePassDecoratorMiddleware.php
  tests/TestCase/Http/MiddlewareQueueTest.php
  tests/TestCase/Http/RunnerTest.php
  tests/TestCase/Http/ServerTest.php
  tests/TestCase/Routing/Middleware/RoutingMiddlewareTest.php
  tests/test_app/Plugin/TestPlugin/src/Plugin.php
  tests/test_app/TestApp/Application.php
  tests/test_app/TestApp/Http/EventApplication.php
  tests/test_app/TestApp/Http/MiddlewareApplication.php
  tests/test_app/TestApp/Middleware/DumbMiddleware.php
  tests/test_app/TestApp/Middleware/SampleMiddleware.php
  tests/test_app/TestApp/Middleware/ThrowsExceptionMiddleware.php
Labels: deprecations

#15642 Deprecate colon prefixed route template placeholders.
  src/Routing/Route/Route.php
  tests/TestCase/Command/RoutesCommandTest.php
  tests/TestCase/Routing/AssetTest.php
  tests/TestCase/Routing/Route/DashedRouteTest.php
  tests/TestCase/Routing/Route/EntityRouteTest.php
  tests/TestCase/Routing/Route/InflectedRouteTest.php
  tests/TestCase/Routing/Route/PluginShortRouteTest.php
  tests/TestCase/Routing/Route/RedirectRouteTest.php
  tests/TestCase/Routing/Route/RouteTest.php
  tests/TestCase/Routing/RouteBuilderTest.php
  tests/TestCase/Routing/RouteCollectionTest.php
  tests/TestCase/Routing/RouterTest.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/Helper/HtmlHelperTest.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
  tests/test_app/TestApp/Application.php
Labels: deprecations

#15657 Sync plugin short usage for i18n commands.
  src/Command/I18nExtractCommand.php
Labels: enhancement

#15633 Deprecate calling ResultSetInterface methods on query instances directly
  src/Datasource/QueryTrait.php
  src/ORM/LazyEagerLoader.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorShadowTableTest.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
  tests/TestCase/ORM/Behavior/TreeBehaviorTest.php
  tests/TestCase/ORM/BindingKeyTest.php
  tests/TestCase/ORM/ColumnSchemaAwareTypeIntegrationTest.php
  tests/TestCase/ORM/CompositeKeysTest.php
  tests/TestCase/ORM/QueryRegressionTest.php
  tests/TestCase/ORM/QueryTest.php
  tests/TestCase/ORM/ResultSetTest.php
  tests/TestCase/ORM/TableTest.php
Labels: ORM, deprecations

#15663 Fix docblock tag alignment
  src/Http/Client.php
  src/TestSuite/Fixture/SchemaCleaner.php
Labels: cleanup, documentation

#15664 Remove deprecated DoublePassMiddleware.
  psalm-baseline.xml
  src/Http/Middleware/DoublePassDecoratorMiddleware.php
  src/Http/MiddlewareQueue.php
  tests/TestCase/Http/MiddlewareQueueTest.php
Labels: cleanup, deprecations

#15665 cake 5: Remove deprecated ResultSet method proxying
  src/Datasource/QueryTrait.php
  src/ORM/Query.php
  tests/TestCase/ORM/QueryTest.php
Labels: cleanup

#15674 cake 5: Add native type hints for Core
  .stickler.yml
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Cache/CacheRegistry.php
  src/Console/HelperRegistry.php
  src/Controller/Component/FlashComponent.php
  src/Controller/Component/PaginatorComponent.php
  src/Controller/ComponentRegistry.php
  src/Core/Configure.php
  src/Core/Configure/Engine/IniConfig.php
  src/Core/Exception/CakeException.php
  src/Core/InstanceConfigTrait.php
  src/Core/ObjectRegistry.php
  src/Core/PluginApplicationInterface.php
  src/Core/Retry/CommandRetry.php
  src/Core/ServiceConfig.php
  src/Core/ServiceProvider.php
  src/Core/StaticConfigTrait.php
  src/Core/functions.php
  src/Datasource/ConnectionRegistry.php
  src/Log/LogEngineRegistry.php
  src/Mailer/TransportRegistry.php
  src/ORM/BehaviorRegistry.php
  src/View/HelperRegistry.php
  tests/TestCase/Core/StaticConfigTraitTest.php
  tests/TestCase/Mailer/MailerTest.php
Labels: enhancement, php

#15680 Fix TruncationResetStrategy and TransactionResetStrategy names
  phpstan-baseline.neon
  src/TestSuite/Fixture/TransactionResetStrategy.php
  src/TestSuite/Fixture/TruncationResetStrategy.php
  src/TestSuite/TestCase.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Http/SessionTest.php
  tests/TestCase/TestSuite/Fixture/TransactionResetStrategyTest.php
  tests/TestCase/TestSuite/Fixture/TruncationResetStrategyTest.php
  tests/TestCase/TestSuite/TestCaseTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/ViewTest.php
Labels: cleanup

#15678 Remove deprecated behavior from App::path().
  src/Core/App.php
  tests/TestCase/Core/AppTest.php
Labels: deprecations

#15679 cake 5: Add native type hints for Cache
  phpstan-baseline.neon
  src/Cache/Cache.php
  src/Cache/CacheEngine.php
  src/Cache/CacheEngineInterface.php
  src/Cache/Engine/ApcuEngine.php
  src/Cache/Engine/ArrayEngine.php
  src/Cache/Engine/FileEngine.php
  src/Cache/Engine/MemcachedEngine.php
  src/Cache/Engine/NullEngine.php
  src/Cache/Engine/RedisEngine.php
  tests/test_app/Plugin/TestPlugin/src/Cache/Engine/TestPluginCacheEngine.php
  tests/test_app/TestApp/Cache/Engine/TestAppCacheEngine.php
Labels: enhancement

#15684 cake 5: Remove use of deprecated Serializable
  src/Collection/Collection.php
  src/Collection/Iterator/BufferedIterator.php
  src/Collection/Iterator/ZipIterator.php
  src/Datasource/ResultSetInterface.php
  src/Mailer/Message.php
  src/ORM/ResultSet.php
  src/View/ViewBuilder.php
  tests/TestCase/ORM/Association/HasManyTest.php
Labels: cleanup, php

#15683 PHP 8.1: Iterator returns
  src/Collection/Iterator/ZipIterator.php
  tests/TestCase/Collection/CollectionTest.php
  tests/test_app/TestApp/Collection/TestIterator.php
Labels: php

#15686 Replace getTypeName() with PHP's get_debug_type().
  src/Console/BaseCommand.php
  src/Controller/Controller.php
  src/Core/ServiceProvider.php
  src/Core/functions.php
  src/Database/Statement/PDOStatement.php
  src/Database/Type/BoolType.php
  src/Database/Type/DecimalType.php
  src/Database/Type/IntegerType.php
  src/Database/Type/StringType.php
  src/Datasource/FactoryLocator.php
  src/Datasource/ModelAwareTrait.php
  src/Error/BaseErrorHandler.php
  src/Error/Debugger.php
  src/Error/Middleware/ErrorHandlerMiddleware.php
  src/Http/Cookie/Cookie.php
  src/Http/Cookie/CookieCollection.php
  src/Log/Engine/BaseLog.php
  src/Log/LogEngineRegistry.php
  src/ORM/Marshaller.php
  src/ORM/Rule/LinkConstraint.php
  src/ORM/RulesChecker.php
  src/ORM/Table.php
  src/Routing/Route/EntityRoute.php
  src/Routing/RouteBuilder.php
  src/Validation/Validator.php
  src/View/Form/ContextFactory.php
  src/View/Widget/WidgetLocator.php
  tests/TestCase/Core/FunctionsTest.php
  tests/TestCase/ORM/Rule/LinkConstraintTest.php
  tests/TestCase/ORM/RulesCheckerIntegrationTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/View/Form/ContextFactoryTest.php
  tests/test_app/TestApp/Database/Type/ColumnSchemaAwareType.php
Labels: php

#15685 cake 5: Add native type hints for Utility
  src/Utility/CookieCryptTrait.php
  src/Utility/Hash.php
  src/Utility/Inflector.php
  src/Utility/MergeVariablesTrait.php
  src/Utility/Security.php
  src/Utility/Text.php
  src/Utility/Xml.php
  tests/TestCase/Utility/HashTest.php
  tests/TestCase/Utility/TextTest.php
  tests/TestCase/Utility/XmlTest.php
  tests/TestCase/View/XmlViewTest.php
Labels: enhancement

#15688 cake 5: Add native type hints for Validation
  src/Validation/RulesProvider.php
  src/Validation/Validation.php
  src/Validation/ValidationRule.php
  src/Validation/ValidationSet.php
  src/Validation/Validator.php
  tests/TestCase/Validation/ValidationTest.php
  tests/TestCase/Validation/ValidatorTest.php
Labels: enhancement

#15701 Remove redundant code.
  src/View/JsonView.php
Labels: cleanup

#15702 Remove redundant checks.
  tests/TestCase/Cache/Engine/MemcachedEngineTest.php
  tests/TestCase/Core/ConfigureTest.php
  tests/TestCase/Http/ResponseTest.php
Labels: cleanup

#15705 Fix radio inputs trimming leading - off causing duplicate ids
  src/View/Widget/RadioWidget.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/Widget/RadioWidgetTest.php
Labels: defect, form

#15707 cake 5: Remove CURRENCY_ACCOUNTING constant
  src/I18n/Number.php
Labels: i18n, php

#15708 PHP 8.1: Add ReturnTypeWillChange attributes to iterators
  src/Database/Query.php
  src/Database/Statement/BufferedStatement.php
  src/Database/Statement/StatementDecorator.php
  src/Datasource/EntityTrait.php
  src/ORM/ResultSet.php
Labels: php

#15712 Fix php 8.1 warnings
  src/Database/Type/DateTimeType.php
  src/ORM/Association/BelongsToMany.php
  tests/test_app/TestApp/Http/Client/Adapter/CakeStreamWrapper.php
Labels: php

#15698 cake 5: Add native type hints for Console
  src/Command/I18nExtractCommand.php
  src/Console/Arguments.php
  src/Console/BaseCommand.php
  src/Console/CommandCollection.php
  src/Console/ConsoleInputArgument.php
  src/Console/ConsoleInputOption.php
  src/Console/ConsoleInputSubcommand.php
  src/Console/ConsoleIo.php
  src/Console/ConsoleOptionParser.php
  src/Console/ConsoleOutput.php
  src/Console/Exception/MissingOptionException.php
  src/Console/HelpFormatter.php
  tests/TestCase/Console/ArgumentsTest.php
  tests/TestCase/Console/CommandTest.php
  tests/test_app/TestApp/Command/AbortCommand.php
  tests/test_app/TestApp/Command/BridgeCommand.php
  tests/test_app/TestApp/Command/DemoCommand.php
  tests/test_app/TestApp/Command/DependencyCommand.php
  tests/test_app/TestApp/Command/FormatSpecifierCommand.php
  tests/test_app/TestApp/Command/IntegrationCommand.php
  tests/test_app/TestApp/Command/NonInteractiveCommand.php
Labels: enhancement, php

#15716 Remove deprecated code from Route.
  src/Routing/Route/Route.php
  tests/TestCase/Routing/Route/RouteTest.php
Labels: cleanup

#15717 Remove deprecated code.
  src/Controller/ControllerFactory.php
  src/Datasource/EntityTrait.php
  src/Error/Middleware/ErrorHandlerMiddleware.php
  src/Http/Middleware/CsrfProtectionMiddleware.php
  src/Validation/Validator.php
  tests/TestCase/Controller/ControllerFactoryTest.php
  tests/TestCase/Http/Middleware/CsrfProtectionMiddlewareTest.php
  tests/TestCase/Validation/ValidatorTest.php
Labels: cleanup

#15718 Remove checks for defunct controller properties.
  src/Controller/Controller.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Error/ExceptionRendererTest.php
Labels: cleanup

#15714 cake 5: Add native type hints for Core properties
  src/Console/Exception/ConsoleException.php
  src/Console/Exception/MissingHelperException.php
  src/Controller/Exception/MissingActionException.php
  src/Controller/Exception/MissingComponentException.php
  src/Core/BasePlugin.php
  src/Core/Configure.php
  src/Core/Configure/Engine/IniConfig.php
  src/Core/Configure/Engine/JsonConfig.php
  src/Core/Configure/Engine/PhpConfig.php
  src/Core/Configure/FileConfigTrait.php
  src/Core/Exception/CakeException.php
  src/Core/Exception/MissingPluginException.php
  src/Core/InstanceConfigTrait.php
  src/Core/ObjectRegistry.php
  src/Core/Plugin.php
  src/Core/PluginCollection.php
  src/Core/Retry/CommandRetry.php
  src/Core/ServiceProvider.php
  src/Core/StaticConfigTrait.php
  src/Database/Exception/MissingConnectionException.php
  src/Database/Exception/MissingDriverException.php
  src/Database/Exception/MissingExtensionException.php
  src/Datasource/Exception/MissingDatasourceConfigException.php
  src/Datasource/Exception/MissingDatasourceException.php
  src/Datasource/Exception/MissingModelException.php
  src/Datasource/Exception/PageOutOfBoundsException.php
  src/Http/Exception/BadRequestException.php
  src/Http/Exception/ConflictException.php
  src/Http/Exception/ForbiddenException.php
  src/Http/Exception/GoneException.php
  src/Http/Exception/HttpException.php
  src/Http/Exception/InvalidCsrfTokenException.php
  src/Http/Exception/MethodNotAllowedException.php
  src/Http/Exception/MissingControllerException.php
  src/Http/Exception/NotAcceptableException.php
  src/Http/Exception/NotFoundException.php
  src/Http/Exception/NotImplementedException.php
  src/Http/Exception/ServiceUnavailableException.php
  src/Http/Exception/UnauthorizedException.php
  src/Http/Exception/UnavailableForLegalReasonsException.php
  src/Mailer/Exception/MissingActionException.php
  src/Mailer/Exception/MissingMailerException.php
  src/ORM/Exception/MissingBehaviorException.php
  src/ORM/Exception/MissingEntityException.php
  src/ORM/Exception/MissingTableClassException.php
  src/ORM/Exception/PersistenceFailedException.php
  src/ORM/Exception/RolledbackTransactionException.php
  src/Routing/Exception/DuplicateNamedRouteException.php
  src/Routing/Exception/MissingDispatcherFilterException.php
  src/Routing/Exception/MissingRouteException.php
  src/View/Exception/MissingCellException.php
  src/View/Exception/MissingHelperException.php
  src/View/Exception/MissingViewException.php
  tests/test_app/TestApp/ServiceProvider/PersonServiceProvider.php
Labels: enhancement, php

#15713 cake 5: Add native type hints for Http
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Http/BaseApplication.php
  src/Http/Client.php
  src/Http/Client/Adapter/Curl.php
  src/Http/Client/FormData.php
  src/Http/Client/Request.php
  src/Http/Client/Response.php
  src/Http/ControllerFactoryInterface.php
  src/Http/Cookie/Cookie.php
  src/Http/Cookie/CookieCollection.php
  src/Http/Cookie/CookieInterface.php
  src/Http/CorsBuilder.php
  src/Http/Exception/HttpException.php
  src/Http/FlashMessage.php
  src/Http/Middleware/BodyParserMiddleware.php
  src/Http/Middleware/CspMiddleware.php
  src/Http/MiddlewareQueue.php
  src/Http/Response.php
  src/Http/ResponseEmitter.php
  src/Http/ServerRequest.php
  src/Http/Session.php
  src/Http/Session/CacheSession.php
  src/Http/Session/DatabaseSession.php
  tests/TestCase/Http/ResponseTest.php
  tests/TestCase/Http/ServerRequestTest.php
  tests/TestCase/Http/Session/CacheSessionTest.php
  tests/TestCase/Http/Session/DatabaseSessionTest.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
Labels: enhancement, php

#15719 cake 5: Add native type hints for Error
  src/Error/BaseErrorHandler.php
  src/Error/Debug/ArrayItemNode.php
  src/Error/Debug/ConsoleFormatter.php
  src/Error/Debug/DebugContext.php
  src/Error/Debug/HtmlFormatter.php
  src/Error/Debug/NodeInterface.php
  src/Error/Debug/ScalarNode.php
  src/Error/Debug/TextFormatter.php
  src/Error/Debugger.php
  src/Error/ErrorHandler.php
  src/Error/ErrorLoggerInterface.php
  src/Error/Middleware/ErrorHandlerMiddleware.php
  tests/TestCase/Error/DebuggerTest.php
  tests/TestCase/Error/Middleware/ErrorHandlerMiddlewareTest.php
Labels: enhancement, php

#15720 cake 5: Add native type hints for Controller
  src/Controller/Component.php
  src/Controller/Component/FlashComponent.php
  src/Controller/Component/PaginatorComponent.php
  src/Controller/Component/RequestHandlerComponent.php
  src/Controller/Controller.php
  src/Controller/ControllerFactory.php
Labels: enhancement, php

#15723 cake 5: Add native type hints for Event
  phpstan-baseline.neon
  src/Event/Decorator/AbstractDecorator.php
  src/Event/Decorator/ConditionDecorator.php
  src/Event/Decorator/SubjectFilterDecorator.php
  src/Event/Event.php
  src/Event/EventInterface.php
  src/Event/EventList.php
  src/Event/EventManager.php
  src/Event/EventManagerInterface.php
  tests/TestCase/Event/Decorator/SubjectFilterDecoratorTest.php
Labels: enhancement, php

#15724 cake 5: Add native type hints for Form
  src/Form/Form.php
  src/Form/FormProtector.php
  src/Form/Schema.php
Labels: enhancement, php
