Repository cakephp/cakephp, pull requests merged in 2021-06, with the labels that each got.

#15570 Fix up more controller casing issues
  tests/TestCase/Controller/Component/AuthComponentTest.php
  tests/TestCase/Controller/Component/FormProtectionComponentTest.php
  tests/TestCase/Controller/Component/SecurityComponentTest.php
  tests/TestCase/Controller/ControllerFactoryTest.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Error/ExceptionRendererTest.php
  tests/TestCase/Http/ServerRequestTest.php
  tests/TestCase/Routing/Route/DashedRouteTest.php
  tests/TestCase/Routing/Route/InflectedRouteTest.php
  tests/TestCase/Routing/Route/PluginShortRouteTest.php
  tests/TestCase/Routing/Route/RedirectRouteTest.php
  tests/TestCase/Routing/Route/RouteTest.php
  tests/TestCase/Routing/RouteBuilderTest.php
  tests/TestCase/Routing/RouteCollectionTest.php
  tests/TestCase/Routing/RouterTest.php
  tests/TestCase/View/Helper/BreadcrumbsHelperTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/Helper/HtmlHelperTest.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
  tests/test_app/config/routes.php
Labels: cleanup, testing

#15558 Allow specifying middlewares at the controller level.
  phpstan-baseline.neon
  src/Controller/Controller.php
  src/Controller/ControllerFactory.php
  tests/TestCase/Controller/ControllerFactoryTest.php
  tests/test_app/TestApp/Controller/PostsController.php
Labels: middleware

#15583 Use DefaultFormatter with ArrayLog
  src/Log/Engine/ArrayLog.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Database/Log/LoggingStatementTest.php
Labels: enhancement

#15571 Remove additional wrong DS
  src/View/View.php
Labels: defect

#15578 Update return types for session handler methods.
  composer.json
  src/Http/Session/CacheSession.php
  src/Http/Session/DatabaseSession.php
  src/I18n/DateFormatTrait.php
  tests/TestCase/Http/Session/DatabaseSessionTest.php
  tests/test_app/Plugin/TestPlugin/src/Http/Session/TestPluginSession.php
  tests/test_app/TestApp/Http/Session/TestAppLibSession.php
Labels: php

#15599 Remove deprecated AuthComponent and related files.
  phpstan-baseline.neon
  psalm.xml
  src/Auth/AbstractPasswordHasher.php
  src/Auth/BaseAuthenticate.php
  src/Auth/BaseAuthorize.php
  src/Auth/BasicAuthenticate.php
  src/Auth/ControllerAuthorize.php
  src/Auth/DefaultPasswordHasher.php
  src/Auth/DigestAuthenticate.php
  src/Auth/FallbackPasswordHasher.php
  src/Auth/FormAuthenticate.php
  src/Auth/PasswordHasherFactory.php
  src/Auth/Storage/MemoryStorage.php
  src/Auth/Storage/SessionStorage.php
  src/Auth/Storage/StorageInterface.php
  src/Auth/WeakPasswordHasher.php
  src/Controller/Component/AuthComponent.php
  src/Core/App.php
  tests/TestCase/Auth/BasicAuthenticateTest.php
  tests/TestCase/Auth/ControllerAuthorizeTest.php
  tests/TestCase/Auth/DefaultPasswordHasherTest.php
  tests/TestCase/Auth/DigestAuthenticateTest.php
  tests/TestCase/Auth/FallbackPasswordHasherTest.php
  tests/TestCase/Auth/FormAuthenticateTest.php
  tests/TestCase/Auth/PasswordHasherFactoryTest.php
  tests/TestCase/Auth/Storage/MemoryStorageTest.php
  tests/TestCase/Auth/Storage/SessionStorageTest.php
  tests/TestCase/Auth/WeakPasswordHasherTest.php
  tests/TestCase/Controller/Component/AuthComponentTest.php
  tests/TestCase/Controller/ComponentRegistryTest.php
  tests/test_app/TestApp/Auth/CallCounterPasswordHasher.php
  tests/test_app/TestApp/Auth/TestAuthenticate.php
  tests/test_app/TestApp/Controller/AuthTestController.php
  tests/test_app/TestApp/Controller/Component/TestAuthComponent.php
Labels: cleanup

#15600 Update return types.
  src/Http/Session/CacheSession.php
  src/Http/Session/DatabaseSession.php
  src/I18n/DateFormatTrait.php
  tests/test_app/Plugin/TestPlugin/src/Http/Session/TestPluginSession.php
  tests/test_app/TestApp/Http/Session/TestAppLibSession.php
Labels: php

#15601 Normalize order of types in return tags
  src/Console/CommandCollection.php
  src/Console/HelpFormatter.php
  src/Database/Expression/FieldInterface.php
  src/Database/Expression/FieldTrait.php
  src/Database/Expression/QueryExpression.php
  src/Datasource/FactoryLocator.php
  src/ORM/Association.php
  src/ORM/Association/BelongsToMany.php
  src/ORM/Behavior/Translate/TranslateTrait.php
  src/ORM/ResultSet.php
  src/Utility/Hash.php
Labels: cleanup

#15603 cake 5: Remove validation deprecations
  src/Validation/Validation.php
  src/Validation/Validator.php
  src/View/Form/ArrayContext.php
  src/View/Form/EntityContext.php
  src/View/Form/FormContext.php
  src/View/Form/NullContext.php
  src/View/Helper/NumberHelper.php
  tests/TestCase/Validation/ValidationTest.php
  tests/TestCase/Validation/ValidatorTest.php
Labels: deprecations

#15602 cake 5: Remove database-related deprecated code
  src/Database/Exception.php
  src/Database/Expression/ComparisonExpression.php
  src/Database/Expression/QueryExpression.php
  src/Database/Schema/BaseSchema.php
  src/Database/Schema/MysqlSchema.php
  src/Database/Schema/MysqlSchemaDialect.php
  src/Database/Schema/PostgresSchema.php
  src/Database/Schema/PostgresSchemaDialect.php
  src/Database/Schema/SchemaDialect.php
  src/Database/Schema/SqliteSchema.php
  src/Database/Schema/SqliteSchemaDialect.php
  src/Database/Schema/SqlserverSchema.php
  src/Database/Schema/SqlserverSchemaDialect.php
  src/Database/Schema/TableSchema.php
  src/Database/SqlDialectTrait.php
  src/Database/Type.php
  src/Database/Type/DateTimeType.php
  src/Datasource/EntityTrait.php
  src/ORM/Behavior.php
  src/ORM/TableRegistry.php
  src/TestSuite/Schema/SchemaCleaner.php
  tests/TestCase/Database/Schema/CollectionTest.php
  tests/TestCase/Database/Schema/TableSchemaTest.php
  tests/TestCase/ExceptionsTest.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/ORM/TableRegistryTest.php
  tests/TestCase/TestSuite/Fixture/TransactionStrategyTest.php
  tests/TestCase/TestSuite/Fixture/TruncationStrategyTest.php
Labels: cleanup

#15604 cake 5: Remove http-related deprecated code
  src/Core/Exception/CakeException.php
  src/Error/ExceptionRenderer.php
  src/Http/Cookie/Cookie.php
  src/Http/Exception/RedirectException.php
  src/Http/Middleware/CsrfProtectionMiddleware.php
  src/Http/ServerRequest.php
  src/Mailer/Email.php
  tests/TestCase/Error/ExceptionRendererTest.php
  tests/TestCase/Error/Middleware/ErrorHandlerMiddlewareTest.php
  tests/TestCase/Http/Cookie/CookieTest.php
  tests/TestCase/Http/Middleware/CsrfProtectionMiddlewareTest.php
  tests/TestCase/Http/ServerRequestTest.php
  tests/TestCase/Mailer/EmailTest.php
  tests/TestCase/TestSuite/TestEmailTransportTest.php
Labels: cleanup

#15605 cake 5: Remove various deprecations
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Cache/Cache.php
  src/Console/Command.php
  src/Controller/Component/SecurityComponent.php
  src/Controller/Controller.php
  src/Core/ClassLoader.php
  src/Error/BaseErrorHandler.php
  src/Form/Form.php
  src/I18n/Number.php
  src/Mailer/Mailer.php
  src/Routing/Exception/RedirectException.php
  src/Routing/Middleware/RoutingMiddleware.php
  src/TestSuite/ConsoleIntegrationTestCase.php
  src/TestSuite/IntegrationTestCase.php
  tests/Fixture/AssertIntegrationTestCase.php
  tests/TestCase/Controller/Component/SecurityComponentTest.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/ExceptionsTest.php
  tests/TestCase/Form/FormTest.php
  tests/TestCase/I18n/NumberTest.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
Labels: cleanup

#15613 cake 5: Remove deprecated syslog formatter
  src/Log/Engine/SyslogLog.php
  src/Log/Formatter/LegacySyslogFormatter.php
  tests/TestCase/Log/Engine/SyslogLogTest.php
Labels: cleanup

#15611 cake 5: Require array event payload
  src/Event/Event.php
  src/Event/EventDispatcherInterface.php
  src/Event/EventDispatcherTrait.php
  src/Event/EventInterface.php
  tests/TestCase/Event/EventTest.php
Labels: defect

#15621 cake 5: Remove Wincache support
  .github/workflows/ci.yml
  src/Cache/Cache.php
  src/Cache/Engine/WincacheEngine.php
  src/Cache/README.md
  src/Command/CacheClearCommand.php
  tests/TestCase/Cache/Engine/WincacheEngineTest.php
Labels: cache, cleanup

#15567 fix error in PaginatorHelper with scopes
  src/View/Helper/PaginatorHelper.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
Labels: defect

#15592 Resolves #15585 by allowing a name to be specified for the csrf token…
  src/TestSuite/IntegrationTestTrait.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
Labels: defect

#15625 cake 5: Remove deprecated underscored special view vars
  src/View/View.php
  tests/TestCase/View/JsonViewTest.php
Labels: cleanup

#15628 Return PDOStatement instead of true for query mock return
  tests/TestCase/Database/DriverTest.php
Labels: php

#15627 Return array instead of false for empty fetchAll() mock return
  tests/TestCase/Database/Schema/SqliteSchemaTest.php
Labels: php

#15624 cake 5: Remove deprecated Paginator whitelist config
  src/Datasource/Paginator.php
  tests/TestCase/Controller/Component/PaginatorComponentTest.php
  tests/TestCase/Datasource/PaginatorTestTrait.php
Labels: cleanup
