Repository cakephp/cakephp, pull requests merged in 2021-01, with the labels that each got.

#15149 Retain flash also for redirect
  src/TestSuite/IntegrationTestTrait.php
Labels: defect

#15261 Update api links to 4.x
  src/Database/README.md
  src/Datasource/README.md
Labels: documentation

#15267 Show phpcs sniff with each error
  phpcs.xml
  src/Database/Expression/QueryExpression.php
Labels: cleanup

#15273 Handle missing translations when saving. Fixes #15272
  src/ORM/Behavior/Translate/TranslateStrategyTrait.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorShadowTableTest.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
Labels: ORM, defect

#15275 Micro optimization.
  src/ORM/Behavior/Translate/TranslateStrategyTrait.php
Labels: optimization

#15283 Remove incorrect argument type.
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: validation

#15278 Add Query::whereNotInListOrNull() and QueryExpression::notInOrNull()
  phpstan-baseline.neon
  src/Database/Expression/QueryExpression.php
  src/Database/Query.php
  tests/TestCase/Database/Expression/QueryExpressionTest.php
  tests/TestCase/Database/QueryTest.php
Labels: enhancement

#15284 # Regression ? regex can be 'int'
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: defect

#15289 Issue #15288. Fix SprintfFormatter.
  src/I18n/Formatter/IcuFormatter.php
  src/I18n/Formatter/SprintfFormatter.php
  src/I18n/Translator.php
  tests/TestCase/I18n/I18nTest.php
Labels: defect

#15293 Include message body in serialized Message.
  src/Mailer/Message.php
  tests/TestCase/Mailer/MessageTest.php
Labels: mailer

#15303 Updated example in Cache::remember Doc bloc
  src/Cache/Cache.php
Labels: documentation

#15316 Port fixes from #15304 to 3.x
  src/Shell/RoutesShell.php
  tests/TestCase/Shell/RoutesShellTest.php
Labels: backport
