Repository cakephp/cakephp, pull requests merged in 2021-03, with the labels that each got.

#15352 Use null coalescing operator where possible.
  src/Auth/BaseAuthenticate.php
  src/Command/I18nExtractCommand.php
  src/Console/Arguments.php
  src/Console/CommandRunner.php
  src/Console/Shell.php
  src/Controller/Component.php
  src/Controller/Component/RequestHandlerComponent.php
  src/Core/ClassLoader.php
  src/Core/InstanceConfigTrait.php
  src/Core/functions.php
  src/Database/Schema/TableSchema.php
  src/Database/Statement/StatementDecorator.php
  src/Database/TypeMap.php
  src/Datasource/ConnectionManager.php
  src/Datasource/RuleInvoker.php
  src/Error/BaseErrorHandler.php
  src/Filesystem/File.php
  src/Form/Schema.php
  src/Http/FlashMessage.php
  src/Http/Response.php
  src/Http/ServerRequest.php
  src/I18n/Package.php
  src/ORM/Association/BelongsToMany.php
  src/ORM/Association/Loader/SelectLoader.php
  src/ORM/AssociationCollection.php
  src/ORM/Behavior/CounterCacheBehavior.php
  src/ORM/Marshaller.php
  src/ORM/ResultSet.php
  src/ORM/Table.php
  src/Routing/Route/Route.php
  src/Routing/RouteBuilder.php
  src/Routing/RouteCollection.php
  src/Routing/Router.php
  src/Shell/Task/CommandTask.php
  src/TestSuite/Fixture/FixtureManager.php
  src/TestSuite/Fixture/TestFixture.php
  src/TestSuite/IntegrationTestTrait.php
  src/Utility/Hash.php
  src/Validation/ValidationRule.php
  src/Validation/Validator.php
  src/View/Helper/FormHelper.php
  src/View/Helper/PaginatorHelper.php
  src/View/View.php
  src/View/ViewBlock.php
  src/View/Widget/RadioWidget.php
  src/View/Widget/SelectBoxWidget.php
Labels: cleanup

#15350 Simplify disabling of association target fields
  src/ORM/Association.php
  tests/TestCase/ORM/Association/HasOneTest.php
Labels: cleanup

#15353 DATE_RFC7231
  src/Http/Response.php
  src/Routing/Middleware/AssetMiddleware.php
  tests/TestCase/Http/ResponseTest.php
  tests/TestCase/Routing/Middleware/AssetMiddlewareTest.php
Labels: defect

#15354 Simplify generating nested contains in setMatching()
  src/ORM/EagerLoader.php
  tests/TestCase/ORM/QueryTest.php
Labels: cleanup

#15361 Document avg() and median() with 0 rows and null values
  src/Collection/CollectionInterface.php
  tests/TestCase/Collection/CollectionTest.php
Labels: documentation

#15367 Backport: Detect infinite recursion when initializing Table
  src/ORM/Locator/TableLocator.php
  tests/TestCase/ORM/Locator/TableLocatorTest.php
  tests/test_app/TestApp/Model/Table/RecursionTable.php
Labels: backport

#15370 Backport: Allow multiple replyTo addresses.
  src/Mailer/Email.php
  tests/TestCase/Mailer/EmailTest.php
  tests/TestCase/Mailer/Transport/MailTransportTest.php
  tests/TestCase/Mailer/Transport/SmtpTransportTest.php
Labels: backport

#15375 Escape pre tag in markdown block
  src/Core/functions.php
Labels: documentation

#15374 Escape pre tag in markdown block
  src/Core/functions.php
Labels: documentation

#15380 [3.x] Allow to compare "mail sent with" against an array
  src/TestSuite/Constraint/Email/MailSentWith.php
  tests/TestCase/TestSuite/EmailTraitTest.php
Labels: email, testing

#15403 Don't use strlen() when we just need to check if string is empty or not.
  src/Database/Expression/QueryExpression.php
  src/Database/QueryCompiler.php
  src/Datasource/EntityTrait.php
  src/Http/Client/Adapter/Curl.php
  src/Http/ServerRequestFactory.php
  src/I18n/Translator.php
  src/Mailer/Message.php
  src/Shell/Helper/TableHelper.php
  src/Utility/Text.php
  src/Utility/Xml.php
  src/View/Form/EntityContext.php
  src/View/View.php
Labels: cleanup

#15371 4.next - Add support for schema column SQL/conversion via database types.
  src/Database/Schema/MysqlSchemaDialect.php
  src/Database/Schema/PostgresSchemaDialect.php
  src/Database/Schema/SchemaDialect.php
  src/Database/Schema/SqliteSchemaDialect.php
  src/Database/Schema/SqlserverSchemaDialect.php
  src/Database/Type/ColumnSchemaAwareInterface.php
  tests/Fixture/ColumnSchemaAwareTypeValuesFixture.php
  tests/TestCase/Database/ColumnSchemaAwareTypeTest.php
  tests/TestCase/ORM/ColumnSchemaAwareTypeIntegrationTest.php
  tests/test_app/TestApp/Database/ColumnSchemaAwareTypeValueObject.php
  tests/test_app/TestApp/Database/Type/ColumnSchemaAwareType.php
Labels: enhancement

#15404 4.next Start data only fixtures
  src/TestSuite/Fixture/FixtureInjector.php
  src/TestSuite/Fixture/TransactionStrategy.php
  src/TestSuite/FixtureSchemaExtension.php
  src/TestSuite/TestCase.php
  tests/TestCase/TestSuite/Fixture/TransactionStrategyTest.php
Labels: testing

#15413 Backport: Fix BufferedIterator not yielding full results
  src/Collection/Iterator/BufferedIterator.php
  tests/TestCase/Collection/CollectionTest.php
  tests/TestCase/Collection/Iterator/BufferedIteratorTest.php
Labels: backport

#15414 Backport: Fix RouteBuilder::plugin() not forwarding namePrefix option
  src/Routing/RouteBuilder.php
  tests/TestCase/Routing/RouteBuilderTest.php
Labels: backport

#15416 Remove uneeded phpcs ignores.
  src/Collection/CollectionTrait.php
  src/Console/HelperRegistry.php
  src/Console/TaskRegistry.php
  src/Controller/ControllerFactory.php
  src/Core/App.php
  src/Core/PluginCollection.php
  src/Datasource/ConnectionRegistry.php
  src/Http/Middleware/CspMiddleware.php
  src/I18n/DateFormatTrait.php
  src/Utility/Text.php
  src/View/ViewBuilder.php
Labels: cleanup, code-style
