Repository cakephp/cakephp, pull requests merged in 2022-03, with the labels that each got.

#16367 adjust command code references to use interface instead of implementing class
  src/Error/ConsoleErrorHandler.php
  src/TestSuite/ConsoleIntegrationTestTrait.php
  tests/TestCase/Command/CacheCommandsTest.php
  tests/TestCase/Command/CompletionCommandTest.php
  tests/TestCase/Command/PluginAssetsCommandsTest.php
  tests/TestCase/Command/PluginLoadCommandTest.php
  tests/TestCase/Command/PluginLoadedCommandTest.php
  tests/TestCase/Command/PluginUnloadCommandTest.php
  tests/TestCase/Command/RoutesCommandTest.php
  tests/TestCase/Console/Command/HelpCommandTest.php
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Console/CommandTest.php
  tests/TestCase/TestSuite/ConsoleIntegrationTestTraitTest.php
Labels: cleanup

#16369 fix CS errors
  src/ORM/Association/BelongsToMany.php
  src/ORM/Association/HasMany.php
  src/ORM/ResultSetFactory.php
  src/View/View.php
Labels: cleanup

#16355 Trim down public API of Connection.
  src/Database/Connection.php
  src/Database/Driver.php
  src/Database/DriverInterface.php
  src/Database/Log/LoggedQuery.php
  src/Database/Log/QueryLogger.php
  src/Database/Query.php
  src/Database/Retry/ReconnectStrategy.php
  src/Database/Statement/Statement.php
  src/Database/StatementInterface.php
  src/Database/composer.json
  src/Datasource/ConnectionInterface.php
  src/Datasource/composer.json
  src/TestSuite/ConnectionHelper.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Database/Driver/MysqlTest.php
  tests/TestCase/Database/Driver/PostgresTest.php
  tests/TestCase/Database/Driver/SqliteTest.php
  tests/TestCase/Database/Driver/SqlserverTest.php
  tests/TestCase/Database/DriverTest.php
  tests/TestCase/Database/Log/LoggedQueryTest.php
  tests/TestCase/Database/Log/QueryLoggerTest.php
  tests/TestCase/Database/Statement/StatementTest.php
  tests/TestCase/ORM/ResultSetFactoryTest.php
  tests/TestCase/TestSuite/ConnectionHelperTest.php
  tests/TestCase/TestSuite/Fixture/SchemaLoaderTest.php
  tests/test_app/TestApp/Database/Driver/StubDriver.php
Labels: database

#16379 Improve code readability.
  src/Database/Driver/SqlDialectTrait.php
Labels: cleanup

#16365 Use null coalescing assignment.
  psalm-baseline.xml
  src/Cache/Engine/FileEngine.php
  src/Collection/CollectionTrait.php
  src/Controller/Controller.php
  src/Core/Configure.php
  src/Core/Configure/Engine/IniConfig.php
  src/Core/Configure/Engine/JsonConfig.php
  src/Core/Configure/Engine/PhpConfig.php
  src/Database/Connection.php
  src/Database/Driver.php
  src/Database/Exception/NestedTransactionRollbackException.php
  src/Database/Expression/AggregateExpression.php
  src/Database/Expression/CaseStatementExpression.php
  src/Database/Expression/QueryExpression.php
  src/Database/Expression/WhenThenExpression.php
  src/Database/Expression/WindowExpression.php
  src/Database/Query.php
  src/Database/Statement/Statement.php
  src/Database/TypeMapTrait.php
  src/Error/ExceptionRenderer.php
  src/Event/EventDispatcherTrait.php
  src/Form/Form.php
  src/Http/BaseApplication.php
  src/Http/Client/Response.php
  src/Http/ResponseEmitter.php
  src/Http/Session/CacheSession.php
  src/I18n/DateFormatTrait.php
  src/I18n/DateTime.php
  src/I18n/I18n.php
  src/I18n/Number.php
  src/I18n/TranslatorRegistry.php
  src/Mailer/Mailer.php
  src/Mailer/Message.php
  src/ORM/Association/BelongsToMany.php
  src/ORM/Behavior/Translate/TranslateStrategyTrait.php
  src/ORM/EagerLoader.php
  src/ORM/Locator/LocatorAwareTrait.php
  src/ORM/Query.php
  src/ORM/RulesChecker.php
  src/ORM/Table.php
  src/Routing/Asset.php
  src/TestSuite/ConsoleIntegrationTestTrait.php
  src/TestSuite/StringCompareTrait.php
  src/Utility/CookieCryptTrait.php
  src/Utility/Security.php
  src/Utility/Text.php
  src/Validation/Validation.php
  src/View/Form/ArrayContext.php
  src/View/Helper/FormHelper.php
  src/View/JsonView.php
  src/View/View.php
  src/View/ViewBuilder.php
Labels: cleanup

#16383 Remove uneeded Statement::closeCursor() calls.
  src/Database/Connection.php
  src/Database/Schema/Collection.php
  src/Database/Schema/SqliteSchemaDialect.php
  src/Database/Statement/SqliteStatement.php
  src/ORM/Behavior/TreeBehavior.php
  src/ORM/Query.php
  src/ORM/Table.php
  src/TestSuite/ConnectionHelper.php
  src/TestSuite/Fixture/TestFixture.php
  tests/TestCase/TestSuite/TestFixtureTest.php
Labels: cleanup

#16394 Code cleanup.
  src/Controller/Controller.php
  src/Database/Expression/CaseExpressionTrait.php
  src/Error/ErrorLogger.php
  src/Error/ExceptionTrap.php
  src/Http/BaseApplication.php
  src/Http/Cookie/Cookie.php
  src/Http/Middleware/CsrfProtectionMiddleware.php
  src/Http/ResponseEmitter.php
  src/Http/ServerRequest.php
  src/Log/Engine/BaseLog.php
  src/ORM/Table.php
  src/TestSuite/ConnectionHelper.php
  src/TestSuite/ContainerStubTrait.php
  src/View/Form/EntityContext.php
Labels: cleanup

#16401 Deprecate Debugger features that are replaced by ErrorTrap
  psalm-baseline.xml
  src/Error/Debugger.php
  tests/TestCase/Error/DebuggerTest.php
  tests/TestCase/Error/ErrorHandlerTest.php
Labels: errorhandler, deprecations

#16403 Remove deprecated routes caching.
  src/Routing/Exception/FailedRouteCacheException.php
  src/Routing/Middleware/RoutingMiddleware.php
  tests/TestCase/Routing/Middleware/RoutingMiddlewareTest.php
  tests/test_app/TestApp/Middleware/UnserializableMiddleware.php
Labels: cleanup

#16411 Cleanup docblock
  src/Http/Response.php
Labels: cleanup
