Repository cakephp/cakephp, pull requests merged in 2022-11, with the labels that each got.

#16843 Get accessor just before it's checked/used
  src/Datasource/EntityTrait.php
Labels: enhancement, ORM

#16841 addHelper() for initialize()
  src/View/View.php
  tests/TestCase/View/ViewTest.php
  tests/test_app/TestApp/View/TestView.php
Labels: enhancement

#16858 Fix return type
  src/Http/ServerRequest.php
Labels: cleanup

#16860 5.x: DI delegate
  src/Core/ContainerInterface.php
Labels: enhancement

#16859 Drop Http\Uri class.
  src/Http/ServerRequest.php
  src/Http/ServerRequestFactory.php
  src/Http/Uri.php
  tests/TestCase/Http/UriTest.php
Labels: cleanup

#16861 Cleanup Router.
  src/Routing/Router.php
  tests/TestCase/Routing/RouterTest.php
Labels: cleanup

#16865 Use null coalescing assignment.
  src/Database/Driver/Sqlserver.php
  src/ORM/Query/SelectQuery.php
  src/View/ViewVarsTrait.php
Labels: cleanup

#16871 Decoupled connection roles from ConnectionManager
  src/Database/Connection.php
  src/Database/Driver.php
  src/Database/DriverInterface.php
  src/Database/Log/LoggedQuery.php
  src/Database/Log/QueryLogger.php
  src/Database/Query.php
  src/Database/Query/SelectQuery.php
  src/Database/QueryCompiler.php
  src/Database/Statement/BufferedStatement.php
  src/Database/Statement/StatementDecorator.php
  src/Database/TypeConverterTrait.php
  src/Datasource/ConnectionManager.php
  src/ORM/EagerLoader.php
  src/ORM/ResultSet.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Database/Log/LoggedQueryTest.php
  tests/TestCase/Database/Log/LoggingStatementTest.php
  tests/TestCase/Database/Log/QueryLoggerTest.php
  tests/TestCase/Database/QueryTest.php
  tests/TestCase/Datasource/ConnectionManagerTest.php
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/test_app/TestApp/Database/Driver/DisabledDriver.php
Labels: enhancement, database

#16880 4.next: add psalm template annotation
  src/Datasource/ResultSetInterface.php
  src/ORM/ResultSet.php
Labels: documentation

#16887 4.next: Add DI container to itself
  src/Http/BaseApplication.php
  tests/TestCase/Http/BaseApplicationTest.php
Labels: enhancement
