Repository cakephp/cakephp, pull requests merged in 2022-04, with the labels that each got.

#16450 Fix errors on invalid cookies
  src/Http/Cookie/CookieCollection.php
  tests/TestCase/Http/Cookie/CookieCollectionTest.php
Labels: http

#16366 added ability to set a command description
  src/Console/BaseCommand.php
  src/Console/Command/HelpCommand.php
  tests/TestCase/Console/Command/HelpCommandTest.php
  tests/test_app/TestApp/Command/DemoCommand.php
Labels: console

#16447 4.4 - Make ExceptionTrap handle old configuration better.
  psalm-baseline.xml
  src/Error/ExceptionRenderer.php
  src/Error/ExceptionTrap.php
  src/Error/Middleware/ErrorHandlerMiddleware.php
  src/Error/Renderer/WebExceptionRenderer.php
  src/TestSuite/IntegrationTestTrait.php
  tests/TestCase/Error/ExceptionTrapTest.php
  tests/TestCase/Error/Middleware/ErrorHandlerMiddlewareTest.php
Labels: RFC

#16464 Remove unnecessary variable assignment.
  src/Error/ErrorTrap.php
  src/Error/ExceptionTrap.php
Labels: cleanup

#16465 Remove deprecated code.
  psalm-baseline.xml
  src/Controller/Component/PaginatorComponent.php
  src/Error/ExceptionRenderer.php
  src/Error/ExceptionTrap.php
  src/Error/Renderer/WebExceptionRenderer.php
  tests/TestCase/Controller/Component/PaginatorComponentTest.php
  tests/TestCase/Error/ExceptionTrapTest.php
  tests/TestCase/Error/Renderer/WebExceptionRendererTest.php
  tests/TestCase/TestSuite/TestFixtureTest.php
  tests/test_app/TestApp/Error/Renderer/MyCustomExceptionRenderer.php
  tests/test_app/TestApp/Error/Renderer/TestAppsExceptionRenderer.php
Labels: deprecations
