Repository cakephp/cakephp, pull requests merged in 2022-05, with the labels that each got.

#16491 Allow php 8.2 tests to fail
  .github/workflows/ci.yml
Labels: php

#16492 Fix use of deprecated string interpolation
  src/Routing/RouteCollection.php
  tests/TestCase/Console/ShellTest.php
  tests/TestCase/Database/QueryTest.php
  tests/TestCase/Error/DebuggerTest.php
Labels: php

#16501 Fix Model.afterSaveCommit triggering inconsistency.
  src/ORM/Table.php
  tests/TestCase/ORM/RulesCheckerIntegrationTest.php
  tests/TestCase/ORM/TableTest.php
Labels: ORM

#16502 Use random string not bytes for CSRF token salt
  src/Http/Middleware/CsrfProtectionMiddleware.php
  tests/TestCase/Http/Middleware/CsrfProtectionMiddlewareTest.php
Labels: security, utility, session, middleware, backport, form

#16510 Add types to NegotiationRequiredView
  src/View/NegotiationRequiredView.php
Labels: php

#16513 PHP 8.1 polyfill no longer needed
  composer.json
Labels: testing

#16511 Convert all Query parameters to closures
  src/Database/IdentifierQuoter.php
  src/Database/Query.php
  src/Datasource/QueryInterface.php
  src/ORM/EagerLoader.php
  src/ORM/Query.php
Labels: php

#16509 Simplify FieldTypeConverter
  src/Database/FieldTypeConverter.php
  src/Database/Type/IntegerType.php
Labels: cleanup

#16514 Store event handlers as closures
  src/Event/EventManager.php
  tests/TestCase/Event/EventManagerTest.php
  tests/TestCase/ORM/BehaviorRegistryTest.php
Labels: events

#16516 Remove null parameter type hint that leads to foreach error
  src/TestSuite/IntegrationTestTrait.php
Labels: enhancement, documentation

#16530 Deprecate associating multiple methods with the same event
  src/Event/EventListenerInterface.php
  src/Event/EventManager.php
  tests/TestCase/Event/EventManagerTest.php
  tests/test_app/TestApp/TestCase/Event/CustomTestEventListenerInterface.php
  tests/test_app/TestApp/TestCase/Event/MultiMethodEventListenerInterface.php
Labels: events, deprecations
