Repository cakephp/cakephp, pull requests merged in 2022-07, with the labels that each got.

#16593 Remove unneeded PHP version checks.
  .github/workflows/ci.yml
  src/I18n/Number.php
  src/Mailer/Transport/MailTransport.php
  tests/TestCase/Cache/Engine/MemcachedEngineTest.php
  tests/TestCase/Mailer/Transport/MailTransportTest.php
  tests/TestCase/Utility/FilesystemTest.php
Labels: cleanup

#16600 Add compatibility shim for `errorLogger`
  src/Error/ErrorTrap.php
  tests/TestCase/Error/ErrorTrapTest.php
Labels: errorhandler, deprecations

#16604 fix TableLocator::get() with options throw exception if model mocked.
  src/Datasource/Locator/AbstractLocator.php
  tests/TestCase/ORM/Locator/TableLocatorTest.php
Labels: defect

#16618 Fix cache key generation.
  src/ORM/Table.php
  tests/TestCase/ORM/TableTest.php
Labels: defect

#16625 Remove redundant class type checks.
  src/Error/ErrorTrap.php
  src/Error/ExceptionTrap.php
  src/Http/Session.php
  src/ORM/AssociationCollection.php
  src/ORM/Table.php
  src/Routing/RouteBuilder.php
  tests/TestCase/Error/ErrorTrapTest.php
  tests/TestCase/Error/ExceptionTrapTest.php
  tests/TestCase/ORM/AssociationCollectionTest.php
  tests/TestCase/Routing/RouteBuilderTest.php
Labels: cleanup

#16627 Fixes fallback if a singular message isn't translated
  src/I18n/Translator.php
  tests/TestCase/I18n/I18nTest.php
Labels: i18n, defect

#16637 4.x cleanup variables before return
  src/Console/BaseCommand.php
  src/Console/ConsoleOptionParser.php
  src/Console/ShellDispatcher.php
  src/Database/Expression/WindowExpression.php
  src/Error/Debugger.php
  src/Error/Renderer/HtmlErrorRenderer.php
  src/Event/EventManager.php
  src/Filesystem/Filesystem.php
  src/Http/Middleware/CsrfProtectionMiddleware.php
  src/Http/Runner.php
  src/Http/ServerRequestFactory.php
  src/I18n/TranslatorRegistry.php
  src/ORM/EagerLoader.php
  src/Routing/Router.php
  src/TestSuite/IntegrationTestTrait.php
  src/TestSuite/MiddlewareDispatcher.php
  src/Utility/Text.php
  src/View/CellTrait.php
  src/View/Helper/BreadcrumbsHelper.php
  src/View/Helper/FormHelper.php
  src/View/StringTemplate.php
Labels: cleanup

#16633 Ensure TableLocator returns the same instance when using a table's registry alias.
  src/ORM/Locator/TableLocator.php
  tests/TestCase/ORM/Locator/TableLocatorTest.php
Labels: defect

#16638 5.x cleanup
  src/Controller/Controller.php
Labels: cleanup

#16645 Remove unused properties.
  src/Database/Query.php
Labels: cleanup

#16651 Fix up generic docblocks.
  src/Datasource/RepositoryInterface.php
  src/ORM/LazyEagerLoader.php
  src/ORM/Table.php
Labels: documentation

#16654 Fix outdated Log Readme
  src/Log/README.md
Labels: documentation, log
