Repository cakephp/cakephp, pull requests merged in 2023-08, with the labels that each got.

#17226 4.x: fix deprecation notice related to Chronos 2.4
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm-baseline.xml
  src/I18n/DateFormatTrait.php
  src/I18n/RelativeTimeFormatter.php
  src/View/Helper/TimeHelper.php
  tests/TestCase/View/Helper/TimeHelperTest.php
  tests/phpstan-baseline.neon
  tests/phpstan.neon
Labels: deprecations

#17225 Add CookieCollection::__get()
  src/Http/Cookie/CookieCollection.php
  tests/TestCase/Http/Cookie/CookieCollectionTest.php
Labels: enhancement, http

#17230 allow manually dispatching ci workflow
  .github/workflows/ci.yml
Labels: github_actions

#17228 Added method getError() to Form #17219
  src/Form/Form.php
  tests/TestCase/Form/FormTest.php
Labels: enhancement, form

#17233 Fix BasePlugin.php enable hook typo
  src/Core/BasePlugin.php
Labels: documentation

#17235 5.x: remove ComponentRegistry from DIC
  src/Http/BaseApplication.php
  tests/TestCase/Http/BaseApplicationTest.php
Labels: cleanup, dependency injection

#17240 5.x: PHP 8.3 fix
  tests/TestCase/Error/DebuggerTest.php
Labels: testing

#17239 5.x: convert `returnSelf()`
  tests/TestCase/ORM/Association/HasManyTest.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/TestSuite/TestFixtureTest.php
Labels: testing, deprecations

#17238 5.x: convert `returnValue()` to `willReturn()`
  tests/TestCase/Cache/CacheTest.php
  tests/TestCase/Command/PluginAssetsCommandsTest.php
  tests/TestCase/Command/SchemaCacheCommandsTest.php
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Console/CommandTest.php
  tests/TestCase/Console/ConsoleIoTest.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Database/Driver/MysqlTest.php
  tests/TestCase/Database/Driver/PostgresTest.php
  tests/TestCase/Database/Driver/SqliteTest.php
  tests/TestCase/Database/Driver/SqlserverTest.php
  tests/TestCase/Database/DriverTest.php
  tests/TestCase/Database/Schema/MysqlSchemaTest.php
  tests/TestCase/Database/Schema/PostgresSchemaTest.php
  tests/TestCase/Database/Schema/SqliteSchemaTest.php
  tests/TestCase/Database/Schema/SqlserverSchemaTest.php
  tests/TestCase/Database/Type/StringTypeTest.php
  tests/TestCase/Datasource/Paging/PaginatorTestTrait.php
  tests/TestCase/Error/Middleware/ErrorHandlerMiddlewareTest.php
  tests/TestCase/Event/EventManagerTest.php
  tests/TestCase/Http/Client/Auth/DigestTest.php
  tests/TestCase/Http/ClientTest.php
  tests/TestCase/Mailer/MailerTest.php
  tests/TestCase/Mailer/Transport/SmtpTransportTest.php
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/ORM/Association/HasManyTest.php
  tests/TestCase/ORM/AssociationCollectionTest.php
  tests/TestCase/ORM/AssociationProxyTest.php
  tests/TestCase/ORM/AssociationTest.php
  tests/TestCase/ORM/BehaviorRegistryTest.php
  tests/TestCase/ORM/EagerLoaderTest.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/ORM/Query/SelectQueryTest.php
  tests/TestCase/ORM/ResultSetFactoryTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/Routing/Route/RouteTest.php
  tests/TestCase/Routing/RouterTest.php
  tests/TestCase/TestSuite/Fixture/FixtureHelperTest.php
  tests/TestCase/TestSuite/TestCaseTest.php
  tests/TestCase/TestSuite/TestFixtureTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: testing, deprecations

#17237 5.x: remove `addMethods(['table'])` from tests
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/ORM/AssociationCollectionTest.php
Labels: testing, deprecations

#17241 5.x: convert `returnCallback()` to `willReturnCallback()`
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Database/Driver/SqliteTest.php
  tests/TestCase/Database/Schema/MysqlSchemaTest.php
  tests/TestCase/Database/Schema/PostgresSchemaTest.php
  tests/TestCase/Database/Schema/SqliteSchemaTest.php
  tests/TestCase/Database/Schema/SqlserverSchemaTest.php
  tests/TestCase/Http/ResponseEmitterTest.php
  tests/TestCase/Http/ServerTest.php
  tests/TestCase/Mailer/Transport/SmtpTransportTest.php
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/Routing/Middleware/RoutingMiddlewareTest.php
  tests/TestCase/Validation/ValidatorTest.php
Labels: testing, deprecations

#17242 5.x: convert `onConsecutiveCalls()` to `willReturn()`
  tests/TestCase/Console/ConsoleIoTest.php
  tests/TestCase/Database/Driver/PostgresTest.php
  tests/TestCase/Database/Driver/SqlserverTest.php
  tests/TestCase/Database/DriverTest.php
  tests/TestCase/Http/ClientTest.php
  tests/TestCase/Mailer/Transport/SmtpTransportTest.php
  tests/TestCase/ORM/Query/SelectQueryTest.php
Labels: testing, deprecations

#17243 5.x: convert `getObjectForTrait()` to anonymous class
  tests/TestCase/Core/StaticConfigTraitTest.php
  tests/TestCase/Event/EventDispatcherTraitTest.php
  tests/TestCase/Log/LogTraitTest.php
  tests/TestCase/ORM/Locator/LocatorAwareTraitTest.php
Labels: testing, deprecations

#17244 5.x: convert `getMockForAbstractClass()` to anonymous class
  tests/TestCase/Cache/CacheTest.php
  tests/TestCase/Console/Command/HelpCommandTest.php
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Database/DriverTest.php
  tests/TestCase/Database/Query/UpdateQueryTest.php
  tests/TestCase/Database/QueryTest.php
  tests/TestCase/Http/BaseApplicationTest.php
  tests/TestCase/Http/MiddlewareApplicationTest.php
  tests/TestCase/Http/ServerTest.php
  tests/TestCase/I18n/TranslatorRegistryTest.php
  tests/test_app/TestApp/Database/Driver/StubDriver.php
Labels: testing, deprecations

#17189 [5.x] Word validation error messages more precisely
  src/Validation/Validator.php
  tests/TestCase/Validation/NoI18nValidator.php
  tests/TestCase/Validation/ValidatorTest.php
Labels: enhancement, validation

#17246 5.x: Convert `addMethods()` to anonymous or test classes or Mockery
  composer.json
  src/TestSuite/TestCase.php
  tests/TestCase/Collection/CollectionTest.php
  tests/TestCase/Command/PluginAssetsCommandsTest.php
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Console/CommandTest.php
  tests/TestCase/Database/ConnectionTest.php
  tests/TestCase/Database/Driver/SqliteTest.php
  tests/TestCase/Database/Schema/MysqlSchemaTest.php
  tests/TestCase/Database/Type/StringTypeTest.php
  tests/TestCase/Datasource/Paging/PaginatorTestTrait.php
  tests/TestCase/Form/FormTest.php
  tests/TestCase/Http/ServerTest.php
  tests/TestCase/Mailer/MailerDefaultProfileRestorationTest.php
  tests/TestCase/Mailer/MailerSendActionTest.php
  tests/TestCase/Mailer/MailerSendFailsEmailIsReset.php
  tests/TestCase/Mailer/MailerSendWithUnsetTemplateDefaultsToActionNameTest.php
  tests/TestCase/Mailer/MailerTest.php
  tests/TestCase/ORM/Association/BelongsToManySaveAssociatedOnlyEntitiesAppendTest.php
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/ORM/Association/BelongsToTest.php
  tests/TestCase/ORM/Association/HasManyTest.php
  tests/TestCase/ORM/Association/HasOneTest.php
  tests/TestCase/ORM/AssociationProxyTest.php
  tests/TestCase/ORM/BehaviorRegistryTest.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/ORM/TableGetWithCustomFinderTest.php
  tests/TestCase/ORM/TableImplementedEventsTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/ORM/TableValidationWithBadDefinerTest.php
  tests/TestCase/ORM/TableValidationWithDefinerTest.php
  tests/TestCase/Validation/ValidatorTest.php
Labels: testing, deprecations

#17255 5.x: don't require mockery via TestCase::teardown
  src/TestSuite/TestCase.php
Labels: testing

#17251 Use associative array / named args when invoking cell methods.
  src/View/CellTrait.php
  tests/TestCase/View/CellTest.php
Labels: enhancement

#17208 [5.x] modified entity getOriginal behavior
  src/Datasource/EntityInterface.php
  src/Datasource/EntityTrait.php
  src/ORM/Entity.php
  src/ORM/Marshaller.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorEavTest.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/ORM/Query/QueryRegressionTest.php
  tests/TestCase/ORM/TableTest.php
Labels: enhancement
