Repository cakephp/cakephp, pull requests merged in 2023-04, with the labels that each got.

#17085 Remove constants dropped in #17063.
  config/bootstrap.php
  src/basics.php
  tests/TestCase/BasicsTest.php
  tests/TestCase/Mailer/MailerTest.php
  tests/TestCase/Mailer/MessageTest.php
  tests/TestCase/TestSuite/EmailTraitTest.php
Labels: cleanup

#17095 4.x: handle numeric keys in cookies being parsed from the server request
  src/Http/Cookie/CookieCollection.php
  tests/TestCase/Http/Cookie/CookieCollectionTest.php
  tests/TestCase/Http/ServerRequestTest.php
Labels: bug

#17103 Catch all exceptions when generating sql for Query::__debugInfo()
  src/Database/Query.php
Labels: bug

#17102 4.next: update psalm to v5
  .phive/phars.xml
  phpstan-baseline.neon
  psalm-baseline.xml
  psalm.xml
  src/Collection/Collection.php
  src/Collection/CollectionInterface.php
  src/Collection/Iterator/MapReduce.php
  src/Collection/Iterator/NestIterator.php
  src/Collection/Iterator/NoChildrenIterator.php
  src/Collection/Iterator/TreeIterator.php
  src/Collection/Iterator/TreePrinter.php
  src/Collection/Iterator/UnfoldIterator.php
  src/Console/CommandCollection.php
  src/Core/ObjectRegistry.php
  src/Core/PluginCollection.php
  src/Database/Query.php
  src/Database/SchemaCache.php
  src/Database/Statement/BufferedStatement.php
  src/Database/Statement/PDOStatement.php
  src/Database/Statement/SqlserverStatement.php
  src/Database/Statement/StatementDecorator.php
  src/Datasource/EntityInterface.php
  src/Datasource/ResultSetDecorator.php
  src/Event/EventList.php
  src/Http/CallbackStream.php
  src/Http/Client/Adapter/Stream.php
  src/Http/Cookie/CookieCollection.php
  src/Http/ResponseEmitter.php
  src/Http/ServerRequest.php
  src/Http/ServerRequestFactory.php
  src/Http/Session.php
  src/I18n/Parser/PoFileParser.php
  src/Log/LogEngineRegistry.php
  src/ORM/AssociationCollection.php
  src/ORM/Behavior/Translate/ShadowTableStrategy.php
  src/ORM/Marshaller.php
  src/TestSuite/Fixture/FixtureManager.php
  src/TestSuite/TestCase.php
  src/Utility/Xml.php
  src/Validation/ValidationSet.php
  src/Validation/Validator.php
  src/View/Cell.php
  src/View/Exception/MissingCellTemplateException.php
  src/View/Exception/MissingTemplateException.php
  src/View/HelperRegistry.php
  src/View/Widget/RadioWidget.php
  src/View/XmlView.php
Labels: enhancement

#17117 4.next: middleware DIC
  .github/workflows/ci.yml
  src/Controller/ControllerFactory.php
  src/Http/MiddlewareQueue.php
  src/Http/Server.php
  src/Routing/Middleware/RoutingMiddleware.php
  tests/TestCase/Http/MiddlewareQueueTest.php
  tests/TestCase/Http/ServerTest.php
  tests/TestCase/Routing/Middleware/RoutingMiddlewareTest.php
Labels: dependency injection

#17118 4.next: fix DateType not properly handling ChronosDate instances with different timezones
  src/Database/Type/DateType.php
  tests/TestCase/Database/Type/DateTimeTypeTest.php
  tests/TestCase/Database/Type/DateTypeTest.php
Labels: database, bug

#17120 Code cleanup
  src/Controller/ComponentRegistry.php
  src/Datasource/EntityTrait.php
  src/ORM/ResultSetFactory.php
  src/ORM/Table.php
Labels: cleanup
