Repository cakephp/cakephp, pull requests merged in 2023-09, with the labels that each got.

#17261 5.x: fix aliasing non default test datasource
  src/TestSuite/ConnectionHelper.php
  tests/TestCase/TestSuite/ConnectionHelperTest.php
Labels: datasource, testing

#17267 Restore extractOriginal() behavior
  src/Datasource/EntityTrait.php
  tests/TestCase/ORM/EntityTest.php
Labels: bug

#17280 5.x: minor test cleanup
  tests/TestCase/Console/CommandRunnerTest.php
  tests/TestCase/Database/Driver/MysqlTest.php
  tests/TestCase/Database/Schema/MysqlSchemaTest.php
  tests/TestCase/Database/Schema/PostgresSchemaTest.php
  tests/TestCase/Database/Schema/SqliteSchemaTest.php
  tests/TestCase/Database/Schema/SqlserverSchemaTest.php
  tests/TestCase/Datasource/Paging/PaginatorTestTrait.php
  tests/TestCase/Http/Client/Auth/OauthTest.php
  tests/TestCase/Http/ResponseTest.php
  tests/TestCase/Http/ServerTest.php
  tests/TestCase/ORM/Behavior/TranslateBehaviorEavTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/TestSuite/TestCaseTest.php
  tests/test_app/Plugin/TestPlugin/src/Http/Session/TestPluginSession.php
  tests/test_app/TestApp/ApplicationWithDefaultRoutes.php
  tests/test_app/TestApp/ApplicationWithExceptionsInMiddleware.php
  tests/test_app/TestApp/Database/Type/OrderedUuidType.php
  tests/test_app/TestApp/Http/MiddlewareApplication.php
  tests/test_app/TestApp/Http/Session/TestAppLibSession.php
  tests/test_app/TestApp/Model/Entity/ProtectedUser.php
  tests/test_app/TestApp/TestCase/Event/CustomTestEventListenerInterface.php
  tests/test_app/templates/Posts/json/index.php
  tests/test_app/templates/TestsApps/index.php
Labels: testing, cleanup

#17271 Document the changed behavior of extractOriginal() instead.
  src/Datasource/EntityTrait.php
  tests/TestCase/ORM/EntityTest.php
Labels: enhancement

#17290 5.x: add deprecation warning to `getMockForModel` if `addMethods` is used
  src/TestSuite/TestCase.php
Labels: testing

#17301 Fix up exception message and docs.
  src/Controller/Controller.php
  src/Datasource/ModelAwareTrait.php
  src/Error/ExceptionTrap.php
  src/Routing/Router.php
  src/View/Form/ArrayContext.php
Labels: bug

#17303 Fix for SortIterator with support for Chronos instances
  src/Collection/Iterator/SortIterator.php
  tests/TestCase/Collection/Iterator/SortIteratorTest.php
Labels: bug

#17324 Update docs URLs
  src/Cache/README.md
  src/Collection/README.md
  src/Command/CacheClearCommand.php
  src/Command/CacheClearGroupCommand.php
  src/Command/CacheClearallCommand.php
  src/Command/CacheListCommand.php
  src/Command/ServerCommand.php
  src/Console/ConsoleIo.php
  src/Console/Exception/ConsoleException.php
  src/Console/Exception/MissingOptionException.php
  src/Console/Exception/StopException.php
  src/Console/README.md
  src/Controller/Component.php
  src/Controller/Controller.php
  src/Core/App.php
  src/Core/Configure.php
  src/Core/Plugin.php
  src/Core/README.md
  src/Core/functions.php
  src/Core/functions_global.php
  src/Error/Debugger.php
  src/Error/functions.php
  src/Error/functions_global.php
  src/Event/README.md
  src/Form/README.md
  src/Http/Middleware/SecurityHeadersMiddleware.php
  src/Http/README.md
  src/I18n/Number.php
  src/I18n/README.md
  src/I18n/functions.php
  src/I18n/functions_global.php
  src/Log/README.md
  src/ORM/Behavior/TranslateBehavior.php
  src/ORM/README.md
  src/ORM/Table.php
  src/Utility/CookieCryptTrait.php
  src/Utility/Hash.php
  src/Utility/Inflector.php
  src/Utility/README.md
  src/Utility/Security.php
  src/Utility/Text.php
  src/Validation/README.md
  src/Validation/Validator.php
  src/View/Helper/FormHelper.php
  src/View/Helper/HtmlHelper.php
  src/View/Helper/NumberHelper.php
  src/View/Helper/PaginatorHelper.php
  src/View/Helper/TextHelper.php
  src/View/Helper/TimeHelper.php
  tests/TestCase/Log/LogTest.php
  tests/TestCase/Utility/InflectorTest.php
  tests/test_app/templates/Pages/home.php
Labels: cleanup
