Repository cakephp/cakephp, pull requests merged in 2023-12, with the labels that each got.

#17462 Do not set timezone on ChronosDate when marshalling into DateTime field
  src/Database/Type/DateTimeType.php
  tests/TestCase/Database/Type/DateTimeTypeTest.php
Labels: defect, database, deprecations, dependencies

#17464 5.x: adjust docs for decimal validation rule
  src/Validation/Validation.php
Labels: validation, documentation

#17468 Switch pragma function based on SQLite version.
  src/Database/Schema/SqliteSchemaDialect.php
Labels: database

#17470 Add missing method to interface as soft-req
  src/Datasource/EntityInterface.php
Labels: bug

#17458 5.next: add expect log feature to TestSuite
  src/TestSuite/LogTestTrait.php
  tests/TestCase/TestSuite/LogTestTraitTest.php
Labels: enhancement, testing, log

#17467 FIX: exception trap: handle Exception.beforeRender event being stopped or returning no result
  src/Error/ExceptionTrap.php
  tests/TestCase/Error/ExceptionTrapTest.php
Labels: bug

#17476 Less cloaking and more strict comparison where possible.
  src/Cache/Engine/ApcuEngine.php
  src/Cache/Engine/MemcachedEngine.php
  src/Collection/Iterator/MapReduce.php
  src/Command/I18nExtractCommand.php
  src/Command/ServerCommand.php
  src/Console/ConsoleOptionParser.php
  src/Controller/Controller.php
  src/Core/TestSuite/ContainerStubTrait.php
  src/Database/Expression/CaseStatementExpression.php
  src/Database/Expression/ValuesExpression.php
  src/Database/Log/LoggedQuery.php
  src/Mailer/Mailer.php
  src/Mailer/Message.php
  src/Network/Socket.php
  src/ORM/EagerLoader.php
  src/ORM/Query/SelectQuery.php
  src/Routing/Route/EntityRoute.php
  src/Routing/Route/Route.php
  src/TestSuite/Fixture/TestFixture.php
  src/View/Cell.php
  src/View/CellTrait.php
  src/View/StringTemplate.php
  src/View/View.php
  tests/test_app/TestApp/Auth/TestAuthenticate.php
Labels: cleanup

#17481 4.x: fix deprecation warning
  src/TestSuite/Constraint/Console/ContentsContain.php
Labels: deprecations

#17154 [4.4] Use array values of app paths returned by App::path() for I18n commands
  src/Command/I18nExtractCommand.php
  src/Command/I18nInitCommand.php
  tests/TestCase/Command/I18nCommandTest.php
  tests/TestCase/Command/I18nExtractCommandTest.php
  tests/TestCase/I18n/MessagesFileLoaderTest.php
  tests/TestCase/Utility/XmlTest.php
  tests/TestCase/Validation/ValidationTest.php
  tests/TestCase/View/Helper/NumberHelperTest.php
  tests/TestCase/View/Helper/TextHelperTest.php
Labels: core

#17503 Run test suite with PHP 8.3
  .github/workflows/ci.yml
  tests/TestCase/Error/DebuggerTest.php
Labels: testing

#17512 Use consistent uppercase for enum case def.
  tests/TestCase/Validation/ValidationTest.php
  tests/TestCase/Validation/ValidatorTest.php
  tests/test_app/TestApp/Model/Enum/NonBacked.php
Labels: cleanup

#17507 Fix up int and string enum types
  src/Database/Type/EnumType.php
  tests/TestCase/Database/Type/EnumTypeTest.php
Labels: bug
