Repository cakephp/cakephp, pull requests merged in 2023-01, with the labels that each got.

#16921 remove default association config from tests
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/ORM/Association/BelongsToTest.php
  tests/TestCase/ORM/Association/HasOneTest.php
  tests/TestCase/ORM/QueryRegressionTest.php
  tests/TestCase/ORM/QueryTest.php
  tests/TestCase/ORM/TableTest.php
Labels: cleanup

#16922 Change return type for TypeInterface::toStatement().
  src/Database/Type/BaseType.php
  src/Database/Type/BinaryType.php
  src/Database/Type/BinaryUuidType.php
  src/Database/Type/BoolType.php
  src/Database/Type/DateTimeType.php
  src/Database/Type/DecimalType.php
  src/Database/Type/EnumType.php
  src/Database/Type/FloatType.php
  src/Database/Type/IntegerType.php
  src/Database/Type/JsonType.php
  src/Database/Type/StringType.php
  src/Database/TypeInterface.php
Labels: database

#16930 Allow specifying default value when converting to associative form.
  src/Utility/Hash.php
  tests/TestCase/Utility/HashTest.php
Labels: enhancement

#16937 Fix up TypeError cases found by PHPStan level 8
  src/View/Exception/MissingTemplateException.php
  src/View/Form/ArrayContext.php
  src/View/Form/EntityContext.php
  src/View/Helper/FormHelper.php
  src/View/Helper/HtmlHelper.php
  src/View/Helper/PaginatorHelper.php
  src/View/Helper/TextHelper.php
  src/View/JsonView.php
  src/View/View.php
  src/View/ViewBlock.php
  src/View/XmlView.php
Labels: cleanup

#16936 Fix up console output to be empty.
  src/Console/ConsoleOutput.php
Labels: bug

#16941 3.x is not supported anymore
  .github/SECURITY.md
Labels: documentation

#16940 Fix up dead code bug
  src/Utility/Text.php
Labels: cleanup

#16939 Fix up TypeError cases found by PHPStan level 7/8
  psalm-baseline.xml
  psalm.xml
  src/Cache/Engine/FileEngine.php
  src/Command/I18nExtractCommand.php
  src/Command/I18nInitCommand.php
  src/Console/Command/HelpCommand.php
  src/Console/CommandScanner.php
  src/Controller/Controller.php
  src/Core/BasePlugin.php
  src/Core/Configure/Engine/IniConfig.php
  src/Core/Configure/Engine/JsonConfig.php
  src/Core/ObjectRegistry.php
  src/Core/functions.php
  src/Database/Driver.php
  src/Database/Type/BinaryUuidType.php
  src/Database/Type/DateTimeType.php
  src/Database/Type/EnumType.php
  src/Error/Debugger.php
  src/Http/Client.php
  src/Http/Client/FormData.php
  src/Http/Client/Response.php
  src/Http/Response.php
  src/Http/ServerRequestFactory.php
  src/Http/Session.php
  src/ORM/Association/BelongsToMany.php
  src/ORM/Behavior/CounterCacheBehavior.php
  src/Utility/Filesystem.php
  src/Validation/Validation.php
  src/Validation/ValidationRule.php
  src/Validation/Validator.php
Labels: cleanup

#16942 5.x: add requestAsJson method to IntegrationTestTrait
  src/TestSuite/IntegrationTestTrait.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
Labels: testing

#16945 Fix up TypeError cases found by PHPStan level 7/8
  src/Database/Driver/Sqlserver.php
  src/Database/Expression/CommonTableExpression.php
  src/Database/Expression/ComparisonExpression.php
  src/Database/Expression/FunctionExpression.php
  src/Database/Log/LoggedQuery.php
  src/Database/Query.php
  src/Database/Query/SelectQuery.php
  src/Datasource/EntityTrait.php
  src/Datasource/Paging/NumericPaginator.php
  src/ORM/Behavior/CounterCacheBehavior.php
  src/ORM/Behavior/Translate/EavStrategy.php
  src/ORM/Behavior/Translate/ShadowTableStrategy.php
  src/ORM/Behavior/TranslateBehavior.php
  src/ORM/Behavior/TreeBehavior.php
  src/ORM/BehaviorRegistry.php
  src/ORM/EagerLoader.php
  src/ORM/LazyEagerLoader.php
  src/ORM/Marshaller.php
  src/ORM/Query/CommonQueryTrait.php
  src/ORM/ResultSetFactory.php
  src/ORM/Table.php
Labels: cleanup

#16948 Fix up TypeError cases found by PHPStan level 7/8: ORM
  src/ORM/Association.php
  src/ORM/Association/BelongsTo.php
  src/ORM/Association/BelongsToMany.php
  src/ORM/Association/DependentDeleteHelper.php
  src/ORM/Association/HasMany.php
  src/ORM/Association/HasOne.php
  src/ORM/Association/Loader/SelectLoader.php
  src/ORM/EagerLoader.php
  src/ORM/Table.php
  tests/TestCase/Core/Configure/Engine/JsonConfigTest.php
Labels: cleanup

#16946 Fix up TypeError cases for PHPStan level 8
  src/Cache/Cache.php
  src/Cache/CacheEngine.php
  src/Cache/CacheRegistry.php
  src/Cache/Engine/MemcachedEngine.php
  src/Collection/CollectionTrait.php
  src/Command/Helper/TableHelper.php
  src/Command/I18nExtractCommand.php
  src/Console/BaseCommand.php
  src/Console/CommandCollection.php
  src/Console/ConsoleInput.php
  src/Console/ConsoleInputArgument.php
  src/Console/ConsoleOptionParser.php
  src/Console/ConsoleOutput.php
  src/Core/App.php
  src/Core/Configure/Engine/JsonConfig.php
  src/Core/StaticConfigTrait.php
  src/Error/Debug/HtmlFormatter.php
  src/Error/Debugger.php
  src/Event/EventManager.php
  src/Form/Form.php
  src/Form/FormProtector.php
  src/Http/Client/Auth/Oauth.php
  src/Http/Middleware/BodyParserMiddleware.php
  src/Http/Response.php
  src/Http/ResponseEmitter.php
  src/Http/ServerRequest.php
  src/I18n/DateFormatTrait.php
  src/I18n/Number.php
  src/I18n/Parser/MoFileParser.php
  src/I18n/RelativeTimeFormatter.php
  src/Log/Engine/BaseLog.php
  src/Log/Engine/FileLog.php
  src/Log/LogEngineRegistry.php
  src/Mailer/Message.php
  src/Mailer/Transport/SmtpTransport.php
  src/Mailer/TransportFactory.php
  src/Routing/Asset.php
  src/Routing/Middleware/AssetMiddleware.php
  src/Routing/Route/Route.php
  src/Routing/Router.php
  src/TestSuite/Fixture/SchemaLoader.php
  src/TestSuite/TestCase.php
  src/Utility/Crypto/OpenSsl.php
  src/Utility/Hash.php
  src/Utility/Inflector.php
  src/Utility/Security.php
  src/Utility/Text.php
  src/Utility/Xml.php
  src/Validation/RulesProvider.php
  src/Validation/ValidationRule.php
  src/Validation/Validator.php
  src/View/Form/FormContext.php
  src/View/Widget/SelectBoxWidget.php
  src/View/XmlView.php
  tests/TestCase/Cache/CacheTest.php
  tests/TestCase/Command/CacheCommandsTest.php
  tests/TestCase/Core/Configure/Engine/JsonConfigTest.php
  tests/TestCase/Validation/ValidationRuleTest.php
Labels: cleanup

#16949 4.x: i18n extract - check if folder exists before recursively checking php files
  src/Command/I18nExtractCommand.php
  tests/TestCase/Command/I18nExtractCommandTest.php
Labels: bug

#16950 Fix up TypeError cases found by PHPStan level 8
  src/Collection/Iterator/TreeIterator.php
  src/Console/ConsoleOutput.php
  src/Core/StaticConfigTrait.php
  src/Database/Schema/SqliteSchemaDialect.php
  src/Event/EventManager.php
  src/Http/Client/Adapter/Stream.php
  src/Http/Cookie/Cookie.php
  src/I18n/Parser/MoFileParser.php
  src/I18n/Parser/PoFileParser.php
  src/Network/Socket.php
Labels: cleanup

#16951 Fix up TypeError cases found by PHPStan level 8
  src/Console/BaseCommand.php
  src/Console/ConsoleOutput.php
  src/Database/Driver/Postgres.php
  src/Database/Type/DateType.php
  src/Database/Type/TimeType.php
  src/Event/EventManager.php
  src/I18n/DateFormatTrait.php
  src/I18n/Parser/MoFileParser.php
Labels: cleanup

#16955 Fix up TypeError cases found by PHPStan level 8
  src/Console/BaseCommand.php
  src/TestSuite/TestCase.php
Labels: cleanup

#16957 Update Slack link
  .github/CONTRIBUTING.md
  README.md
Labels: documentation

#16959 Fix up Stan issues.
  composer.json
  src/Controller/Controller.php
  src/Error/Debugger.php
  src/Http/Cookie/Cookie.php
  src/I18n/Parser/PoFileParser.php
Labels: cleanup

#16964 Set PHPStan to level 8 now using baseline.
  README.md
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: cleanup

#16966 Add validation script not to miss deprecation aliases.
  .github/workflows/ci.yml
  contrib/validate-deprecation-aliases.php
Labels: deprecations

#16958 5.x: add a comment to a query instance
  src/Database/PostgresCompiler.php
  src/Database/Query.php
  src/Database/Query/DeleteQuery.php
  src/Database/Query/InsertQuery.php
  src/Database/Query/SelectQuery.php
  src/Database/Query/UpdateQuery.php
  src/Database/QueryCompiler.php
  src/Database/SqlserverCompiler.php
  tests/TestCase/Database/QueryCompilerTest.php
  tests/TestCase/Database/QueryTest.php
Labels: enhancement, database

#16977 Fix up issues detected by IDE
  src/Console/HelpFormatter.php
  src/Core/Configure.php
  src/Core/PluginCollection.php
  src/Core/TestSuite/ContainerStubTrait.php
  src/Database/Driver.php
  src/Database/Statement/Statement.php
  src/Database/Type/DateTimeType.php
  src/Database/Type/DateType.php
  src/Database/Type/TimeType.php
  src/Datasource/ConnectionInterface.php
  src/Datasource/Paging/NumericPaginator.php
  src/Datasource/RulesAwareTrait.php
  src/Http/Client.php
  src/Http/MiddlewareQueue.php
  src/Http/ServerRequest.php
  src/Mailer/Message.php
  src/Mailer/Transport/SmtpTransport.php
  src/ORM/Marshaller.php
  src/ORM/Table.php
  src/Routing/Route/Route.php
  src/TestSuite/Fixture/FixtureHelper.php
  src/TestSuite/TestCase.php
  src/Utility/Hash.php
  src/View/Form/ArrayContext.php
  src/View/Helper/FormHelper.php
  src/View/Helper/HtmlHelper.php
  src/View/Helper/UrlHelper.php
  src/View/View.php
  templates/element/exception_stack_trace_nav.php
Labels: cleanup

#16978 Fix up issues detected by IDE
  contrib/validate-deprecation-aliases.php
  src/Command/CompletionCommand.php
  src/Command/VersionCommand.php
  src/Console/BaseCommand.php
  src/Console/Command/HelpCommand.php
  src/Console/Exception/MissingOptionException.php
  src/Database/Expression/CommonTableExpression.php
  src/Database/Expression/FunctionExpression.php
  src/Database/Expression/QueryExpression.php
  src/Database/FunctionsBuilder.php
  src/Database/Query.php
  src/Datasource/ConnectionManager.php
  src/Datasource/EntityTrait.php
  src/Datasource/Paging/NumericPaginator.php
  src/Error/Debug/PropertyNode.php
  src/Error/Debugger.php
  src/Http/ServerRequest.php
  src/I18n/DateFormatTrait.php
  src/Mailer/Transport/SmtpTransport.php
  src/Routing/RouteBuilder.php
  src/TestSuite/IntegrationTestTrait.php
  src/Utility/Crypto/OpenSsl.php
  src/Utility/MergeVariablesTrait.php
  src/View/View.php
  templates/Error/invalid_parameter.php
  templates/element/dev_error_stacktrace.php
Labels: cleanup

#16980 Fix key name
  src/Controller/ControllerFactory.php
Labels: bug

#16969 Add ability to use custom po files inside plugins
  src/I18n/MessagesFileLoader.php
  tests/TestCase/I18n/I18nTest.php
  tests/test_app/Plugin/Company/TestPluginThree/resources/locales/en/custom.po
Labels: enhancement

#16975 Numeric assoc keys can happen to be int.
  src/Core/StaticConfigTrait.php
Labels: bug
