Repository cakephp/cakephp, pull requests merged in 2023-03, with the labels that each got.

#17056 Cleanup not needed tearDown part.
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: cleanup

#17050 4.5 Prototype of result set deprecations.
  src/Datasource/QueryTrait.php
  src/ORM/Query.php
  tests/TestCase/ORM/QueryTest.php
Labels: deprecations

#17051 4.next: Allow Route Path params inside string representation
  src/Routing/Router.php
  tests/TestCase/Routing/RouterTest.php
Labels: routing

#17079 Fix DateTimeType::manyToPHP() with int value
  src/Database/Type/DateTimeType.php
  tests/TestCase/Database/Type/DateTimeTypeTest.php
  tests/TestCase/Database/Type/DateTypeTest.php
Labels: bug
