Repository cakephp/cakephp, pull requests merged in 2023-11, with the labels that each got.

#17399 Remove not needed silencing.
  src/View/Helper/FormHelper.php
Labels: documentation, testing

#17400 Add Interface for enum labels.
  src/Database/Type/EnumLabelInterface.php
  src/View/Helper/FormHelper.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/test_app/TestApp/Model/Enum/ArticleStatusLabelInterface.php
Labels: enhancement

#17404 Modify TimeHelper::format to accept arrays for the parameter $format
  src/View/Helper/TimeHelper.php
  tests/TestCase/View/Helper/TimeHelperTest.php
Labels: enhancement

#17406 Removed deprecated tag.
  src/Datasource/ModelAwareTrait.php
Labels: cleanup

#17409 Clean up old messages/docs.
  src/ORM/TableRegistry.php
Labels: documentation, cleanup

#17410 Clean up PHPStan baseline.
  phpstan-baseline.neon
  src/Validation/Validation.php
Labels: cleanup

#17411 Clean up PHPStan baseline. Fix merge issues.
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Console/CommandCollection.php
  src/Console/HelperRegistry.php
Labels: bug

#17417 Use PHP 8.3 for max now.
  .github/workflows/ci.yml
Labels: cleanup

#17424 Fix notice
  src/Datasource/ConnectionManager.php
Labels: bug

#17427 Better exception output on Type classes.
  src/Database/Type/BoolType.php
  src/Database/Type/DecimalType.php
  src/Database/Type/EnumType.php
  src/Database/Type/IntegerType.php
  src/Database/Type/StringType.php
  tests/TestCase/ORM/MarshallerTest.php
Labels: enhancement

#17421 Shim binary16 support for migration based testing
  src/Database/Schema/SqliteSchemaDialect.php
  tests/TestCase/Database/Schema/SqliteSchemaTest.php
Labels: bug

#17431 5.next: add deprecation warning for `_cake_core_` cache config
  src/I18n/I18n.php
Labels: deprecations

#17412 RFC: Add basic PHPStan validation for split packages.
  .gitattributes
  .github/workflows/ci.yml
  contrib/validate-split-packages-phpstan.php
  contrib/validate-split-packages.php
  psalm.xml
  src/Validation/.gitattributes
  src/Validation/composer.json
  src/Validation/phpstan.neon.dist
  src/Validation/tests/phpstan-bootstrap.php
Labels: dependencies

#17438 Document possible types as per 5.x
  src/I18n/Number.php
  src/View/Helper/NumberHelper.php
Labels: documentation

#17443 Make PHPStan see the code better.
  src/Command/CompletionCommand.php
  src/ORM/Association/BelongsToMany.php
  src/ORM/Association/HasMany.php
  src/ORM/Association/Loader/SelectLoader.php
  src/ORM/Association/Loader/SelectWithPivotLoader.php
  src/ORM/Behavior/CounterCacheBehavior.php
  src/ORM/Behavior/Translate/ShadowTableStrategy.php
  src/ORM/Rule/ExistsIn.php
  src/ORM/Rule/IsUnique.php
  src/ORM/Table.php
Labels: testing

#17444 Make PHPStan see the code better.
  src/Collection/CollectionTrait.php
  src/Database/Driver/Sqlserver.php
  src/Database/FieldTypeConverter.php
  src/Database/Query.php
  src/Database/Query/InsertQuery.php
  src/Database/Query/UpdateQuery.php
  src/Database/QueryCompiler.php
  src/Database/Type/DateTimeType.php
  src/Database/Type/DateType.php
  src/Database/Type/TimeType.php
  src/Http/Client/Adapter/Mock.php
  src/I18n/RelativeTimeFormatter.php
  src/Utility/Xml.php
  src/View/Form/EntityContext.php
Labels: cleanup

#17445 Make PHPStan see the code better.
  src/Database/Driver/Sqlserver.php
  src/ORM/Association/BelongsToMany.php
Labels: cleanup

#17442 Drop unused exception class.
  src/Routing/Exception/MissingDispatcherFilterException.php
  tests/TestCase/ExceptionsTest.php
Labels: cleanup

#17446 Local Redis seems to be able to return false
  psalm-baseline.xml
  src/Cache/Engine/RedisEngine.php
Labels: testing

#17452 Fix up nullable type on protected method.
  src/Database/Expression/BetweenExpression.php
Labels: bug

#17454 Made FormHelper methods visible that are tested.
  src/View/Helper/FormHelper.php
  tests/TestCase/Console/CommandTest.php
  tests/TestCase/Console/ConsoleIoTest.php
  tests/TestCase/Core/BasePluginTest.php
  tests/TestCase/Database/Driver/MysqlTest.php
  tests/TestCase/Database/Driver/SqliteTest.php
  tests/TestCase/Database/Expression/QueryExpressionTest.php
  tests/TestCase/Database/QueryTests/TupleComparisonQueryTest.php
  tests/TestCase/Database/Type/IntegerTypeTest.php
  tests/TestCase/Datasource/Paging/PaginatorTestTrait.php
  tests/TestCase/Http/ContentTypeNegotiationTest.php
  tests/TestCase/Http/Session/DatabaseSessionTest.php
  tests/TestCase/I18n/DateTimeTest.php
  tests/TestCase/I18n/TimeTest.php
  tests/TestCase/Log/LogTest.php
  tests/TestCase/Mailer/MailerTest.php
  tests/TestCase/View/CellTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
  tests/TestCase/View/ViewTest.php
Labels: testing

#17455 Revert problematic assert.
  src/Database/Type/DateTimeType.php
Labels: cleanup

#17460 Use strict comparison with string
  src/Validation/Validation.php
Labels: cleanup
