Repository cakephp/cakephp, pull requests merged in 2023-10, with the labels that each got.

#17328 Fix type
  src/View/View.php
Labels: cleanup

#17326 5.1 security headers permissions policy
  src/Http/Middleware/SecurityHeadersMiddleware.php
  tests/TestCase/Http/Middleware/SecurityHeadersMiddlewareTest.php
Labels: enhancement, http

#17337 Add trailing newline for generated file
  src/Command/PluginLoadCommand.php
Labels: cleanup

#17341 Fix up test suite constraint messages.
  src/Console/TestSuite/Constraint/ContentsContain.php
  src/Console/TestSuite/Constraint/ExitCode.php
  tests/TestCase/Console/TestSuite/ConsoleIntegrationTestTraitTest.php
Labels: bug

#17340 Throw exception on invalid invalid key for Collection::combine()
  src/Collection/CollectionTrait.php
  tests/TestCase/Collection/CollectionTest.php
Labels: collection

#17356 Allow both psr/container versions.
  composer.json
  src/Core/composer.json
Labels: dependencies, bug

#17361 Fix up CI for deprecation alerts.
  .github/workflows/ci.yml
  contrib/validate-deprecation-aliases.php
  src/I18n/Date.php
  src/I18n/DateTime.php
  src/ORM/Query/SelectQuery.php
Labels: bug

#17352 Don't silently convert invalid enum values to null.
  src/Database/Type/EnumType.php
  tests/TestCase/Database/Type/EnumTypeTest.php
Labels: defect

#17359 Allow both psr/simple-cache constraint versions.
  composer.json
  src/Database/composer.json
  src/I18n/composer.json
Labels: dependencies, bug

#17360 Allow both psr/http-message constraint versions.
  composer.json
  src/Http/composer.json
  src/Validation/composer.json
Labels: dependencies, bug

#17362 Add split package validation.
  contrib/validate-split-packages.php
Labels: dependencies, cleanup

#17365 FormHelper Backed Enum support
  src/Database/Type/EnumType.php
  src/Database/TypeFactory.php
  src/View/Helper/FormHelper.php
  tests/TestCase/ORM/ColumnSchemaAwareTypeIntegrationTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/test_app/TestApp/Model/Enum/ArticleStatusLabel.php
Labels: enhancement

#17371 4.x: wrap namespaced core functions in function_exists to make upgrade tool work again
  src/Core/functions.php
Labels: bug

#17380 Fix DateTimeWidget usage with ChronosTime instance.
  src/View/Widget/DateTimeWidget.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: defect

#17381 Clarify a less radical fix.
  src/Datasource/ModelAwareTrait.php
Labels: RFC, documentation, deprecations

#17386 add table schema mapping for sqlite3 UUID_TEXT column type
  src/Database/Schema/SqliteSchemaDialect.php
  tests/TestCase/Database/Schema/SqliteSchemaTest.php
Labels: bug

#17395 5.next: add --with-middlewares option to RoutesCommand
  src/Command/RoutesCommand.php
  tests/TestCase/Command/RoutesCommandTest.php
  tests/test_app/TestApp/Application.php
Labels: enhancement, console
