Repository cakephp/cakephp, pull requests merged in 2024-03, with the labels that each got.

#17609 5.x: fix undefined property warning
  phpstan-baseline.neon
  src/Console/ConsoleInput.php
Labels: bug

#17608 Fix up parsing of datetime string with microseconds.
  src/Database/Type/DateTimeType.php
  tests/TestCase/Database/Type/DateTimeTypeTest.php
Labels: bug

#17611 Add test for int backed in Form control().
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/schema.php
  tests/test_app/TestApp/Model/Enum/Priority.php
Labels: testing

#17617 Fix up notice on CLI.
  phpstan-baseline.neon
  src/Console/ConsoleOutput.php
Labels: bug

#17622 Add test case for behavior loading.
  tests/TestCase/ORM/TableTest.php
Labels: testing

#17629 Cleanup
  src/Core/BasePlugin.php
Labels: cleanup

#17636 Fix up exception message.
  src/Database/Schema/TableSchema.php
Labels: enhancement

#17635 Fix backed int validation for forms.
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: bug

#17630 Add pathCombine() helper to Core functions
  src/Core/functions.php
  src/Core/functions_global.php
  tests/TestCase/Core/FunctionsTest.php
Labels: enhancement

#17633 Reverse connection aliasing logic to restore previous behavior
  src/TestSuite/ConnectionHelper.php
  tests/TestCase/TestSuite/ConnectionHelperTest.php
Labels: bug

#17632 Implements only/except enum validation.
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: enhancement

#17639 5.1 app plugin collection
  src/Core/Plugin.php
  src/Core/TestSuite/ContainerStubTrait.php
  src/Http/BaseApplication.php
  src/TestSuite/IntegrationTestTrait.php
  src/TestSuite/MiddlewareDispatcher.php
  src/TestSuite/TestCase.php
  tests/TestCase/Command/RoutesCommandTest.php
  tests/TestCase/Console/Command/HelpCommandTest.php
  tests/TestCase/Routing/AssetTest.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
  tests/TestCase/View/Helper/UrlHelperTest.php
  tests/test_app/TestApp/Application.php
Labels: cleanup
