Repository cakephp/cakephp, pull requests merged in 2024-04, with the labels that each got.

#17634 Add methods to RulesChecker to remove rules.
  src/Datasource/RulesChecker.php
  tests/TestCase/Datasource/RulesCheckerTest.php
Labels: enhancement

#17651 Allow better debugging of response body.
  src/TestSuite/IntegrationTestTrait.php
Labels: testing

#17648 Clear output/error on each call to exec()
  src/Console/TestSuite/ConsoleIntegrationTestTrait.php
  src/Console/TestSuite/StubConsoleOutput.php
  tests/TestCase/Console/TestSuite/ConsoleIntegrationTestTraitTest.php
Labels: enhancement, testing, console

#17663 Avoid lock file being created for vendor lib root
  composer.json
Labels: cleanup

#17643 Console Commands: Add default value for arguments
  src/Console/ConsoleInputArgument.php
  src/Console/ConsoleOptionParser.php
  tests/TestCase/Console/ConsoleOptionParserTest.php
  tests/TestCase/Console/HelpFormatterTest.php
Labels: enhancement

#17664 Use constant instead of string.
  src/ORM/EagerLoader.php
Labels: cleanup

#17642 Console Commands: Add default value for arguments
  src/Console/ConsoleInputArgument.php
  src/Console/ConsoleOptionParser.php
  tests/TestCase/Console/ConsoleOptionParserTest.php
  tests/TestCase/Console/HelpFormatterTest.php
Labels: backport
