Repository cakephp/cakephp, pull requests merged in 2024-07, with the labels that each got.

#17724 Update/fix docblocks.
  src/Routing/RouteBuilder.php
  src/Routing/Router.php
Labels: documentation

#17733 5.1 Add support for geospatial types
  src/Database/Schema/MysqlSchemaDialect.php
  src/Database/Schema/PostgresSchemaDialect.php
  src/Database/Schema/SqliteSchemaDialect.php
  src/Database/Schema/SqlserverSchemaDialect.php
  src/Database/Schema/TableSchema.php
  src/Database/Schema/TableSchemaInterface.php
  tests/TestCase/Database/Schema/MysqlSchemaTest.php
  tests/TestCase/Database/Schema/PostgresSchemaTest.php
  tests/TestCase/Database/Schema/SqliteSchemaTest.php
  tests/TestCase/Database/Schema/SqlserverSchemaTest.php
Labels: enhancement

#17742 5.1 datetime type
  src/Database/Type/DateTimeFractionalType.php
  src/Database/Type/DateTimeType.php
  tests/TestCase/Database/Type/DateTimeFractionalTypeTest.php
Labels: database
