Repository cakephp/cakephp, pull requests merged in 2024-12, with the labels that each got.

#18062 Try reenabling Redis tests for PHP 8.4
  tests/TestCase/Cache/Engine/RedisEngineTest.php
Labels: testing

#18060 Add deprecation warning.
  src/View/Helper/FormHelper.php
Labels: deprecations

#18063 properly catch warnings in tests
  tests/TestCase/Cache/CacheTest.php
  tests/TestCase/Core/FunctionsGlobalTest.php
  tests/TestCase/Core/FunctionsTest.php
  tests/TestCase/Datasource/Paging/PaginatorTestTrait.php
  tests/TestCase/ORM/TableTest.php
Labels: cleanup

#18077 Mention casting to string for debugging
  src/Database/Query.php
Labels: enhancement, documentation

#18076 Drop ORM.mapJsonTypeForSqlite config.
  src/Database/Schema/SqliteSchemaDialect.php
  tests/TestCase/Database/Driver/SqliteTest.php
Labels: cleanup

#18069 5.x: fix more warnings in tests
  tests/TestCase/Cache/CacheTest.php
  tests/TestCase/Network/SocketTest.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
Labels: cleanup

#18080 Remove redundant condition
  src/Database/Query/SelectQuery.php
  src/View/Helper/FormHelper.php
Labels: cleanup

#18082 Fix up strack trace for ErrorTrap handleError()
  src/Error/ErrorTrap.php
Labels: bug

#18085 Update composer.json
  composer.json
Labels: cleanup

#18091 improve validation docs
  src/Validation/Validation.php
  src/Validation/Validator.php
Labels: validation, documentation

#18093 4.x: fix ORM querys not being able to set read role
  src/ORM/Query/SelectQuery.php
  tests/TestCase/ORM/QueryTest.php
Labels: ORM, bug

#17964 Allow setting session lifetime from middleware before starting session
  src/Http/Session.php
  tests/TestCase/Http/SessionTest.php
Labels: needs squashing

#18101 Drop usage of deprecated phpunit API
  phpstan-baseline.neon
  src/TestSuite/TestCase.php
  tests/TestCase/TestSuite/TestCaseTest.php
Labels: cleanup

#18105 5.x: fix console subpackage
  src/Console/TestSuite/ConsoleIntegrationTestTrait.php
  src/Core/TestSuite/ContainerStubTrait.php
Labels: testing, console

#18106 Remove unneeded FileWidget and related template.
  src/View/Helper/FormHelper.php
  src/View/Widget/FileWidget.php
  tests/TestCase/View/Widget/FileWidgetTest.php
Labels: cleanup

#18108 Update deprecated usage.
  tests/TestCase/Datasource/Paging/PaginatorTestTrait.php
Labels: deprecations

#18107 Remove deprecated code.
  src/Console/Arguments.php
  src/Controller/Exception/AuthSecurityException.php
  src/Controller/Exception/SecurityException.php
  src/Datasource/Paging/PaginatedResultSet.php
  src/Datasource/RepositoryInterface.php
  src/I18n/FrozenDate.php
  src/I18n/FrozenTime.php
  src/I18n/I18n.php
  src/Log/Engine/BaseLog.php
  src/Mailer/Mailer.php
  src/ORM/Table.php
  src/Validation/RulesProvider.php
  src/View/Helper/FormHelper.php
  tests/TestCase/Console/ArgumentsTest.php
  tests/TestCase/Controller/Exception/AuthSecurityExceptionTest.php
  tests/TestCase/Controller/Exception/SecurityExceptionTest.php
  tests/TestCase/Datasource/Paging/PaginatedResultSetTest.php
  tests/TestCase/Datasource/Paging/PaginatorTestTrait.php
  tests/TestCase/Log/LogTest.php
  tests/TestCase/Mailer/MailerTest.php
  tests/TestCase/ORM/AssociationTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/Validation/RulesProviderTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: deprecations

#18116 Drop class aliases
  src/Console/TestSuite/ConsoleIntegrationTestTrait.php
  src/Console/TestSuite/Constraint/ContentsBase.php
  src/Console/TestSuite/Constraint/ContentsContain.php
  src/Console/TestSuite/Constraint/ContentsContainRow.php
  src/Console/TestSuite/Constraint/ContentsEmpty.php
  src/Console/TestSuite/Constraint/ContentsNotContain.php
  src/Console/TestSuite/Constraint/ContentsRegExp.php
  src/Console/TestSuite/Constraint/ExitCode.php
  src/Console/TestSuite/MissingConsoleInputException.php
  src/Console/TestSuite/StubConsoleInput.php
  src/Console/TestSuite/StubConsoleOutput.php
  src/Controller/ControllerFactory.php
  src/Core/TestSuite/ContainerStubTrait.php
  src/Http/TestSuite/HttpClientTrait.php
  src/I18n/Date.php
  src/I18n/DateTime.php
  src/ORM/Query.php
  tests/TestCase/ORM/Association/HasManyTest.php
  tests/TestCase/ORM/Association/HasOneTest.php
  tests/TestCase/ORM/Query/SelectQueryTest.php
  tests/TestCase/ORM/TableTest.php
  tests/test_app/TestApp/Model/Behavior/SluggableBehavior.php
Labels: cleanup
