Repository cakephp/cakephp, pull requests merged in 2024-01, with the labels that each got.

#17510 5.next: fix behavior change introduced in phpunit 10.5.5
  composer.json
  src/TestSuite/TestCase.php
  tests/TestCase/Datasource/Paging/PaginatedResultSetTest.php
  tests/TestCase/Log/LogTest.php
  tests/TestCase/ORM/AssociationTest.php
  tests/TestCase/ORM/TableTest.php
  tests/TestCase/TestSuite/TestCaseTest.php
Labels: testing

#17515 Use consistent CamelCase for enum case def.
  src/View/Helper/FormHelper.php
  tests/TestCase/Database/Type/EnumTypeTest.php
  tests/TestCase/Validation/ValidationTest.php
  tests/TestCase/Validation/ValidatorTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/test_app/TestApp/Model/Enum/ArticleStatus.php
  tests/test_app/TestApp/Model/Enum/ArticleStatusLabel.php
  tests/test_app/TestApp/Model/Enum/ArticleStatusLabelInterface.php
  tests/test_app/TestApp/Model/Enum/NonBacked.php
  tests/test_app/TestApp/Model/Enum/Priority.php
Labels: cleanup

#17523 Fix up enum value typo.
  src/Database/DriverFeatureEnum.php
  src/Database/Query.php
  src/Database/Type/EnumType.php
  src/Datasource/ModelAwareTrait.php
  src/Error/Middleware/ErrorHandlerMiddleware.php
  src/Error/Renderer/WebExceptionRenderer.php
  src/Http/Server.php
  src/Http/Session.php
  src/Http/UploadedFileFactory.php
  src/Utility/Text.php
  src/View/Helper/FormHelper.php
  tests/TestCase/Database/Type/EnumTypeTest.php
  tests/TestCase/Validation/ValidationTest.php
  tests/TestCase/Validation/ValidatorTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/test_app/TestApp/Model/Enum/ArticleStatus.php
  tests/test_app/TestApp/Model/Enum/ArticleStatusLabel.php
  tests/test_app/TestApp/Model/Enum/ArticleStatusLabelInterface.php
  tests/test_app/TestApp/Model/Enum/Priority.php
Labels: bug

#17518 Move serialized keys into method.
  src/View/JsonView.php
  src/View/SerializedView.php
  src/View/XmlView.php
Labels: cleanup

#17519 Avoid Typed property not init exception.
  src/ORM/Association/BelongsToMany.php
Labels: bug

#17506 Fix up socket tests.
  tests/TestCase/Network/SocketTest.php
Labels: testing

#17521 5.next: static ConnectionHelper
  src/TestSuite/ConnectionHelper.php
  src/TestSuite/Fixture/Extension/PHPUnitStartedSubscriber.php
  src/TestSuite/Fixture/FixtureHelper.php
  src/TestSuite/Fixture/SchemaLoader.php
  tests/TestCase/TestSuite/ConnectionHelperTest.php
  tests/TestCase/TestSuite/Fixture/SchemaLoaderTest.php
Labels: testing

#17526 Fix up docblocks for assoc options and list arrays.
  src/Command/Helper/ProgressHelper.php
  src/Command/I18nExtractCommand.php
  src/Command/PluginLoadCommand.php
  src/Console/TestSuite/Constraint/ContentsBase.php
  src/Controller/Controller.php
  src/Controller/ErrorController.php
  src/Core/Configure.php
  src/Database/Connection.php
  src/Database/Driver.php
  src/Database/Type/BatchCastingInterface.php
  src/Datasource/RepositoryInterface.php
  src/Form/FormProtector.php
  src/Http/ContentTypeNegotiation.php
  src/Mailer/Renderer.php
  src/ORM/Association.php
  src/ORM/Table.php
  src/Validation/Validation.php
  src/View/Helper/FormHelper.php
  src/View/Helper/PaginatorHelper.php
Labels: documentation

#17528 5.x: fix CollectionTrait::combine not working with BackedEnums in keyfield
  src/Collection/CollectionTrait.php
  tests/TestCase/Collection/CollectionTest.php
Labels: collection

#17529 Fix up list<type> docblocks.
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Command/RoutesGenerateCommand.php
  src/Console/Command/HelpCommand.php
  src/Console/CommandRunner.php
  src/Console/CommandScanner.php
  src/Console/ConsoleInputArgument.php
  src/Console/ConsoleInputOption.php
  src/Console/Exception/MissingOptionException.php
  src/Database/TypeFactory.php
  src/Datasource/EntityInterface.php
  src/Datasource/EntityTrait.php
  src/Http/Client/Response.php
  src/Http/Cookie/CookieCollection.php
  src/Http/CorsBuilder.php
  src/Http/Middleware/BodyParserMiddleware.php
  src/Http/Middleware/EncryptedCookieMiddleware.php
  src/Http/Middleware/SecurityHeadersMiddleware.php
  src/Http/ServerRequest.php
  src/Http/TestSuite/HttpClientTrait.php
  src/I18n/MessagesFileLoader.php
  src/Mailer/Transport/SmtpTransport.php
  src/ORM/Association/Loader/SelectLoader.php
  src/ORM/Behavior/TranslateBehavior.php
  src/ORM/LazyEagerLoader.php
  src/ORM/Query/SelectQuery.php
  src/ORM/Rule/IsUnique.php
  src/ORM/Rule/LinkConstraint.php
  src/ORM/RulesChecker.php
  src/ORM/Table.php
  src/Routing/Route/Route.php
  src/Routing/RouteBuilder.php
  src/Routing/RouteCollection.php
  src/TestSuite/Fixture/FixtureHelper.php
  src/TestSuite/Fixture/FixtureStrategyInterface.php
  src/TestSuite/IntegrationTestTrait.php
  src/TestSuite/TestCase.php
  src/Utility/MergeVariablesTrait.php
  src/Utility/Text.php
  src/Utility/Xml.php
  src/Validation/Validation.php
  src/Validation/Validator.php
  src/View/Exception/MissingCellTemplateException.php
  src/View/Exception/MissingTemplateException.php
  src/View/Form/EntityContext.php
Labels: documentation

#17532 5.x: prevent CollectionTrait::combine keypath being used with non-backed enums
  src/Collection/CollectionTrait.php
  tests/TestCase/Collection/CollectionTest.php
Labels: collection

#17539 Revert for case when cell is not part of view.
  src/View/CellTrait.php
Labels: bug

#17540 Prefer defined vars over undefined checks.
  src/Cache/CacheEngine.php
  src/Error/Renderer/WebExceptionRenderer.php
  src/Http/Client.php
  src/Http/Response.php
  src/I18n/I18n.php
  src/ORM/Behavior/CounterCacheBehavior.php
  src/Routing/Asset.php
  src/View/Form/ContextFactory.php
  tests/TestCase/Mailer/MessageTest.php
  tests/test_app/TestApp/Model/Entity/NonExtending.php
  tests/test_app/TestApp/Model/Table/AuthorsTable.php
Labels: cleanup

#17295 Methods for converting mixed values to specific data types
  src/Core/functions.php
  tests/TestCase/Core/FunctionsGlobalTest.php
  tests/TestCase/Core/FunctionsTest.php
Labels: enhancement

#17448 Use stricter PHPStan checking for better coverage.
  .editorconfig
  .github/workflows/ci.yml
  .phive/phars.xml
  composer.json
  phpcs.xml
  phpstan.neon.dist
  src/Database/Type/DateTimeType.php
  src/View/View.php
Labels: testing, github_actions

#17543 5.next: add plugin versions to `plugin list` command
  src/Command/PluginListCommand.php
  src/Core/PluginConfig.php
  tests/TestCase/Command/PluginListCommandTest.php
  tests/TestCase/Core/PluginConfigTest.php
  tests/composer.lock
Labels: console

#17144 [4.5] TLS Support for RedisEngine
  src/Cache/Engine/RedisEngine.php
  tests/TestCase/Cache/Engine/RedisEngineTest.php
Labels: enhancement, cache

#17555 Psalm suggested fixes.
  src/Collection/CollectionTrait.php
  src/Collection/ExtractTrait.php
  src/Collection/Iterator/TreeIterator.php
  src/Database/Driver.php
  src/Database/Expression/QueryExpression.php
  src/ORM/Association/Loader/SelectLoader.php
  src/ORM/Marshaller.php
  src/ORM/Table.php
  src/View/Cell.php
Labels: cleanup

#17566 Fix up Date regression
  src/Database/Type/DateTimeType.php
  tests/TestCase/Database/Type/DateTimeTypeTest.php
Labels: bug

#17567 Fix up assoc docblock
  src/Routing/Route/Route.php
Labels: documentation

#17573 Fix validation of ChronosTime instances.
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: validation
