Repository cakephp/cakephp, pull requests merged in 2024-09, with the labels that each got.

#17881 5.next: unmockify the testsuite for Routing & View
  tests/TestCase/Routing/Middleware/RoutingMiddlewareTest.php
  tests/TestCase/Routing/Route/RouteTest.php
  tests/TestCase/Routing/RouterTest.php
  tests/TestCase/TestSuite/Fixture/FixtureHelperTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
  tests/TestCase/View/HelperTest.php
Labels: testing

#17890 Fix docblock
  src/TestSuite/TestCase.php
Labels: documentation

#17882 17857 - Add support for INTERSECT and INTERSECT ALL clauses in ORM
  src/Database/Driver/Mysql.php
  src/Database/Driver/Postgres.php
  src/Database/Driver/Sqlite.php
  src/Database/Driver/Sqlserver.php
  src/Database/DriverFeatureEnum.php
  src/Database/Query.php
  src/Database/Query/SelectQuery.php
  src/Database/QueryCompiler.php
  src/Database/SqliteCompiler.php
  src/Database/SqlserverCompiler.php
  src/ORM/Query/SelectQuery.php
  tests/TestCase/Database/Driver/MysqlTest.php
  tests/TestCase/Database/Driver/PostgresTest.php
  tests/TestCase/Database/Driver/SqliteTest.php
  tests/TestCase/Database/Driver/SqlserverTest.php
  tests/TestCase/Database/Query/SelectQueryTest.php
Labels: enhancement, ORM

#17889 Chore/cleanup
  psalm-baseline.xml
  src/Collection/CollectionTrait.php
  src/Collection/Iterator/BufferedIterator.php
  src/Collection/Iterator/ReplaceIterator.php
  src/Collection/Iterator/UniqueIterator.php
Labels: cleanup

#17891 deprecate `Mailer::setMessage`
  src/Mailer/Mailer.php
  tests/TestCase/Mailer/MailerTest.php
Labels: mailer, deprecations

#17892 replace @method docbloc with @mixin where possible
  src/Mailer/Mailer.php
  src/ORM/Behavior/TranslateBehavior.php
  src/View/Helper/NumberHelper.php
  src/View/Helper/TextHelper.php
Labels: cleanup

#17895 Optimize code
  src/View/Helper/TimeHelper.php
Labels: optimization

#17898 Remove redundant condition
  src/Collection/CollectionTrait.php
Labels: cleanup

#17897 restore passed down args assertions
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Datasource/Paging/PaginatedResultSetTest.php
  tests/TestCase/Error/Renderer/WebExceptionRendererTest.php
  tests/TestCase/Event/EventManagerTest.php
  tests/TestCase/Routing/Route/RouteTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: testing

#17905 Fix docblock
  src/Collection/CollectionInterface.php
Labels: documentation

#17916 wrap core functions in function_exists
  src/Core/functions.php
Labels: bug

#17907 Fix form's request type inference.
  src/View/Helper/FormHelper.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: defect

#17919 fix PHP 8.4 MailerTest
  tests/TestCase/Mailer/MailerTest.php
Labels: testing

#17922 Reset current page when changing per page limit.
  src/View/Helper/PaginatorHelper.php
  tests/TestCase/View/Helper/PaginatorHelperTest.php
Labels: defect

#17909 Add gettext compatible paths to the list of translation folders
  src/I18n/MessagesFileLoader.php
  tests/TestCase/I18n/MessagesFileLoaderTest.php
Labels: i18n
