Repository cakephp/cakephp, pull requests merged in 2024-11, with the labels that each got.

#17979 Add trim of padding zeros in convertors toInt and toFloat
  src/Core/functions.php
  tests/TestCase/Core/FunctionsTest.php
Labels: enhancement, needs squashing

#18011 Fix client side buffering disabling for SqlServer.
  src/Database/Driver/Sqlserver.php
  tests/TestCase/Database/Driver/SqlserverTest.php
Labels: defect

#18012 Add MimeType class.
  src/Controller/Controller.php
  src/Http/MimeType.php
  src/Http/Response.php
  src/Routing/Middleware/AssetMiddleware.php
  src/TestSuite/Constraint/Response/ContentType.php
  src/View/Helper/HtmlHelper.php
  tests/TestCase/Http/MimeTypeTest.php
  tests/TestCase/Http/ResponseTest.php
Labels: enhancement

#18017 Fix XML to not break with enums.
  src/Utility/Xml.php
  tests/TestCase/Utility/XmlTest.php
Labels: bug

#17956 Command lists separator
  src/Console/Arguments.php
  src/Console/BaseCommand.php
  src/Console/ConsoleInputArgument.php
  src/Console/ConsoleInputOption.php
  src/Console/ConsoleOptionParser.php
  tests/TestCase/Console/ArgumentsTest.php
  tests/TestCase/Console/ConsoleInputArgumentTest.php
  tests/TestCase/Console/ConsoleInputOptionTest.php
  tests/TestCase/Console/ConsoleOptionParserTest.php
Labels: enhancement, needs squashing

#18020 Allow 4.x callable to continue working in 5.x.
  src/Event/EventManager.php
  tests/TestCase/Event/EventManagerTest.php
Labels: bug

#18014 get ready for phpstan 2.0
  .github/workflows/ci.yml
  .phive/phars.xml
  composer.json
  contrib/validate-split-packages-phpstan.php
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm-baseline.xml
  src/Cache/Engine/FileEngine.php
  src/Collection/CollectionTrait.php
  src/Collection/Iterator/TreeIterator.php
  src/Collection/Iterator/TreePrinter.php
  src/Command/Helper/BannerHelper.php
  src/Console/CommandScanner.php
  src/Console/ConsoleInputOption.php
  src/Controller/Controller.php
  src/Core/StaticConfigTrait.php
  src/Database/Query.php
  src/Database/Type/DecimalType.php
  src/Database/Type/ExpressionTypeCasterTrait.php
  src/Database/Type/FloatType.php
  src/Database/phpstan.neon.dist
  src/Datasource/ConnectionManager.php
  src/Datasource/QueryCacher.php
  src/Datasource/phpstan.neon.dist
  src/Form/FormProtector.php
  src/Http/Client/Adapter/Stream.php
  src/Http/Client/Auth/Oauth.php
  src/Http/Client/Request.php
  src/Http/Client/Response.php
  src/Http/ServerRequest.php
  src/Http/phpstan.neon.dist
  src/Network/Socket.php
  src/ORM/Behavior/Translate/ShadowTableStrategy.php
  src/ORM/Locator/TableLocator.php
  src/ORM/Marshaller.php
  src/ORM/phpstan.neon.dist
  src/Routing/Middleware/RoutingMiddleware.php
  src/Routing/RouteCollection.php
  src/TestSuite/TestCase.php
  src/Utility/Filesystem.php
  src/Validation/Validation.php
  src/Validation/phpstan.neon.dist
  src/View/Form/EntityContext.php
  src/View/StringTemplate.php
  src/View/View.php
  src/View/Widget/SelectBoxWidget.php
  tests/PHPStan/AssociationTableMixinClassReflectionExtension.php
  tests/PHPStan/TableFindByPropertyMethodReflection.php
  tests/phpstan-baseline.neon
  tests/phpstan.neon
Labels: needs squashing

#18028 Fix up list array for input.
  src/Database/Expression/CommonTableExpression.php
  src/Http/Client/Adapter/Stream.php
  src/View/Form/EntityContext.php
Labels: documentation

#18026 Fix up deprecations on interface
  src/Datasource/QueryInterface.php
Labels: deprecations

#18030 Fix up array docblock.
  src/Datasource/QueryInterface.php
  src/Datasource/phpstan.neon.dist
  src/ORM/Query/SelectQuery.php
Labels: documentation

#18031 Fix up docblocks and code cleanup.
  src/Collection/CollectionInterface.php
  src/Console/BaseCommand.php
  src/Console/CommandRunner.php
  src/Error/Debugger.php
  src/Error/Renderer/ConsoleExceptionRenderer.php
  src/Http/MiddlewareQueue.php
  src/ORM/Query/SelectQuery.php
  src/ORM/Table.php
  src/Routing/Asset.php
  src/TestSuite/LogTestTrait.php
  src/Validation/Validation.php
  src/View/Helper/FormHelper.php
  src/View/Helper/UrlHelper.php
Labels: cleanup

#18034 Fix typos and small cleanup.
  src/Collection/Iterator/NestIterator.php
  src/Console/Arguments.php
  src/Console/BaseCommand.php
  src/Core/Retry/CommandRetry.php
  src/Database/Connection.php
  src/Database/Driver.php
  src/Database/Exception/NestedTransactionRollbackException.php
  src/Database/Expression/AggregateExpression.php
  src/Database/Expression/BetweenExpression.php
  src/Datasource/EntityInterface.php
  src/Datasource/EntityTrait.php
  src/Datasource/Paging/NumericPaginator.php
  src/Http/Client/Exception/NetworkException.php
  src/Http/ContentTypeNegotiation.php
  src/Http/Cookie/Cookie.php
  src/Http/HeaderUtility.php
  src/Http/Middleware/HttpsEnforcerMiddleware.php
  src/Log/Formatter/AbstractFormatter.php
  src/Mailer/TransportFactory.php
  src/Mailer/TransportRegistry.php
  src/ORM/Association.php
  src/ORM/Behavior/TimestampBehavior.php
  src/ORM/Behavior/Translate/TranslateStrategyTrait.php
  src/ORM/Behavior/TranslateBehavior.php
  src/ORM/PropertyMarshalInterface.php
  src/TestSuite/StringCompareTrait.php
  src/Utility/Xml.php
  src/Validation/ValidatorAwareTrait.php
  src/View/Form/ArrayContext.php
  src/View/HelperRegistry.php
  src/View/ViewBlock.php
  src/View/Widget/MultiCheckboxWidget.php
  src/View/Widget/RadioWidget.php
  src/View/Widget/YearWidget.php
  tests/TestCase/Database/Type/DateTimeTypeTest.php
Labels: cleanup

#18043 Warn about non applied pagination config
  src/Datasource/Paging/NumericPaginator.php
Labels: documentation

#18042 Fix up 5xx to 4xx for externally invoked bad URLs.
  src/View/View.php
  tests/TestCase/View/ViewTest.php
Labels: bug

#18053 Fix some more typos.
  src/Core/ConventionsTrait.php
  src/I18n/Date.php
  src/I18n/DateTime.php
  src/ORM/Behavior/Translate/TranslateStrategyInterface.php
  src/ORM/Behavior/Translate/TranslateStrategyTrait.php
  src/ORM/Behavior/TranslateBehavior.php
  src/Utility/Security.php
Labels: documentation
