Repository cakephp/cakephp, pull requests merged in 2025-03, with the labels that each got.

#18218 Fix SQL UPDATE with columns containing spaces
  src/Database/Query/UpdateQuery.php
Labels: database, bug

#18222 Add SSL support to Postgres driver
  src/Database/Driver/Postgres.php
  tests/TestCase/Database/Driver/PostgresTest.php
Labels: enhancement, needs squashing

#18213 Added support for strict fields check in fixtures
  src/TestSuite/Fixture/TestFixture.php
  tests/TestCase/TestSuite/Fixture/TestFixtureTest.php
Labels: enhancement, fixtures, needs squashing

#18250 Make NullEngine return the original keys like other engines
  src/Cache/Engine/NullEngine.php
  tests/TestCase/Cache/Engine/NullEngineTest.php
Labels: bug

#18255 Fix docblock
  src/Mailer/Mailer.php
Labels: documentation
