Repository cakephp/cakephp, pull requests merged in 2025-05, with the labels that each got.

#18396 Fix up custom MessagesFileLoader.
  src/I18n/TranslatorRegistry.php
  tests/TestCase/I18n/I18nTest.php
Labels: bug

#18409 Auto coerce ints to strings when creating Options
  src/Console/ConsoleOptionParser.php
  tests/TestCase/Console/ConsoleOptionParserTest.php
Labels: enhancement, needs squashing

#18626 Fix up support for Entity routes and enums.
  src/Routing/Route/Route.php
  tests/TestCase/Routing/Route/EntityRouteTest.php
Labels: enhancement

#18446 Add an option to Plugin Assets Symlink for a relative path. Has testcase.
  src/Command/PluginAssetsSymlinkCommand.php
  src/Command/PluginAssetsTrait.php
  tests/TestCase/Command/PluginAssetsCommandsTest.php
Labels: enhancement

#18613 Allow flushDb() usage
  src/Cache/Engine/RedisEngine.php
  tests/TestCase/Cache/Engine/RedisEngineTest.php
Labels: enhancement

#18628 5.next Add assertRedirectBack()
  src/TestSuite/IntegrationTestTrait.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
Labels: enhancement

#18651 5.next assert redirect back to referer
  src/TestSuite/IntegrationTestTrait.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
Labels: enhancement

#18652 Improving mockery integration
  src/TestSuite/TestCase.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Database/Type/StringTypeTest.php
  tests/TestCase/Datasource/Paging/PaginatedResultSetTest.php
  tests/TestCase/Http/ServerTest.php
  tests/TestCase/ORM/Association/BelongsToTest.php
  tests/TestCase/ORM/Association/HasManyTest.php
  tests/TestCase/ORM/Association/HasOneTest.php
  tests/TestCase/ORM/AssociationProxyTest.php
  tests/TestCase/ORM/BehaviorRegistryTest.php
  tests/TestCase/ORM/Rule/LinkConstraintTest.php
  tests/TestCase/Routing/Route/RouteTest.php
  tests/TestCase/TestSuite/TestCaseTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: testing

#18678 Dont use RCs.
  composer.json
Labels: cleanup

#18679 Fix up data provider usage tests.
  src/Utility/Xml.php
  tests/TestCase/View/XmlViewTest.php
Labels: testing

#18390 Fix assertions against session when enableRetainFlashMessages() is true
  src/TestSuite/IntegrationTestTrait.php
  tests/TestCase/TestSuite/IntegrationTestTraitTest.php
  tests/test_app/TestApp/Controller/PostsController.php
Labels: bug

#18682 Fix up allowMethod() signature.
  src/Http/ServerRequest.php
  tests/TestCase/Http/ServerRequestTest.php
Labels: cleanup

#18693 fix subjectless events throw before deprecation message is being display
  src/Event/EventManager.php
  tests/TestCase/Event/EventManagerTest.php
Labels: events, bug

#18703 Add Message::addAttachment()
  src/Mailer/Mailer.php
  src/Mailer/Message.php
  tests/TestCase/Mailer/MessageTest.php
Labels: enhancement, mailer
