Repository cakephp/cakephp, pull requests merged in 2025-01, with the labels that each got.

#18118 Cleanup code.
  src/Utility/Text.php
Labels: cleanup

#18121 Fix column ordering in postgres foreign key reflection
  src/Database/Schema/PostgresSchemaDialect.php
  tests/TestCase/Database/Schema/PostgresSchemaTest.php
Labels: postgres, database

#18122 Avoid empty() usage
  src/ORM/Entity.php
Labels: cleanup

#18039 6.x: rename _accessible to patchable
  src/Datasource/EntityInterface.php
  src/Datasource/EntityTrait.php
  src/Datasource/RepositoryInterface.php
  src/Http/Session/DatabaseSession.php
  src/ORM/Entity.php
  src/ORM/Marshaller.php
  src/ORM/Table.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/ORM/MarshallerTest.php
  tests/TestCase/ORM/TableTest.php
  tests/test_app/TestApp/Model/Entity/OpenArticleEntity.php
  tests/test_app/TestApp/Model/Entity/OpenTag.php
  tests/test_app/TestApp/Model/Entity/ProtectedArticle.php
  tests/test_app/TestApp/Model/Entity/ProtectedEntity.php
  tests/test_app/TestApp/Model/Entity/Session.php
  tests/test_app/TestApp/Model/Entity/TranslateBakedArticle.php
Labels: ORM

#18126 Use the entity class configured for the table instead of ORM\Entity.
  src/ORM/Behavior/Translate/EavStrategy.php
  src/ORM/Table.php
Labels: bug

#18130 Making I18n in Text Class optional
  src/Utility/Text.php
Labels: needs squashing

#18142 Delay database connection until the schema dialect is accessed
  src/Database/Schema/Collection.php
  tests/TestCase/Database/ConnectionTest.php
Labels: enhancement, needs squashing

#18139 5.2 Add SchemaDialect::describeColumns
  src/Database/Schema/SchemaDialect.php
  tests/TestCase/Database/Schema/SchemaDialectTest.php
Labels: enhancement, database

#18146 Add SchemaDialect::describeIndexes
  src/Database/Schema/SchemaDialect.php
  tests/TestCase/Database/Schema/SchemaDialectTest.php
Labels: enhancement

#18144 Add deleteLink() convenience method.
  src/View/Helper/FormHelper.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: enhancement

#18153 Show explicit warning for deprecated methods of the Database pacakge.
  src/Database/Expression/AggregateExpression.php
  src/Database/Expression/WindowExpression.php
  src/Database/IdentifierQuoter.php
  src/Database/Query.php
  src/Database/Query/SelectQuery.php
  tests/TestCase/Database/Expression/WindowExpressionTest.php
  tests/TestCase/Database/Query/SelectQueryTest.php
Labels: deprecations

#18151 Update Session.php renew() setcookie to avoid samesite warnings
  src/Http/Session.php
Labels: needs squashing

#18157 Don't remove index.php from the request path when URL rewriting is used.
  src/Http/UriFactory.php
  tests/TestCase/Http/ServerRequestFactoryTest.php
Labels: defect

#18165 Fix issues when "requireFieldPresence" is turned on for an entity.
  src/Datasource/EntityTrait.php
  src/View/Form/EntityContext.php
  tests/TestCase/ORM/EntityTest.php
  tests/TestCase/View/Form/EntityContextTest.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: defect

#18156 `FlashComponent::__call()` supports named parameters
  src/Controller/Component/FlashComponent.php
  tests/TestCase/Controller/Component/FlashComponentTest.php
Labels: enhancement

#18166 add IPv6 host capability for DSN string parsing
  src/Core/StaticConfigTrait.php
  tests/TestCase/Core/StaticConfigTraitTest.php
Labels: enhancement
