Repository cakephp/cakephp, pull requests merged in 2025-07, with the labels that each got.

#18763 Fixes InvalidArgumentException (#16362)
  src/ORM/EagerLoader.php
  tests/TestCase/ORM/TableTest.php
Labels: defect, database

#18788 #18787 Fixes datetime validation exception when a boolean is passed as value
  src/Validation/Validation.php
  tests/TestCase/Validation/ValidationTest.php
Labels: bug

#18790 Fix some spelling.
  src/Error/ErrorLogger.php
  src/Error/ErrorRendererInterface.php
  src/Error/ErrorTrap.php
  src/Error/ExceptionTrap.php
  src/Error/Renderer/ConsoleErrorRenderer.php
  src/Validation/Validator.php
Labels: documentation

#18791 Fix some spelling and broken code snippets.
  src/Cache/Engine/MemcachedEngine.php
  src/Collection/CollectionInterface.php
  src/Collection/Iterator/BufferedIterator.php
  src/Collection/Iterator/ExtractIterator.php
  src/Command/Helper/ProgressHelper.php
  src/Command/Helper/TableHelper.php
  src/Core/ServiceProvider.php
  src/Database/Driver/TupleComparisonTranslatorTrait.php
  src/Database/QueryCompiler.php
  src/Database/Schema/MysqlSchemaDialect.php
  src/Datasource/QueryInterface.php
  src/Datasource/README.md
  src/Datasource/RepositoryInterface.php
  src/Error/Debugger.php
  src/Http/Client/Response.php
  src/Http/ServerRequest.php
  src/Log/Engine/FileLog.php
  src/Log/Engine/SyslogLog.php
  src/Mailer/Message.php
  src/ORM/Behavior/Translate/EavStrategy.php
  src/ORM/Behavior/Translate/ShadowTableStrategy.php
  src/ORM/Query/CommonQueryTrait.php
  src/ORM/RulesChecker.php
  src/ORM/Table.php
  src/Routing/Route/RedirectRoute.php
  src/Routing/Route/Route.php
  src/Routing/Router.php
  src/TestSuite/Fixture/SchemaLoader.php
  src/Utility/Hash.php
  src/View/Helper/FormHelper.php
  src/View/Helper/HtmlHelper.php
  src/View/XmlView.php
  tests/TestCase/Http/Client/Auth/OauthTest.php
Labels: documentation

#18799 Consolidate Doc links
  src/Command/CacheClearCommand.php
  src/Command/CacheClearGroupCommand.php
  src/Command/CacheClearallCommand.php
  src/Command/CacheListCommand.php
  src/Console/ConsoleIo.php
  tests/TestCase/Database/Type/DecimalTypeTest.php
  tests/TestCase/Database/Type/FloatTypeTest.php
Labels: documentation
