Repository cakephp/cakephp, pull requests merged in 2025-02, with the labels that each got.

#18172 Optimize/cleanup marshaller code.
  src/Datasource/EntityTrait.php
  src/ORM/Marshaller.php
  tests/TestCase/ORM/EntityTest.php
Labels: ORM

#18174 Fix errors in TranslateBehavior with Entity::$requireFieldPresence enabled
  src/Datasource/EntityTrait.php
  src/ORM/Behavior/Translate/EavStrategy.php
  src/ORM/Behavior/Translate/ShadowTableStrategy.php
  src/ORM/Behavior/Translate/TranslateStrategyTrait.php
  src/ORM/Behavior/Translate/TranslateTrait.php
  tests/test_app/TestApp/Model/Entity/TranslateArticle.php
Labels: bug

#18196 Deprecate returning values from event listeners.
  src/Event/Event.php
  src/Event/EventManager.php
  src/ORM/Table.php
  tests/TestCase/Controller/ControllerTest.php
  tests/TestCase/Error/ErrorTrapTest.php
  tests/TestCase/Error/Middleware/ErrorHandlerMiddlewareTest.php
  tests/TestCase/Event/EventManagerTest.php
  tests/TestCase/ORM/MarshallerTest.php
  tests/TestCase/ORM/RulesCheckerIntegrationTest.php
  tests/TestCase/ORM/TableTest.php
  tests/test_app/TestApp/Auth/TestAuthenticate.php
Labels: enhancement

#18198 Use requestSubmit() instead of submit() in postLink
  src/View/Helper/FormHelper.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: enhancement

#18197 Add findOrCreate() support for array data.
  src/ORM/Table.php
  tests/TestCase/ORM/TableTest.php
Labels: enhancement

#18203 Added a callable message to the RuleInvoker.
  src/Datasource/RuleInvoker.php
  tests/TestCase/Datasource/RuleInvokerTest.php
Labels: enhancement, needs squashing

#18210 Fix FormHelper::create() with _path
  src/View/Helper/FormHelper.php
  tests/TestCase/View/Helper/FormHelperTest.php
Labels: bug
