Repository cakephp/cakephp, pull requests merged in 2025-08, with the labels that each got.

#18816 Split out toQuarterRange() from TimeHelper::toQuarter()
  src/I18n/DateTime.php
  src/View/Helper/TimeHelper.php
  tests/TestCase/I18n/DateTimeTest.php
  tests/TestCase/View/Helper/TimeHelperTest.php
Labels: cleanup

#18815 Split out getMapped() from getMap()
  src/Database/Schema/Column.php
  src/Database/Schema/SchemaDialect.php
  src/Database/TypeFactory.php
  tests/TestCase/Database/TypeFactoryTest.php
Labels: cleanup

#17982 Redis cluster support
  .github/workflows/ci.yml
  phpstan-baseline.neon
  src/Cache/Engine/RedisEngine.php
  tests/TestCase/Cache/Engine/RedisClusterEngineTest.php
  tests/TestCase/Cache/Engine/RedisEngineTest.php
Labels: enhancement, needs squashing

#18825 Fix up array handling for getEnv().
  src/Http/ServerRequest.php
  tests/TestCase/Http/ServerRequestTest.php
Labels: defect

#18828 Redis cluster improvements
  phpstan-baseline.neon
  src/Cache/Engine/RedisEngine.php
  tests/TestCase/Cache/Engine/RedisClusterEngineTest.php
  tests/TestCase/Cache/Engine/RedisEngineTest.php
Labels: enhancement

#18847 Fix failing test.
  tests/TestCase/ORM/TableTest.php
Labels: testing

#18841 5.x Fix methods to be extendable.
  src/Form/FormProtector.php
  src/Mailer/AbstractTransport.php
  src/Mailer/Mailer.php
  src/Mailer/Transport/SmtpTransport.php
  src/TestSuite/TestEmailTransport.php
Labels: documentation, needs squashing

#18848 Fix comments quoting in migrations.
  src/Database/Schema/MysqlSchemaDialect.php
  tests/TestCase/Database/Schema/MysqlSchemaDialectTest.php
Labels: defect, needs squashing

#18862 Update signature of Association::__construct()
  src/ORM/Association.php
  src/ORM/AssociationCollection.php
  src/ORM/Table.php
  tests/TestCase/ORM/Association/BelongsToManySaveAssociatedOnlyEntitiesAppendTest.php
  tests/TestCase/ORM/Association/BelongsToManyTest.php
  tests/TestCase/ORM/Association/BelongsToTest.php
  tests/TestCase/ORM/Association/HasManyTest.php
  tests/TestCase/ORM/Association/HasOneTest.php
  tests/TestCase/ORM/AssociationCollectionTest.php
  tests/TestCase/ORM/AssociationTest.php
  tests/TestCase/ORM/TableTest.php
Labels: ORM

#18858 Schema default expression
  src/Database/Driver.php
  src/Database/Schema/MysqlSchemaDialect.php
  src/Database/Schema/PostgresSchemaDialect.php
  src/Database/Schema/SqlserverSchemaDialect.php
  tests/TestCase/Database/Schema/MysqlSchemaDialectTest.php
  tests/TestCase/Database/Schema/PostgresSchemaDialectTest.php
  tests/TestCase/Database/Schema/SqliteSchemaDialectTest.php
  tests/TestCase/Database/Schema/SqlserverSchemaDialectTest.php
Labels: database

#18856 Add enablePluginLoadingForTests() and loadAllPlugins().
  src/TestSuite/TestCase.php
  src/TestSuite/functions.php
  tests/TestCase/TestSuite/PluginBootstrapTest.php
  tests/bootstrap.php
Labels: enhancement

#18853 Remove _ prefix in Utility
  src/Utility/CookieCryptTrait.php
  src/Utility/Inflector.php
  src/Utility/Security.php
  src/Utility/Text.php
Labels: cleanup
